- type: job
  abstract: true
  parent: AU14JobMilitaryBase
  displayWeight: 6
  id: AU14JobVehicleCommanderBaseAbstract
  name: au14-job-name-vehiclecommander
  description: au14-job-description-vehiclecommander
  icon: "AU14JobIconGovTankCommander"
  spawnMenuRoleName: au14-spawn-role-name-govfor-vehicle-commander
  startingGear: AU14GearGOVFORVehicleCommander
  dummyStartingGear: AU14GearGOVFORVehicleCommanderDummy
  playTimeTracker: AU14JobGOVFORVehicleCommander
  overwatchRoleName: au14-job-name-vehiclecommander
  overwatchSortPriority: -3
  accessGroups:
  - AU14GovforVehicleCrew

- type: job
  abstract: true
  parent: AU14JobVehicleCommanderBaseAbstract
  id: AU14JobVehicleCommanderBase
  roundRole: VehicleCommander
  roundProfiles:
  - AU14RoundJobProfileMilitaryBase
  roundComponents:
  - type: AU14CallsignRole
    suffix: "6"
    commandElement: true
    category: ARMOR
  - type: Skills
    skills:
      RMCSkillConstruction: 2
      RMCSkillCqc: 1
      RMCSkillEndurance: 1
      RMCSkillEngineer: 2
      RMCSkillFirearms: 1
      RMCSkillFireman: 2
      RMCSkillJtac: 1
      RMCSkillPowerLoader: 1
      RMCSkillVehicles: 3
      RMCSkillOverwatch: 1
      RMCSkillNavigations: 1
      RMCSkillIntel: 1
      RMCSkillMedical: 2
      RMCSkillSurgery: 1
      RMCSkillPolice: 1
      RMCSkillLeadership: 3
  - type: JobPrefix
    prefix: au14-job-prefix-vehiclecommander
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/CMU14/Interface/au14govforjobicons.rsi
      state: govfor_vcc
  roundForceComponents:
    OPFOR:
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/CMU14/Interface/au14opforjobicons.rsi
        state: vcc
  requirements:
#  - !type:RoleTimeRequirement
#    role: AU14JobGOVFORVehicleCrewman
#    time: 14400 # 4 hours
#  - !type:RoleTimeRequirement
#    role: AU14JobGOVFORSquadSergeant
#    time: 7200 # 2 hours
  - !type:AgeRequirement
    requiredAge: 25
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
    - NoEnglish
    - SlowRunner
    - Anemic
    - Asthmatic
  ranks:
    RMCRankCivilian: []
  chevrons:
    RMCRankSecondLT:
      entity: AU14ChevronSecondLT
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobGOVFORVehicleCommander
        time: 90000 #25 hours
    RMCRankChiefWarrantOfficer3:
      entity: AU14ChevronUSCMChiefWarrantOfficer3
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobGOVFORVehicleCommander
        time: 36000 #10 hours
    RMCRankChiefWarrantOfficer:
      entity: AU14ChevronUSCMChiefWarrantOfficer2
      requirements: []

- type: playTimeTracker
  id: AU14JobGOVFORVehicleCommander
  isHumanoid: true

- type: job
  parent: AU14JobVehicleCommanderBase
  id: AU14JobGOVFORVehicleCommander
  hidden: false
  setPreference: true
  basePlaytimeTracker: true

- type: startingGear
  id: AU14GearGOVFORVehicleCommander
  equipment:
    id: AU14IDCardGOVFORVehicleCommander
    ears: AU14HeadsetGovforCommand
    head: AU14CamoM50Helmet

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORVehicleCommander
  name: Spawn Point GOVFOR Vehicle Commander
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORVehicleCommander
  - type: Sprite
    state: syn_spawn

- type: roleLoadout
  id: JobAU14JobGOVFORVehicleCommander
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: job
  parent: AU14JobVehicleCommanderBase
  id: AU14JobOPFORVehicleCommander
  roundSide: Opfor
  roundForce: OPFOR
  icon: "AU14JobIconOPFORTankCommander"
  spawnMenuRoleName: Vehicle Commander (OPFOR)
  supervisors: au14-job-supervisors-opfor
  startingGear: AU14GearOPFORVehicleCommander
  dummyStartingGear: AU14GearOPFORVehicleCommanderDummy
  accessGroups:
  - AU14OpforVehicleCrew
  useLoadoutOfJob: AU14JobGOVFORVehicleCommander

- type: startingGear
  id: AU14GearOPFORVehicleCommander
  equipment:
    id: AU14IDCardOPFORVehicleCommander
    ears: AU14HeadsetOpforCommand
    head: AU14CamoM50Helmet

- type: startingGear
  id: AU14GearOPFORVehicleCommanderDummy
  equipment:
    id: AU14IDCardOPFORVehicleCommander
    ears: AU14HeadsetOpforCommand
    head: AU14CamoM50Helmet

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointOPFORVehicleCommander
  name: Spawn Point OPFOR Vehicle Commander
  components:
  - type: SpawnPoint
    job_id: AU14JobOPFORVehicleCommander
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearGOVFORVehicleCommanderDummy
  equipment:
    id: AU14IDCardGOVFORVehicleCommander
    ears: AU14HeadsetGovforCommand
