- type: job
  abstract: true
  parent: AU14JobMilitaryBase
  id: AU14JobOfficerEngiBaseAbstract
  name: au14-job-name-govforengineering
  description: au14-job-description-govforengineering
  icon: "AU14JobIconGovEO"
  spawnMenuRoleName: au14-spawn-role-name-govfor-engineering-officer
  startingGear: AU14GearGOVFOROfficerEngi
  dummyStartingGear: AU14GearGOVFOROfficerEngiDummy
  playTimeTracker: AU14JobGOVFOROfficerEngi
  requireAdminNotify: true
  canBeAntag: false
  displayWeight: 7
  accessGroups:
  - AU14GovforCommand
  - AU14GovforEngineer
  - aulegacygroupcommand

- type: job
  abstract: true
  parent: AU14JobOfficerEngiBaseAbstract
  id: AU14JobOfficerEngiBase
  roundRole: EngineeringOfficer
  roundProfiles:
  - AU14RoundJobProfileMilitaryBase
  roundComponents:
  - type: AU14CallsignRole
    suffix: OPS
    commandElement: true
  - type: ANPRCRadioUser # command staff are radio trained, backup manpack operators
  - type: Skills
    preset: AU14SkillPresetOfficerEngineer
  - type: RMCSpeechBubbleSpecificStyle
    speechStyleClass: commanderSpeech
  - type: JobPrefix
    prefix: au14-job-prefix-govforengineering
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/CMU14/Interface/au14govforjobicons.rsi
      state: govfor_eo
  roundForceComponents:
    OPFOR:
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/CMU14/Interface/au14opforjobicons.rsi
        state: eo
    # UPP:
    # - type: JobPrefix
    #   prefix: au14-job-prefix-govforengineeringUPP
    # WYPMC:
    # - type: JobPrefix
    #   prefix: au14-job-prefix-govforengineeringWYPMC
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000
  - !type:AgeRequirement
    requiredAge: 30
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxiety
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
    - NoEnglish
    - SlowRunner
    - Anemic
  ranks:
    RMCRankCivilian: []
  chevrons:
    RMCRankSecondLT:
      entity: AU14ChevronSecondLT
      requirements: []

- type: playTimeTracker
  id: AU14JobGOVFOROfficerEngi
  isHumanoid: true

# ├──[ Job Prototypes ]──────────────────────────────────────────────┤
- type: job
  parent: AU14JobOfficerEngiBase
  id: AU14JobGOVFOROfficerEngi
  hidden: false
  setPreference: true
  basePlaytimeTracker: true

- type: job
  parent: AU14JobOfficerEngiBase
  id: AU14JobOPFOROfficerEngi
  roundSide: Opfor
  roundForce: OPFOR
  icon: "AU14JobIconOPFOREO"
  spawnMenuRoleName: Engineering Officer (OPFOR)
  supervisors: au14-job-supervisors-opfor
  startingGear: AU14GearOpforOfficerEngi
  dummyStartingGear: AU14GearOpforOfficerEngiDummy
  accessGroups:
  - AU14OpforCommand
  - aulegacygroupcommand

# ├──[ Starting Gear ]───────────────────────────────────────────────┤
  useLoadoutOfJob: AU14JobGOVFOROfficerEngi

- type: startingGear
  id: AU14GearGOVFOROfficerEngi
  equipment:
    id: AU14IDCardGOVFOROfficerEngi
    ears: AU14HeadsetGovforCommand
    outerClothing: RMCHazardVest
    shoes: CMBootsBlackFilled
    head: RMCHardhatWhite
    jumpsuit: CMJumpsuitOrdnanceTech
    back: CMSatchelMarine
    pocket1: AU14StampEO

- type: startingGear
  id: AU14GearGOVFOROfficerEngiDummy
  equipment:
    id: AU14IDCardGOVFOROfficerEngi
    ears: AU14HeadsetGovforCommand
    outerClothing: RMCHazardVest
    shoes: CMBootsBlackFilled
    head: RMCHardhatWhite
    jumpsuit: CMJumpsuitOrdnanceTech
    back: CMSatchelMarine

- type: roleLoadout
  id: JobAU14JobGOVFOROfficerEngi
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: startingGear
  id: AU14GearOpforOfficerEngi
  equipment:
    id: AU14IDCardOPFOROfficerEngi
    outerClothing: RMCHazardVest
    shoes: CMBootsBlackFilled
    head: RMCHardhatWhite
    jumpsuit: CMJumpsuitOrdnanceTech
    ears: AU14HeadsetOpforCommand
    back: CMSatchelMarine
    pocket1: AU14StampEO

- type: startingGear
  id: AU14GearOpforOfficerEngiDummy
  equipment:
    id: AU14IDCardOPFOROfficerEngi
    outerClothing: RMCHazardVest
    shoes: CMBootsBlackFilled
    head: RMCHardhatWhite
    jumpsuit: CMJumpsuitOrdnanceTech
    ears: AU14HeadsetOpforCommand
    back: CMSatchelMarine
    pocket1: AU14StampEO

# ├──[ Spawnpoints ]─────────────────────────────────────────────────┤
- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFOROfficerEngi
  name: Spawn Point GOVFOR Engineering Officer
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFOROfficerEngi
  - type: Sprite
    state: syn_spawn

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointOpforOfficerEngi
  name: Spawn Point OPFOR Engineering Officer
  components:
  - type: SpawnPoint
    job_id: AU14JobOPFOROfficerEngi
  - type: Sprite
    state: syn_spawn

# ├──[ Factions ]────────────────────────────────────────────────────┤
- type: job
  parent: AU14JobOfficerEngiBase
  id: AU14JobGOVFOROfficerEngiUPP
  roundForce: UPP
  requirements: []
  name: Engineering Officer
  spawnMenuRoleName: Engineering Officer (UPP)
  ranks:
    UPP_Captain:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFOROfficerEngi
      time: 360000
    UPP_SeniorLieutenant: []

- type: job
  parent: AU14JobOfficerEngiBase
  id: AU14JobGOVFOROfficerEngiWYPMC
  roundForce: WYPMC
  requirements: []
  name: PMC Chief Engineer
  spawnMenuRoleName: Engineering Officer (WYPMC)
  ranks:
    AU14RankWeYuCommander: []
