using System.Linq;
using System.Numerics;
using Content.Shared.CMU14.Radio;
using Content.Shared.Radio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.CMU14.Radio;

[GenerateTypedNameReferences]
public sealed partial class ANPRCRadioWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototype = default!;

    public event Action<int>? OnSelectSlot;
    public event Action? OnTogglePower;
    public event Action? OnToggleMonitor;
    public event Action<RadioMode>? OnSetMode;
    public event Action<bool>? OnSetScan;
    public event Action<RadioTxPower>? OnSetTxPower;
    public event Action<int>? OnSetSquelch;
    public event Action<string>? OnSetCallsign;
    public event Action<string>? OnAddSlot;
    public event Action<int>? OnDeleteSlot;
    public event Action<int, ProtoId<RadioChannelPrototype>>? OnSetSlotChannel;
    public event Action<int>? OnClearSlot;
    public event Action? OnCryptoZeroize;
    public event Action? OnCryptoDestroy;
    public event Action? OnCryptoRecrypto;
    public event Action? OnRadioCheck;
    public event Action? OnOpenDirectory;
    public event Action<int, string>? OnManualFrequency;
    public event Action<bool>? OnSetSweep;
    public event Action<int, RadioFrequency>? OnTuneContact;
    public event Action<bool>? OnPrintLog;

    private static readonly Color LcdBright = Color.FromHex("#3FCF8E");
    private static readonly Color LcdMid = Color.FromHex("#2D9E60");
    private static readonly Color LcdDim = Color.FromHex("#4A7A55");
    private static readonly Color LcdOff = Color.FromHex("#1E4A2E");
    private static readonly Color LcdWarning = Color.FromHex("#D6B85A");

    private static readonly Color TextBright = Color.FromHex("#C8D2E8");
    private static readonly Color TextDim = Color.FromHex("#687A9A");
    private static readonly Color TextGood = Color.FromHex("#78D69B");
    private static readonly Color TextWarn = Color.FromHex("#D6B85A");
    private static readonly Color TextBad = Color.FromHex("#D65A5A");
    private static readonly Color TextLog = Color.FromHex("#3FCF8E");

    private ANPRCRadioState? _lastState;

    // the BUI rebuilds this window every open, remember the operator's size for the
    // session so they aren't re-dragging it to fit their screen each time
    private static Vector2? _rememberedSize;

    private bool _recryptoArmed;
    private DateTime _recryptoArmedUntil;

    private int _entryTargetSlot = -1;

    private enum EntryTab { Freq, Net }
    private EntryTab _activeEntryTab = EntryTab.Freq;

    private string? _netLogChannelFilter;
    private string _netLogSearchFilter = string.Empty;
    private readonly List<string> _netLogChannels = new();

    private readonly List<string> _callsignPresets = new();

    public ANPRCRadioWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Title = Loc.GetString("anprc-window-title");

        PowerButton.OnPressed += _ => OnTogglePower?.Invoke();

        ModeButton.OnPressed += _ =>
        {
            if (_lastState == null) return;
            var next = _lastState.Mode switch
            {
                RadioMode.FrequencyHopping => RadioMode.SingleChannel,
                RadioMode.SingleChannel => RadioMode.CipherText,
                RadioMode.CipherText => RadioMode.PlainText,
                RadioMode.PlainText => RadioMode.FrequencyHopping,
                _ => RadioMode.FrequencyHopping,
            };
            OnSetMode?.Invoke(next);
        };

        MonitorButton.OnPressed += _ => OnToggleMonitor?.Invoke();

        ScanButton.OnPressed += _ =>
        {
            if (_lastState == null) return;
            OnSetScan?.Invoke(!_lastState.ScanEnabled);
        };

        SquelchButton.OnPressed += _ =>
        {
            if (_lastState == null) return;
            var next = _lastState.SquelchLevel >= ANPRCRadioComponent.MaxSquelchLevel ? 0 : _lastState.SquelchLevel + 1;
            OnSetSquelch?.Invoke(next);
        };

        TxPowerButton.OnPressed += _ =>
        {
            if (_lastState == null) return;
            var next = _lastState.TxPower switch
            {
                RadioTxPower.Low => RadioTxPower.Medium,
                RadioTxPower.Medium => RadioTxPower.High,
                _ => RadioTxPower.Low,
            };
            OnSetTxPower?.Invoke(next);
        };

        CallsignSetButton.OnPressed += _ =>
        {
            var text = CallsignLineEdit.Text.Trim().ToUpperInvariant();
            if (text.Length > ANPRCRadioComponent.MaxCallsignLength)
                text = text[..ANPRCRadioComponent.MaxCallsignLength];
            OnSetCallsign?.Invoke(text);
            CallsignLineEdit.Text = string.Empty;
        };

        // picking a preset just fills the line edit, SET still confirms and the field
        // stays free-text for custom callsigns
        CallsignPresetButton.OnItemSelected += args =>
        {
            CallsignPresetButton.SelectId(0);

            if (args.Id <= 0 || args.Id > _callsignPresets.Count)
                return;

            CallsignLineEdit.Text = _callsignPresets[args.Id - 1];
        };

        AddSlotButton.OnPressed += _ =>
        {
            AddSlotPanel.Visible = true;
            AddSlotLabelEdit.Text = string.Empty;
            AddSlotLabelEdit.GrabKeyboardFocus();
        };

        AddSlotConfirmButton.OnPressed += _ =>
        {
            var label = AddSlotLabelEdit.Text.Trim().ToUpperInvariant();
            if (label.Length > ANPRCRadioComponent.MaxLabelLength)
                label = label[..ANPRCRadioComponent.MaxLabelLength];
            if (string.IsNullOrWhiteSpace(label)) label = "СЕТЬ";
            OnAddSlot?.Invoke(label);
            AddSlotPanel.Visible = false;
            AddSlotLabelEdit.Text = string.Empty;
        };

        AddSlotCancelButton.OnPressed += _ =>
        {
            AddSlotPanel.Visible = false;
            AddSlotLabelEdit.Text = string.Empty;
        };

        EntryTabFreqButton.OnPressed += _ => ShowEntryTab(EntryTab.Freq);
        EntryTabNetButton.OnPressed += _ => ShowEntryTab(EntryTab.Net);

        EntryTabClearButton.OnPressed += _ =>
        {
            if (_entryTargetSlot < 0) return;
            OnClearSlot?.Invoke(_entryTargetSlot);
            CloseSlotEntryPanel();
        };

        EntryFreqConfirmButton.OnPressed += _ =>
        {
            if (_entryTargetSlot < 0) return;
            var text = EntryFreqLineEdit.Text.Trim();
            if (!string.IsNullOrEmpty(text))
                OnManualFrequency?.Invoke(_entryTargetSlot, text);
            CloseSlotEntryPanel();
        };

        SlotEntryCloseButton.OnPressed += _ => CloseSlotEntryPanel();

        ZeroizeButton.OnPressed += _ => OnCryptoZeroize?.Invoke();
        DestroyButton.OnPressed += _ => OnCryptoDestroy?.Invoke();

        // superseding every fill card in the faction is not a one-misclick action:
        // first press arms the button, a second press within the window confirms
        RecryptoButton.Text = Loc.GetString("anprc-recrypto-button");
        RecryptoButton.OnPressed += _ =>
        {
            if (_recryptoArmed && DateTime.UtcNow <= _recryptoArmedUntil)
            {
                DisarmRecrypto();
                OnCryptoRecrypto?.Invoke();
                return;
            }

            _recryptoArmed = true;
            _recryptoArmedUntil = DateTime.UtcNow + TimeSpan.FromSeconds(4);
            RecryptoButton.Text = Loc.GetString("anprc-recrypto-button-confirm");
            RecryptoButton.ModulateSelfOverride = TextBad;
        };

        RadioCheckButton.OnPressed += _ => OnRadioCheck?.Invoke();
        DirectoryButton.OnPressed += _ => OnOpenDirectory?.Invoke();

        SweepButton.OnPressed += _ =>
        {
            if (_lastState == null) return;
            OnSetSweep?.Invoke(!_lastState.SweepEnabled);
        };

        PrintLogButton.OnPressed += _ => OnPrintLog?.Invoke(false);
        PrintInterceptsButton.OnPressed += _ => OnPrintLog?.Invoke(true);

        NetLogChannelFilter.OnItemSelected += args =>
        {
            NetLogChannelFilter.SelectId(args.Id);
            _netLogChannelFilter = args.Id == 0 ? null : _netLogChannels[args.Id - 1];
            if (_lastState != null)
                RebuildNetLog(_lastState);
        };

        NetLogSearchEdit.OnTextChanged += args =>
        {
            _netLogSearchFilter = args.Text.Trim();
            if (_lastState != null)
                RebuildNetLog(_lastState);
        };

        NetLogFilterClearButton.OnPressed += _ =>
        {
            _netLogChannelFilter = null;
            _netLogSearchFilter = string.Empty;
            NetLogSearchEdit.Text = string.Empty;

            // the dropdown is empty until the first state arrives, and selecting an
            // id it does not carry throws rather than no-opping
            if (NetLogChannelFilter.ItemCount > 0)
                NetLogChannelFilter.SelectId(0);
            if (_lastState != null)
                RebuildNetLog(_lastState);
        };

        AddSlotPanel.Visible = false;
        SlotEntryPanel.Visible = false;
    }

    // clamp to the viewport so the panel never opens taller than a small screen, and
    // restore the size the operator last dragged it to
    protected override void EnteredTree()
    {
        base.EnteredTree();

        var target = _rememberedSize ?? SetSize;

        if (Root is { } root)
            target = Vector2.Min(target, root.Size * 0.95f);

        SetSize = Vector2.Max(target, new Vector2(MinWidth, MinHeight));
    }

    protected override void Resized()
    {
        base.Resized();

        if (IsInsideTree)
            _rememberedSize = Size;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_recryptoArmed && DateTime.UtcNow > _recryptoArmedUntil)
            DisarmRecrypto();
    }

    private void DisarmRecrypto()
    {
        _recryptoArmed = false;
        RecryptoButton.Text = Loc.GetString("anprc-recrypto-button");
        RecryptoButton.ModulateSelfOverride = null;
    }

    public void UpdateState(ANPRCRadioState state)
    {
        _lastState = state;

        var hasActiveDynFreq = state.FrequencyOverrides.TryGetValue(state.ActiveSlot, out var activeDynFreq);
        RadioChannelPrototype? activeProto = null;
        var hasActiveChannel = !hasActiveDynFreq &&
                               state.Presets.TryGetValue(state.ActiveSlot, out var activeChannel) &&
                               _prototype.TryIndex(activeChannel, out activeProto);

        var hasAnyActive = hasActiveChannel || hasActiveDynFreq;
        // planted retrans stations are fully operable from the panel without being worn
        var deployed = state.IsEquipped || state.Planted;
        var online = state.Enabled && deployed;
        var ready = online && hasAnyActive && state.ActiveSlot >= 0;

<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
        HeaderPowerLabel.Text = state.Enabled ? "ПИТАНИЕ: ВКЛ" : "ПИТАНИЕ: ВЫКЛ";
=======
        HeaderPowerLabel.Text = Loc.GetString(state.Enabled
            ? "anprc-ui-header-power-on"
            : "anprc-ui-header-power-off");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
        HeaderPowerLabel.FontColorOverride = state.Enabled ? TextGood : TextBad;

        if (state.Planted)
        {
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            HeaderLinkLabel.Text = "СВЯЗЬ: РЕТРАНСЛЯТОР";
=======
            HeaderLinkLabel.Text = Loc.GetString("anprc-ui-header-link-retrans");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
            HeaderLinkLabel.FontColorOverride = state.Enabled ? TextGood : TextDim;
        }
        else if (!state.IsEquipped)
        {
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            HeaderLinkLabel.Text = "СВЯЗЬ: НЕ НАДЕТА";
=======
            HeaderLinkLabel.Text = Loc.GetString("anprc-ui-header-link-not-worn");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
            HeaderLinkLabel.FontColorOverride = TextWarn;
        }
        else if (!state.Enabled)
        {
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            HeaderLinkLabel.Text = "СВЯЗЬ: ОЖИДАНИЕ";
=======
            HeaderLinkLabel.Text = Loc.GetString("anprc-ui-header-link-standby");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
            HeaderLinkLabel.FontColorOverride = TextDim;
        }
        else
        {
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            HeaderLinkLabel.Text = hasAnyActive ? "СВЯЗЬ: ГОТОВА" : "СВЯЗЬ: НЕТ СЕТИ";
            HeaderLinkLabel.FontColorOverride = hasAnyActive ? TextGood : TextWarn;
        }

        LcdModeLabel.Text = $"РЕЖИМ: {ModeShort(state.Mode)}";
=======
            HeaderLinkLabel.Text = Loc.GetString(hasAnyActive
                ? "anprc-ui-header-link-ready"
                : "anprc-ui-header-link-no-net");
            HeaderLinkLabel.FontColorOverride = hasAnyActive ? TextGood : TextWarn;
        }

        LcdModeLabel.Text = Loc.GetString("anprc-ui-lcd-mode", ("mode", ModeShort(state.Mode)));
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
        LcdModeLabel.FontColorOverride = online ? LcdDim : LcdOff;
        CryptoLabel.FontColorOverride = online ? LcdDim : LcdOff;

        if (hasActiveDynFreq)
        {
            var fStr = FormatFreq(activeDynFreq);
            FrequencyLabel.Text = fStr;
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            ChannelNameLabel.Text = "ПРЯМАЯ ЧАСТОТА";
            ChannelIdLabel.Text = $"ЧАСТОТА: {fStr}";
            BandLabel.Text = $"ДИАПАЗОН: {BandName(activeDynFreq)}";
            WaveformLabel.Text = "СИГНАЛ: ПРЯМОЙ";
=======
            ChannelNameLabel.Text = Loc.GetString("anprc-ui-direct-frequency");
            ChannelIdLabel.Text = Loc.GetString("anprc-ui-frequency", ("frequency", fStr));
            BandLabel.Text = Loc.GetString("anprc-ui-band", ("band", BandName(activeDynFreq)));
            WaveformLabel.Text = Loc.GetString("anprc-ui-waveform", ("waveform", "LOS"));
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs

            FrequencyLabel.FontColorOverride = ready ? LcdBright : LcdOff;
            ChannelNameLabel.FontColorOverride = ready ? LcdMid : LcdOff;
            ChannelIdLabel.FontColorOverride = online ? LcdDim : LcdOff;
            BandLabel.FontColorOverride = online ? LcdDim : LcdOff;
            WaveformLabel.FontColorOverride = online ? LcdDim : LcdOff;
        }
        else if (activeProto != null)
        {
            FrequencyLabel.Text = FormatFreq(PlanFreq(activeProto));
            ChannelNameLabel.Text = activeProto.LocalizedName.ToUpperInvariant();
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            ChannelIdLabel.Text = $"КАНАЛ: {activeProto.ID}";
            BandLabel.Text = $"ДИАПАЗОН: {BandName(PlanFreq(activeProto))}";
            WaveformLabel.Text = $"СИГНАЛ: {(activeProto.LongRange ? "СПУТНИК" : "ПРЯМОЙ")}";
=======
            ChannelIdLabel.Text = Loc.GetString("anprc-ui-channel", ("channel", activeProto.ID));
            BandLabel.Text = Loc.GetString("anprc-ui-band", ("band", BandName(PlanFreq(activeProto))));
            WaveformLabel.Text = Loc.GetString("anprc-ui-waveform", ("waveform", activeProto.LongRange ? "SAT" : "LOS"));
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs

            FrequencyLabel.FontColorOverride = ready ? LcdBright : LcdOff;
            ChannelNameLabel.FontColorOverride = ready ? LcdMid : LcdOff;
            ChannelIdLabel.FontColorOverride = online ? LcdDim : LcdOff;
            BandLabel.FontColorOverride = online ? LcdDim : LcdOff;
            WaveformLabel.FontColorOverride = online ? LcdDim : LcdOff;
        }
        else
        {
            FrequencyLabel.Text = "-- . ---";
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            ChannelNameLabel.Text = state.ActiveSlot < 0 ? "НЕТ АКТИВНОЙ ЯЧЕЙКИ" : "ЯЧЕЙКА ПУСТА";
            ChannelIdLabel.Text = "КАНАЛ: ---";
            BandLabel.Text = "ДИАПАЗОН: ---";
            WaveformLabel.Text = "СИГНАЛ: ---";
=======
            ChannelNameLabel.Text = Loc.GetString(state.ActiveSlot < 0
                ? "anprc-ui-no-slot-active"
                : "anprc-ui-slot-empty");
            ChannelIdLabel.Text = Loc.GetString("anprc-ui-channel-placeholder");
            BandLabel.Text = Loc.GetString("anprc-ui-band-placeholder");
            WaveformLabel.Text = Loc.GetString("anprc-ui-waveform-placeholder");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs

            FrequencyLabel.FontColorOverride = LcdOff;
            ChannelNameLabel.FontColorOverride = LcdOff;
            ChannelIdLabel.FontColorOverride = LcdOff;
            BandLabel.FontColorOverride = LcdOff;
            WaveformLabel.FontColorOverride = LcdOff;
        }

        if (!online)
        {
            TxIndicator.FontColorOverride = LcdOff;
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            TxLabel.Text = "ВЫКЛ";
=======
            TxLabel.Text = Loc.GetString("anprc-ui-tx-off");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
            TxLabel.FontColorOverride = LcdOff;
        }
        else if (!hasAnyActive)
        {
            TxIndicator.FontColorOverride = LcdWarning;
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            TxLabel.Text = "НЕТ СЕТИ";
=======
            TxLabel.Text = Loc.GetString("anprc-ui-tx-no-net");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
            TxLabel.FontColorOverride = LcdWarning;
        }
        else
        {
            TxIndicator.FontColorOverride = LcdBright;
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            TxLabel.Text = state.MonitorEnabled ? "МОНИТОР" : "ОЖИДАНИЕ";
=======
            TxLabel.Text = Loc.GetString(state.MonitorEnabled
                ? "anprc-ui-tx-monitor"
                : "anprc-ui-tx-standby");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
            TxLabel.FontColorOverride = state.MonitorEnabled ? LcdBright : LcdDim;
        }

        if (!deployed)
        {
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            BitStatusLabel.Text = "ТЕСТ: НЕ НАДЕТА";
=======
            BitStatusLabel.Text = Loc.GetString("anprc-ui-bit-not-seated");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
            BitStatusLabel.FontColorOverride = LcdWarning;
        }
        else if (!state.Enabled)
        {
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            BitStatusLabel.Text = "ТЕСТ: НЕТ СВЯЗИ";
=======
            BitStatusLabel.Text = Loc.GetString("anprc-ui-bit-offline");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
            BitStatusLabel.FontColorOverride = LcdOff;
        }
        else if (!hasAnyActive)
        {
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            BitStatusLabel.Text = "ТЕСТ: НЕТ СЕТИ";
=======
            BitStatusLabel.Text = Loc.GetString("anprc-ui-bit-no-net");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
            BitStatusLabel.FontColorOverride = LcdWarning;
        }
        else
        {
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            BitStatusLabel.Text = "ТЕСТ: НОРМА";
=======
            BitStatusLabel.Text = Loc.GetString("anprc-ui-bit-pass");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
            BitStatusLabel.FontColorOverride = LcdBright;
        }

        SignalBarsLabel.Text = Bars(ready ? 8 : 0, 8);
        SignalBarsLabel.FontColorOverride = ready ? LcdBright : LcdOff;

        var batteryFilled = state.HasBattery ? (int)Math.Round(state.BatteryFraction * 6) : 0;
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
        BatteryBarsLabel.Text = state.HasBattery ? Bars(batteryFilled, 6) : "НЕТ БАТАРЕИ";
=======
        BatteryBarsLabel.Text = state.HasBattery ? Bars(batteryFilled, 6) : Loc.GetString("anprc-ui-no-cell");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
        BatteryBarsLabel.FontColorOverride = !state.HasBattery ? TextBad
                                            : state.BatteryFraction <= 0.2f ? LcdWarning
                                            : LcdDim;

<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
        AntennaLabel.Text = $"АНТ: {state.AntennaLabel}";
=======
        AntennaLabel.Text = Loc.GetString("anprc-ui-antenna", ("antenna", state.AntennaLabel));
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
        AntennaLabel.FontColorOverride = online ? LcdDim : LcdOff;

        if (!deployed)
        {
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            FaultLabel.Text = "ОШИБКА: НЕ НАДЕТА";
=======
            FaultLabel.Text = Loc.GetString("anprc-ui-fault-not-worn");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
            FaultLabel.FontColorOverride = TextWarn;
        }
        else if (!state.Enabled)
        {
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            FaultLabel.Text = "ОШИБКА: ВЫКЛ";
=======
            FaultLabel.Text = Loc.GetString("anprc-ui-fault-off");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
            FaultLabel.FontColorOverride = TextDim;
        }
        else if (!hasAnyActive)
        {
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            FaultLabel.Text = "ОШИБКА: НЕТ СЕТИ";
=======
            FaultLabel.Text = Loc.GetString("anprc-ui-fault-no-net");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
            FaultLabel.FontColorOverride = TextWarn;
        }
        else
        {
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            FaultLabel.Text = "ОШИБКА: НЕТ";
=======
            FaultLabel.Text = Loc.GetString("anprc-ui-fault-none");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
            FaultLabel.FontColorOverride = TextGood;
        }

        // callsign: manual station override > wearer's assigned callsign (AUTO)
        if (!string.IsNullOrEmpty(state.Callsign))
        {
            CallsignDisplayLabel.Text = state.Callsign;
            CallsignDisplayLabel.FontColorOverride = TextGood;
        }
        else if (!string.IsNullOrEmpty(state.WearerCallsign))
        {
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            CallsignDisplayLabel.Text = $"{state.WearerCallsign} (АВТО)";
=======
            CallsignDisplayLabel.Text = Loc.GetString("anprc-ui-callsign-auto", ("callsign", state.WearerCallsign));
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
            CallsignDisplayLabel.FontColorOverride = TextGood;
        }
        else
        {
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            CallsignDisplayLabel.Text = "НЕИЗВЕСТНАЯ СТАНЦИЯ";
=======
            CallsignDisplayLabel.Text = Loc.GetString("anprc-unknown-station");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
            CallsignDisplayLabel.FontColorOverride = TextDim;
        }

        RebuildCallsignPresets(state);
        RebuildSlotList(state);

        var slotCount = state.SlotLabels.Count;
        PresetSummaryLabel.Text = $"{slotCount}/{ANPRCRadioComponent.MaxSlots}";
        PresetSummaryLabel.FontColorOverride = slotCount > 0 ? TextDim : TextWarn;
        AddSlotButton.Disabled = slotCount >= ANPRCRadioComponent.MaxSlots || !online;

<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
        ModeButton.Text = $"РЕЖИМ {ModeShort(state.Mode)}";
        MonitorButton.Text = state.MonitorEnabled ? "МОНИТОР ВКЛ" : "МОНИТОР ВЫКЛ";
        ScanButton.Text = state.ScanEnabled ? "СКАН ВКЛ" : "СКАН ВЫКЛ";
        SquelchButton.Text = $"ШУМ {state.SquelchLevel}";
        TxPowerButton.Text = $"ПЕРЕДАЧА {state.TxPower.Short()}";
=======
        ModeButton.Text = Loc.GetString("anprc-ui-mode-button", ("mode", ModeShort(state.Mode)));
        MonitorButton.Text = Loc.GetString(state.MonitorEnabled ? "anprc-ui-monitor-on" : "anprc-ui-monitor-off");
        ScanButton.Text = Loc.GetString(state.ScanEnabled ? "anprc-ui-scan-on" : "anprc-ui-scan-off");
        SquelchButton.Text = Loc.GetString("anprc-ui-squelch-button", ("level", state.SquelchLevel));
        TxPowerButton.Text = Loc.GetString("anprc-ui-tx-power-button", ("power", state.TxPower.Short()));
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs

        ModeButton.Disabled = !online;
        MonitorButton.Disabled = !online;
        ScanButton.Disabled = !online;
        SquelchButton.Disabled = !online;
        TxPowerButton.Disabled = !online;
        MonitorButton.Pressed = state.MonitorEnabled && online;
        ScanButton.Pressed = state.ScanEnabled && online;

<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
        RoleValueLabel.Text = state.Planted ? "СТАНЦИЯ-РЕТРАНСЛЯТОР" : "РЕТРАНСЛЯТОР РТО";

        RelayValueLabel.Text = online && hasAnyActive ? "ОПОРА" : "ОЖИДАНИЕ";
        RelayValueLabel.FontColorOverride = online && hasAnyActive ? TextGood : TextDim;

        DiagnosticLineA.Text = online && hasAnyActive ? "ОПОРА: АКТИВНА"
                                          : online ? "ОПОРА: ОЖИДАНИЕ"
                                                                   : "ОПОРА: НЕТ СВЯЗИ";
        DiagnosticLineA.FontColorOverride = online && hasAnyActive ? TextGood : TextDim;
        DiagnosticLineB.Text = online && hasAnyActive ? "ОБХОД: ГОТОВ" : "ОБХОД: НЕТ";
=======
        RoleValueLabel.Text = Loc.GetString(state.Planted
            ? "anprc-ui-role-retrans-station"
            : "anprc-ui-role-rto-relay");

        RelayValueLabel.Text = Loc.GetString(online && hasAnyActive
            ? "anprc-ui-relay-anchor"
            : "anprc-ui-relay-standby");
        RelayValueLabel.FontColorOverride = online && hasAnyActive ? TextGood : TextDim;

        DiagnosticLineA.Text = Loc.GetString(online && hasAnyActive
            ? "anprc-ui-anchor-active"
            : online
                ? "anprc-ui-anchor-standby"
                : "anprc-ui-anchor-offline");
        DiagnosticLineA.FontColorOverride = online && hasAnyActive ? TextGood : TextDim;
        DiagnosticLineB.Text = Loc.GetString(online && hasAnyActive
            ? "anprc-ui-bypass-armed"
            : "anprc-ui-bypass-no");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
        DiagnosticLineB.FontColorOverride = online && hasAnyActive ? TextGood : TextDim;

        RoleValueLabel.FontColorOverride = online ? TextBright : TextDim;

        var hasFill = !string.IsNullOrEmpty(state.CryptoFaction);
        var secured = hasFill && !state.CryptoStale;

<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
        CryptoStatusLabel.Text = secured ? $"ЗАЩИЩЕНО ({state.CryptoDesignation})"
                                             : hasFill ? $"УСТАРЕЛО ({state.CryptoDesignation})"
                                                        : "НЕ ЗАЩИЩЕНО";
=======
        CryptoStatusLabel.Text = secured
            ? Loc.GetString("anprc-ui-secured", ("designation", state.CryptoDesignation))
            : hasFill
                ? Loc.GetString("anprc-ui-stale", ("designation", state.CryptoDesignation))
                : Loc.GetString("anprc-ui-unsecured");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
        CryptoStatusLabel.FontColorOverride = secured ? TextGood : hasFill ? TextWarn : TextBad;

        CryptoFillLabel.Text = hasFill
            ? state.CryptoStale
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
                ? $"КЛЮЧ: {state.CryptoDesignation} ({state.CryptoFaction.ToUpperInvariant()}) — УСТАРЕЛ, НУЖНА СМЕНА"
                : $"КЛЮЧ: {state.CryptoDesignation} ({state.CryptoFaction.ToUpperInvariant()})"
            : "КЛЮЧ: НЕТ — вставьте карту";
=======
                ? Loc.GetString("anprc-ui-fill-stale",
                    ("designation", state.CryptoDesignation),
                    ("faction", state.CryptoFaction.ToUpperInvariant()))
                : Loc.GetString("anprc-ui-fill-loaded",
                    ("designation", state.CryptoDesignation),
                    ("faction", state.CryptoFaction.ToUpperInvariant()))
            : Loc.GetString("anprc-ui-fill-none");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
        CryptoFillLabel.FontColorOverride = secured ? TextGood : hasFill ? TextWarn : TextDim;

        ZeroizeButton.Disabled = !online || !hasFill;
        DestroyButton.Disabled = !online || !hasFill;
        RecryptoButton.Disabled = !online || !secured;

        if (RecryptoButton.Disabled && _recryptoArmed)
            DisarmRecrypto();

        RadioCheckButton.Disabled = !ready;

        RebuildSweep(state);
        RebuildNetLog(state);

        PrintLogButton.Disabled = !online || state.NetLog.Count == 0;
        PrintInterceptsButton.Disabled = !online || state.NetLog.All(e => !e.Intercepted);

        PowerButton.Text = state.Enabled
            ? Loc.GetString("anprc-power-off-button")
            : Loc.GetString("anprc-power-on-button");

        var net = hasActiveDynFreq
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            ? $"ПРЯМАЯ {FormatFreq(activeDynFreq)}"
            : activeProto?.LocalizedName ?? "Нет сети";

        StatusLabel.Text =
            $"{(state.Planted ? "РАЗВЁРНУТА" : state.IsEquipped ? "НАДЕТА" : "НЕ НАДЕТА")}" +
            $" · {(state.Enabled ? "ВКЛ" : "ВЫКЛ")}" +
            $" · {net}";
=======
            ? Loc.GetString("anprc-ui-footer-direct", ("frequency", FormatFreq(activeDynFreq)))
            : activeProto?.LocalizedName ?? Loc.GetString("anprc-ui-footer-no-net");
        var deployment = Loc.GetString(state.Planted
            ? "anprc-ui-footer-planted"
            : state.IsEquipped
                ? "anprc-ui-footer-equipped"
                : "anprc-ui-footer-unequipped");
        var power = Loc.GetString(state.Enabled ? "anprc-status-on" : "anprc-status-off");

        StatusLabel.Text = Loc.GetString("anprc-ui-footer-status",
            ("deployment", deployment),
            ("power", power),
            ("net", net));
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
    }

    // only rebuild the dropdown when the pool actually changes, otherwise the periodic
    // state updates yank an open dropdown shut
    private void RebuildCallsignPresets(ANPRCRadioState state)
    {
        if (state.CallsignPresets.SequenceEqual(_callsignPresets))
        {
            CallsignPresetButton.Visible = _callsignPresets.Count > 0;
            return;
        }

        _callsignPresets.Clear();
        _callsignPresets.AddRange(state.CallsignPresets);

        CallsignPresetButton.Clear();
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
        CallsignPresetButton.AddItem("ШАБЛОНЫ", 0);
=======
        CallsignPresetButton.AddItem(Loc.GetString("anprc-ui-callsign-presets"), 0);
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
        for (var i = 0; i < _callsignPresets.Count; i++)
        {
            CallsignPresetButton.AddItem(_callsignPresets[i], i + 1);
        }

        CallsignPresetButton.SelectId(0);
        CallsignPresetButton.Visible = _callsignPresets.Count > 0;
    }

    private void RebuildSlotList(ANPRCRadioState state)
    {
        SlotListContainer.RemoveAllChildren();

        // planted retrans stations stay tunable from the panel, matching the
        // deployed logic above, so nobody has to pack the bag up to switch nets
        var online = state.Enabled && (state.IsEquipped || state.Planted);
        var sortedSlots = state.SlotLabels.Keys.OrderBy(k => k).ToList();

        foreach (var slot in sortedSlots)
        {
            var label = state.SlotLabels[slot];
            var isActive = slot == state.ActiveSlot;

            string freqText;
            if (state.FrequencyOverrides.TryGetValue(slot, out var dynFreq))
            {
                // a raw frequency the sweep fixed but could not name reads as an
                // unknown net rather than a plain direct entry, so an operator can
                // tell a tuned intercept from a number they punched in themselves
                var unknownNet = state.SweepContacts.Any(contact =>
                    contact.Resolved && !contact.Known && contact.Frequency == dynFreq);

<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
                freqText = unknownNet
                    ? $"{FormatFreq(dynFreq)} МГц · НЕИЗВЕСТНАЯ СЕТЬ"
                    : $"{FormatFreq(dynFreq)} МГц · ПРЯМАЯ";
            }
            else if (state.Presets.TryGetValue(slot, out var ch) && _prototype.TryIndex(ch, out var proto))
                freqText = $"{FormatFreq(PlanFreq(proto))} МГц · {proto.LocalizedName.ToUpperInvariant()}";
            else
                freqText = "--- ПУСТО ---";
=======
                freqText = Loc.GetString(unknownNet
                        ? "anprc-ui-slot-frequency-unknown"
                        : "anprc-ui-slot-frequency-direct",
                    ("frequency", FormatFreq(dynFreq)));
            }
            else if (state.Presets.TryGetValue(slot, out var ch) && _prototype.TryIndex(ch, out var proto))
            {
                freqText = Loc.GetString("anprc-ui-slot-frequency-channel",
                    ("frequency", FormatFreq(PlanFreq(proto))),
                    ("channel", proto.LocalizedName.ToUpperInvariant()));
            }
            else
            {
                freqText = Loc.GetString("anprc-ui-slot-frequency-empty");
            }
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs

            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 4 };

            var selectBtn = new Button
            {
                Text = $"[{label}]  {freqText}",
                HorizontalExpand = true,
                Pressed = isActive && online,
                Disabled = !online,
            };
            var capturedSlot = slot;
            selectBtn.OnPressed += _ => OnSelectSlot?.Invoke(capturedSlot);

            var tuneBtn = new Button
            {
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
                Text = "НАСТР.",
=======
                Text = Loc.GetString("anprc-ui-tune-button"),
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
                MinWidth = 52,
                Disabled = !online,
            };
            tuneBtn.OnPressed += _ => OpenSlotEntryPanel(capturedSlot, state);

            var delBtn = new Button
            {
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
                Text = "УДАЛ.",
=======
                Text = Loc.GetString("anprc-ui-delete-button"),
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
                MinWidth = 44,
            };
            delBtn.OnPressed += _ => OnDeleteSlot?.Invoke(capturedSlot);

            row.AddChild(selectBtn);
            row.AddChild(tuneBtn);
            row.AddChild(delBtn);
            SlotListContainer.AddChild(row);
        }
    }

    private void OpenSlotEntryPanel(int slot, ANPRCRadioState state)
    {
        _entryTargetSlot = slot;
        var label = state.SlotLabels.TryGetValue(slot, out var lbl) ? lbl : $"P{slot + 1}";
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
        SlotEntryHeaderLabel.Text = $"НАСТРОЙКА [{label}]:";
=======
        SlotEntryHeaderLabel.Text = Loc.GetString("anprc-ui-tune-slot-label", ("label", label));
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
        SlotEntryPanel.Visible = true;
        EntryFreqLineEdit.Text = string.Empty;
        ShowEntryTab(EntryTab.Freq);
        RebuildNetList(state);
    }

    private void CloseSlotEntryPanel()
    {
        SlotEntryPanel.Visible = false;
        _entryTargetSlot = -1;
        EntryFreqLineEdit.Text = string.Empty;
    }

    private void ShowEntryTab(EntryTab tab)
    {
        _activeEntryTab = tab;
        EntryFreqPanel.Visible = tab == EntryTab.Freq;
        EntryNetScroll.Visible = tab == EntryTab.Net;

        EntryTabFreqButton.Pressed = tab == EntryTab.Freq;
        EntryTabNetButton.Pressed = tab == EntryTab.Net;
    }

    // frequencies come from the round's signal plan carried in the BUI state,
    // the prototype value is only the fallback book number
    private RadioFrequency PlanFreq(RadioChannelPrototype proto)
    {
        return _lastState != null && _lastState.ChannelFrequencies.TryGetValue(proto.ID, out var freq)
            ? freq
            : proto.Frequency;
    }

    private void RebuildNetList(ANPRCRadioState state)
    {
        EntryNetList.RemoveAllChildren();

        var opFaction = state.OperatorFaction;

        foreach (var proto in _prototype.EnumeratePrototypes<RadioChannelPrototype>())
        {
            // skip sentinels and non-displayable channels
            if (proto.Frequency == RadioFrequency.Off)
                continue;

            // own-faction nets always list. a foreign net lists once the search
            // receiver has fixed it - the server only puts a foreign channel's
            // frequency in the state after it lands in DiscoveredFrequencies.
            // faction-less channels (colony, civilian) get tuned by raw frequency
            var ownNet = string.IsNullOrEmpty(opFaction) ||
                         string.Equals(proto.Faction, opFaction, StringComparison.OrdinalIgnoreCase);

            var discovered = !ownNet &&
                             !string.IsNullOrEmpty(proto.Faction) &&
                             state.ChannelFrequencies.ContainsKey(proto.ID);

            if (!ownNet && !discovered)
                continue;

            var capturedProto = proto;
            var btn = new Button
            {
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
                Text = discovered
                    ? $"{proto.LocalizedName.ToUpperInvariant()}  -  {FormatFreq(PlanFreq(proto))} МГц · ПОЙМАНА"
                    : $"{proto.LocalizedName.ToUpperInvariant()}  -  {FormatFreq(PlanFreq(proto))} МГц",
=======
                Text = Loc.GetString(discovered ? "anprc-ui-net-entry-intercept" : "anprc-ui-net-entry",
                    ("channel", proto.LocalizedName.ToUpperInvariant()),
                    ("frequency", FormatFreq(PlanFreq(proto)))),
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
                HorizontalExpand = true,
            };
            btn.OnPressed += _ =>
            {
                if (_entryTargetSlot < 0) return;
                OnSetSlotChannel?.Invoke(_entryTargetSlot, new ProtoId<RadioChannelPrototype>(capturedProto.ID));
                CloseSlotEntryPanel();
            };
            EntryNetList.AddChild(btn);
        }
    }

    private void RebuildSweep(ANPRCRadioState state)
    {
        var online = state.Enabled && (state.IsEquipped || state.Planted);

        SweepButton.Disabled = !online;
        SweepButton.Text = Loc.GetString(state.SweepEnabled ? "anprc-ui-stop-search" : "anprc-ui-start-search");
        SweepButton.Pressed = state.SweepEnabled && online;

        SweepStatusLabel.Text = Loc.GetString(!online
            ? "anprc-ui-search-offline"
            : state.SweepEnabled
                ? "anprc-ui-search-searching"
                : "anprc-ui-search-idle");
        SweepStatusLabel.FontColorOverride = state.SweepEnabled && online ? TextWarn : TextDim;

        if (state.SweepEnabled && online)
        {
            SweepBandLabel.Text = Loc.GetString("anprc-ui-search-head", ("frequency", FormatFreq(state.SweepPosition)));
            SweepBandLabel.FontColorOverride = LcdBright;
            SweepHintLabel.Text = Loc.GetString("anprc-ui-search-active-help");
            SweepHintLabel.FontColorOverride = TextWarn;
        }
        else
        {
            SweepBandLabel.Text = Loc.GetString("anprc-ui-band-idle");
            SweepBandLabel.FontColorOverride = LcdOff;
            SweepHintLabel.Text = Loc.GetString("anprc-ui-search-help");
            SweepHintLabel.FontColorOverride = TextDim;
        }

        SweepContactList.RemoveAllChildren();

        if (state.SweepContacts.Count == 0)
        {
            SweepContactList.AddChild(new Label
            {
                Text = Loc.GetString("anprc-ui-no-contacts"),
                FontColorOverride = TextDim,
            });

            return;
        }

        foreach (var contact in state.SweepContacts)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4,
            };

            if (contact.Resolved)
            {
                // an own net is dimmed and tagged: it is on the band, but it was never
                // work, and it should not read like a prize the operator won
                row.AddChild(new Label
                {
                    Text = Loc.GetString(contact.Known ? "anprc-ui-contact-own" : "anprc-ui-contact",
                        ("frequency", FormatFreq(contact.Frequency)),
                        ("channel", contact.ChannelName.ToUpperInvariant())),
                    FontColorOverride = contact.Known ? TextDim : TextGood,
                    HorizontalExpand = true,
                    ClipText = true,
                });

                // own nets are already sitting in the operator's presets, so only a
                // fixed foreign net gets the shortcut
                if (!contact.Known)
                {
                    var tuneBtn = new Button
                    {
                        Text = Loc.GetString("anprc-ui-tune-button"),
                        MinWidth = 52,
                        Disabled = state.ActiveSlot < 0 || !state.SlotLabels.ContainsKey(state.ActiveSlot),
                    };

                    var captured = contact.Frequency;
                    var slot = state.ActiveSlot;
                    tuneBtn.OnPressed += _ => OnTuneContact?.Invoke(slot, captured);

                    row.AddChild(tuneBtn);
                }
            }
            else
            {
                // partial fix: only the digits earned so far, the rest still masked
                row.AddChild(new Label
                {
                    Text = Loc.GetString("anprc-ui-contact-partial",
                        ("frequency", MaskDigits(FormatFreq(contact.Frequency), contact.Tier, contact.TierMax)),
                        ("tier", contact.Tier),
                        ("tierMax", contact.TierMax)),
                    FontColorOverride = TextWarn,
                    HorizontalExpand = true,
                    ClipText = true,
                });
            }

            SweepContactList.AddChild(row);
        }
    }

    private void RebuildNetLog(ANPRCRadioState state)
    {
        RebuildNetLogChannelFilter(state);

        NetLogContainer.RemoveAllChildren();

        var shown = 0;
        foreach (var entry in state.NetLog)
        {
            if (!NetLogEntryMatchesFilters(entry))
                continue;

            shown++;
            var ts = TimeSpan.FromSeconds(entry.Timestamp);
            var timeStr = $"{(int) ts.TotalMinutes:D2}:{ts.Seconds:D2}";

            var line = new Label
            {
                Text = Loc.GetString(entry.Intercepted ? "anprc-ui-log-entry-intercept" : "anprc-ui-log-entry",
                    ("time", timeStr),
                    ("sender", entry.SenderName),
                    ("channel", entry.ChannelDisplay)),
                FontColorOverride = entry.Intercepted ? TextWarn : TextLog,
                ClipText = true,
            };
            var msg = new Label
            {
                Text = $"  {entry.Message}",
                FontColorOverride = TextDim,
                ClipText = true,
            };
            NetLogContainer.AddChild(line);
            NetLogContainer.AddChild(msg);
        }

        var filtered = _netLogChannelFilter != null || _netLogSearchFilter.Length > 0;
        NetLogCountLabel.Text = filtered
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
            ? $"Записей: {shown}/{state.NetLog.Count}"
            : $"Записей: {state.NetLog.Count}";
=======
            ? Loc.GetString("anprc-ui-log-filtered-count", ("shown", shown), ("total", state.NetLog.Count))
            : Loc.GetString("anprc-ui-log-count", ("count", state.NetLog.Count));
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs

        if (filtered && shown == 0 && state.NetLog.Count > 0)
        {
            NetLogContainer.AddChild(new Label
            {
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
                Text = "НЕТ ЗАПИСЕЙ ПО ФИЛЬТРУ",
=======
                Text = Loc.GetString("anprc-ui-log-no-filter-match"),
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
                FontColorOverride = TextDim,
            });
        }
    }

    private bool NetLogEntryMatchesFilters(ANPRCNetLogEntry entry)
    {
        if (_netLogChannelFilter != null && entry.ChannelDisplay != _netLogChannelFilter)
            return false;

        return _netLogSearchFilter.Length == 0 ||
               entry.SenderName.Contains(_netLogSearchFilter, StringComparison.OrdinalIgnoreCase) ||
               entry.Message.Contains(_netLogSearchFilter, StringComparison.OrdinalIgnoreCase);
    }

    // same deal as the callsign dropdown, only rebuild when the set of nets in the log
    // changes so an open dropdown doesn't get yanked shut
    private void RebuildNetLogChannelFilter(ANPRCRadioState state)
    {
        var channels = state.NetLog
            .Select(e => e.ChannelDisplay)
            .Distinct()
            .OrderBy(c => c, StringComparer.OrdinalIgnoreCase)
            .ToList();

        // on a fresh window with an empty log both lists are empty, so the equality
        // check alone would skip the build and leave the dropdown with no ALL NETS
        // entry for the clear button to select back to
        if (NetLogChannelFilter.ItemCount > 0 && channels.SequenceEqual(_netLogChannels))
            return;

        _netLogChannels.Clear();
        _netLogChannels.AddRange(channels);

        NetLogChannelFilter.Clear();
<<<<<<< HEAD:Content.Client/_AU14/Radio/ANPRCRadioWindow.xaml.cs
        NetLogChannelFilter.AddItem("ВСЕ СЕТИ", 0);
=======
        NetLogChannelFilter.AddItem(Loc.GetString("anprc-ui-all-nets"), 0);
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Radio/ANPRCRadioWindow.xaml.cs
        for (var i = 0; i < _netLogChannels.Count; i++)
        {
            NetLogChannelFilter.AddItem(_netLogChannels[i], i + 1);
        }

        // reselect the previously chosen net, if it rotated out of the 50-entry log fall
        // back to ALL instead of filtering on a ghost
        var selectedIdx = _netLogChannelFilter == null ? -1 : _netLogChannels.IndexOf(_netLogChannelFilter);
        if (selectedIdx < 0)
        {
            _netLogChannelFilter = null;
            NetLogChannelFilter.SelectId(0);
        }
        else
        {
            NetLogChannelFilter.SelectId(selectedIdx + 1);
        }
    }

    private static string FormatFreq(RadioFrequency frequency)
        => frequency.FormatMegahertz();

    // The first three tiers reveal the MHz digits. The final tier reveals the exact
    // kHz carrier, so 259.237 progresses through 2XX.XXX / 25X.XXX / 259.XXX / 259.237.
    private static string MaskDigits(string formatted, int tier, int tierMax)
    {
        if (tier >= tierMax)
            return formatted;

        var earnedDigits = Math.Max(0, tier);
        var digitsSeen = 0;
        var masked = formatted.ToCharArray();

        for (var i = 0; i < masked.Length; i++)
        {
            if (!char.IsAsciiDigit(masked[i]))
                continue;

            digitsSeen++;
            if (digitsSeen > earnedDigits)
                masked[i] = 'X';
        }

        return new string(masked);
    }

    private static string BandName(RadioFrequency frequency)
    {
        var kilohertz = frequency.Kilohertz;
        return kilohertz < 3_000
            ? "LF"
            : kilohertz < 30_000
                ? "HF"
                : kilohertz < 88_000
                    ? "VHF"
                    : kilohertz < 300_000
                        ? "UHF"
                        : "SHF";
    }

    private static string Bars(int filled, int total)
    {
        filled = Math.Clamp(filled, 0, total);
        return new string('█', filled) + new string('░', total - filled);
    }

    private static string ModeShort(RadioMode m) => m switch
    {
        RadioMode.FrequencyHopping => "FH",
        RadioMode.SingleChannel => "SC",
        RadioMode.CipherText => "CT",
        RadioMode.PlainText => "PT",
        _ => "FH",
    };
}
