using Content.Shared.CMU14.Radio;
using Content.Shared.Radio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.Radio;

[GenerateTypedNameReferences]
public sealed partial class TunableFrequencyWindow : DefaultWindow
{
    public event Action<string>? OnSetFrequency;

    public TunableFrequencyWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("tunable-radio-window-title");

        ConfirmButton.OnPressed += _ =>
        {
            var text = FreqInput.Text.Trim();
            if (!string.IsNullOrEmpty(text))
                OnSetFrequency?.Invoke(text);
            FreqInput.Text = string.Empty;
        };

        FreqInput.OnTextEntered += _ =>
        {
            var text = FreqInput.Text.Trim();
            if (!string.IsNullOrEmpty(text))
                OnSetFrequency?.Invoke(text);
            FreqInput.Text = string.Empty;
        };
    }

    public void UpdateState(TunableFrequencyState state)
    {
        var freq = state.TunedFrequency;
        var freqStr = freq != RadioFrequency.Off ? TunableFrequencyHelpers.FormatFreq(freq) : "---.---";
        CurrentLabel.Text = Loc.GetString("tunable-radio-current-freq", ("freq", freqStr));

        var minStr = TunableFrequencyHelpers.FormatFreq(state.MinFrequency);
        var maxStr = TunableFrequencyHelpers.FormatFreq(state.MaxFrequency);
        RangeLabel.Text = Loc.GetString("tunable-radio-range-note",
            ("min", minStr), ("max", maxStr));
    }
}
