- type: job
  parent: CMJobBase
  id: CMUJobColonyXenobiologist
  roundSide: Civilian
  roundForce: COLONY
  roundRole: ColonyXenobiologist
  roundComponents:
  - type: Skills
    skills:
      RMCSkillResearch: 2
      RMCSkillMedical: 2
      RMCSkillFireman: 1
  - type: JobPrefix
    prefix: cmu-colony-prefix-xenobiologist
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/CMU14/Interface/cmucolonyblips.rsi
      state: colonist
  name: cmu-colony-name-xenobiologist
  description: cmu-colony-description-xenobiologist
  setPreference: true
  playTimeTracker: CMUJobColonyXenobiologist
  ranks:
    RMCRankCivilian: []
  startingGear: CMUGearColonyXenobiologist
  icon: AU14JobIconColonyColonist
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: cmu-colony-supervisors-colonist
  spawnMenuRoleName: cmu-spawn-role-colony-xenobiologist-cmu 
  accessGroups:
  - Colonist
  roleWeight: 0.25

- type: startingGear
  id: CMUGearColonyXenobiologist
  equipment:
    jumpsuit: RMCJumpsuitCivilianScientist
    outerClothing: RMCLabcoat
    eyes: RMCGlassesReagentHUDGlasses
    gloves: CMHandsLatex
    shoes: RMCShoesLaceup
    back: CMSatchel
    id: AU14IDCardColonyColonist

- type: entity
  parent: CMSpawnPointJobBase
  id: CMUSpawnPointColonyXenobiologist
  name: Spawn Point Colony Xenobiologist
  components:
  - type: SpawnPoint
    job_id: CMUJobColonyXenobiologist
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: CMUJobColonyXenobiologist
  isHumanoid: true
