- type: job
  abstract: true
  parent: AU14JobMilitaryBase
  displayWeight: -1
  id: AU14JobAuxTechBaseAbstract
  name: au14-job-name-govforAuxTech
  description: au14-job-description-govforAuxTech
  icon: "AU14JobIconAuxTech"
<<<<<<< HEAD:Resources/Prototypes/_CMU14/Roles/Military/GovFor/Platoon/Engineering/AuxTech.yml
  # spawnMenuRoleName: Auxiliary Technician (GOVFOR) // RuMC edit
  supervisors: au14-job-supervisors-govfor
  spawnMenuRoleName: Logistics Technician (GOVFOR)
=======
  spawnMenuRoleName: cmu-spawn-role-logistics-technician-govfor 
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Resources/Prototypes/CMU14/Roles/Military/GovFor/Platoon/Engineering/AuxTech.yml
  startingGear: AU14GearGOVFORAuxTech
  dummyStartingGear: AU14GearGOVFORAuxTechDummy
  playTimeTracker: AU14JobGOVFORAuxTech
  overwatchShowName: true
  overwatchRoleName: au14-job-name-govforAuxTech
  overwatchSortPriority: -6
  accessGroups:
  - AU14GovforAuxTech

- type: job
  abstract: true
  parent: AU14JobAuxTechBaseAbstract
  id: AU14JobAuxTechBase
  roundRole: AuxTech
  roundProfiles:
  - AU14RoundJobProfileMilitaryBase
  roundComponents:
  - type: Skills
    preset: AU14SkillPresetPlatoonAuxTech
  - type: JobPrefix
    prefix: au14-job-prefix-govforAuxTech
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/CMU14/Interface/au14govforjobicons.rsi
      state: govfor_logisticstech
  roundForceComponents:
    OPFOR:
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/CMU14/Interface/au14opforjobicons.rsi
        state: logisticstech

  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - NonResuscitable
    - Epilepsy
    - NoEnglish
    - NoEnglish
    - SlowRunner
    - Anemic
  ranks:
    RMCRankCivilian: []
  chevrons:
    RMCRankCorporal:
      entity: AU14ChevronUSCMCorporal
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobGOVFORAuxTech
        time: 86400 # 24 hours
    RMCRankLanceCorporal:
      entity: AU14ChevronUSCMLanceCorporal
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobGOVFORAuxTech
        time: 36000 # 10 hours
    RMCRankPrivateFirstClass:
      entity: AU14ChevronUSCMPrivateFirstClass
      requirements: []

- type: playTimeTracker
  id: AU14JobGOVFORAuxTech
  isHumanoid: true

- type: startingGear
  id: AU14GearGOVFORAuxTech
  equipment:
    ears: AU14HeadsetGovforAuxiliary
    ears2: RMCM5CameraGear
    id: AU14JobIDCardGOVFORAuxTech
    jumpsuit: CMJumpsuitMaintTech
    outerClothing: RMCHazardVestBlue
    shoes: CMBootsBlackFilled
    head: RMCHardhatBlue
  storage:
    back:
    - CMStampApproved
    - AU14StampAUX

- type: startingGear
  id: AU14GearGOVFORAuxTechDummy
  equipment:
    ears: AU14HeadsetGovforAuxiliary
    ears2: RMCM5CameraGear
    id: AU14JobIDCardGOVFORAuxTech
    jumpsuit: CMJumpsuitMaintTech
    outerClothing: RMCHazardVestBlue
    shoes: CMBootsBlackFilled
    head: RMCHardhatBlue

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORAuxTech
  name: Spawn Point GOVFOR Logistics Technician
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORAuxTech
  - type: Sprite
    state: syn_spawn

- type: job
  parent: AU14JobAuxTechBase
  id: AU14JobGOVFORAuxTech
  hidden: false
  setPreference: true
  basePlaytimeTracker: true

- type: roleLoadout
  id: JobAU14JobGOVFORAuxTech
  points: 7
  groups:
  - GOVFORAuxTechClothingAU14
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: job
  parent: AU14JobAuxTechBase
  id: AU14JobOPFORAuxTech
  roundSide: Opfor
  roundForce: OPFOR
  icon: "AU14JobIconOPFORAuxTech"
  spawnMenuRoleName: Logistics Technician (OPFOR)
  supervisors: au14-job-supervisors-opfor
  startingGear: AU14GearOPFORAuxTech
  dummyStartingGear: AU14GearOPFORAuxTechDummy
  accessGroups:
  - AU14OpforAuxTech
  useLoadoutOfJob: AU14JobGOVFORAuxTech

- type: startingGear
  id: AU14GearOPFORAuxTech
  equipment:
    shoes: CMBootsBlackFilled
    ears: AU14HeadsetOpforAuxiliary
    ears2: RMCM5CameraGear
    id: AU14JobIDCardOPFORAuxTech
  storage:
    back:
    - CMStampApproved
    - AU14StampAUX

- type: startingGear
  id: AU14GearOPFORAuxTechDummy
  equipment:
    shoes: CMBootsBlackFilled
    back: CMSatchelMarine
    ears: AU14HeadsetOpforAuxiliary
  storage:
    back:
    - CMStampApproved
    - AU14StampAUX

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointOPFORAuxTech
  name: Spawn Point OPFOR Logistics Technician
  components:
  - type: SpawnPoint
    job_id: AU14JobOPFORAuxTech
  - type: Sprite
    state: syn_spawn
