- type: job
  abstract: true
  parent: AU14JobMilitaryBase
  displayWeight: 1
  id: AU14JobEngineeringTechBaseAbstract
  name: au14-job-name-govforengineeringtech
  description: au14-job-description-govforengineeringtech
  icon: "AU14JobIconGovCT"
  spawnMenuRoleName: cmu-spawn-role-engineering-technician-govfor 
  startingGear: AU14GearGOVFOREngineeringTech
  dummyStartingGear: AU14GearGOVFOREngineeringTechDummy
  playTimeTracker: AU14JobGOVFOREngineeringTech
  accessGroups:
  - AU14GovforEngineer

- type: job
  abstract: true
  parent: AU14JobEngineeringTechBaseAbstract
  id: AU14JobEngineeringTechBase
  roundRole: EngineeringTech
  roundProfiles:
  - AU14RoundJobProfileMilitaryBase
  roundComponents:
  - type: Skills
    preset: AU14SkillPresetPlatoonCombatTechnician
  - type: JobPrefix
    prefix: au14-job-prefix-govforengineeringtech
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/CMU14/Interface/au14govforjobicons.rsi
      state: govfor_ct
  roundForceComponents:
    OPFOR:
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/CMU14/Interface/au14opforjobicons.rsi
        state: ct

  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
    - NonResuscitable
    - NoEnglish
    - SlowRunner
    - Anemic
  ranks:
    RMCRankCivilian: []
  chevrons:
    RMCRankCorporal:
      entity: AU14ChevronUSCMCorporal
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobGOVFOREngineeringTech
        time: 86400 # 24 hours
    RMCRankLanceCorporal:
      entity: AU14ChevronUSCMLanceCorporal
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobGOVFOREngineeringTech
        time: 36000 # 10 hours
    RMCRankPrivateFirstClass:
      entity: AU14ChevronUSCMPrivateFirstClass
      requirements: []

- type: playTimeTracker
  id: AU14JobGOVFOREngineeringTech
  isHumanoid: true

- type: startingGear
  id: AU14GearGOVFOREngineeringTech
  equipment:
    id: AU14IDCardGOVFOREngineeringTech
    ears2: RMCM5CameraGear
    outerClothing: RMCHazardVest
    shoes: CMBootsBlackFilled
    head: RMCHardhatOrange
    jumpsuit: CMJumpsuitMaintTech
    ears: AU14HeadsetGovforMarine

- type: startingGear
  id: AU14GearGOVFOREngineeringTechDummy
  equipment:
    outerClothing: RMCHazardVest
    shoes: CMBootsBlackFilled
    head: RMCHardhatOrange
    jumpsuit: CMJumpsuitMaintTech
    ears: AU14HeadsetGovforMarine

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFOREngineeringTech
  name: Spawn Point GOVFOR Engineering Technician
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFOREngineeringTech
  - type: Sprite
    state: syn_spawn

- type: job
  parent: AU14JobEngineeringTechBase
  id: AU14JobGOVFOREngineeringTech
  hidden: false
  setPreference: true
  basePlaytimeTracker: true

- type: roleLoadout
  id: JobAU14JobGOVFOREngineeringTech
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: job
  parent: AU14JobEngineeringTechBase
  id: AU14JobOPFOREngineeringTech
  roundSide: Opfor
  roundForce: OPFOR
  icon: "AU14JobIconOPFORCT"
  spawnMenuRoleName: Engineering Technician (OPFOR)
  supervisors: au14-job-supervisors-opfor
  startingGear: AU14GearOPFOREngineeringTech
  dummyStartingGear: AU14GearOPFOREngineeringTechDummy
  accessGroups:
  - AU14OpforEngineer
  useLoadoutOfJob: AU14JobGOVFOREngineeringTech

- type: startingGear
  id: AU14GearOPFOREngineeringTech
  equipment:
    id: AU14IDCardOPFOREngineeringTech
    ears2: RMCM5CameraGear
    outerClothing: RMCHazardVest
    shoes: CMBootsBlackFilled
    head: RMCHardhatOrange
    jumpsuit: CMJumpsuitMaintTech
    ears: AU14HeadsetOpforMarine

- type: startingGear
  id: AU14GearOPFOREngineeringTechDummy
  equipment:
    outerClothing: RMCHazardVest
    shoes: CMBootsBlackFilled
    head: RMCHardhatOrange
    jumpsuit: CMJumpsuitMaintTech
    ears: AU14HeadsetOpforMarine

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointOPFOREngineeringTech
  name: Spawn Point OPFOR Engineering Technician
  components:
  - type: SpawnPoint
    job_id: AU14JobOPFOREngineeringTech
  - type: Sprite
    state: syn_spawn
