using Content.Shared.CMU14.Medical.Core;
using Content.Shared.CMU14.ZLevels;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class CmuTab : Control
{
    [Dependency] private IConfigurationManager _cfg = default!;

    private const float OldZLevelBlurStrength = 2.0f;

    public event Action<bool, string>? CrtUiPreviewChanged;
    public event Action? OpenUiSetupRequested;

    public CmuTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        OpenUiSetupButton.OnPressed += _ => OpenUiSetupRequested?.Invoke();
        Appearance.RegisterOptions(Control);
        Appearance.CrtUiPreviewChanged += (enabled, color) => CrtUiPreviewChanged?.Invoke(enabled, color);
        Control.OnApplied += MarkUiConfigured;

        Control.AddOptionCheckBox(CCVars.ChatEnableRunechatBubbles, RunechatSpeechBubblesCheckBox);
        Control.AddOptionPercentSlider(CCVars.ChatRunechatBubbleScale, RunechatSpeechBubbleScaleSlider, 0.5f, 2f);
        Control.AddOptionCheckBox(CCVars.CMUVoteUiLarge, VoteUiLargeCheckBox);
        // CMU14: tactical map preferences.
        Control.AddOptionCheckBox(CCVars.CMUTacMapClassic, ClassicTacMapCheckBox);
        Control.AddOptionCheckBox(CCVars.CMUTacMapCenterOnOpen, CenterTacMapCheckBox);
        Control.AddOptionCheckBox(CCVars.ExamineLogInChat, ExamineLogInChatCheckBox);
        Control.AddOptionCheckBox(CCVars.ExamineFullTextInChat, ExamineFullTextInChatCheckBox);
        Control.AddOptionCheckBox(CCVars.CMUAutoIngestEnabled, AutoIngestCheckBox);
        // CMU14: client temperature unit preference
        Control.AddOptionCheckBox(CCVars.CMUTemperatureFahrenheit, TemperatureFahrenheitCheckBox);
        Control.AddOptionCheckBox(CCVars.ExplosionScreenShakeEnabled, ExplosionScreenShakeEnabledCheckBox);
        Control.AddOptionCheckBox(CCVars.ExplosionScreenShakeIgnoreFar, ExplosionScreenShakeIgnoreFarCheckBox);
        Control.AddOptionCheckBox(CCVars.FirearmScreenShakeEnabled, FirearmScreenShakeEnabledCheckBox);
        Control.AddOptionCheckBox(CCVars.MuteScriptedSounds, MuteScriptedSoundsCheckBox);
        Control.AddOptionCheckBox(CMUMedicalCCVars.TargetedHealingEnabled, TargetedHealingCheckBox);
        Control.AddOptionCheckBox(CMUMedicalCCVars.AutoReapplyKitsEnabled, AutoReapplyKitsCheckBox);
        Control.AddOptionCheckBox(CMUMedicalCCVars.UiLessSurgeryEnabled, UiLessSurgeryCheckBox);
        Control.AddOptionCheckBox(CCVars.CMUScreamOnHotbarEnabled, ScreamOnHotbarCheckBox);
        Control.AddOptionPercentSlider(CMUZLevelsCVars.BlurStrength, ZLevelBlurSlider, scale: OldZLevelBlurStrength);

        Control.Initialize();
    }

    private void MarkUiConfigured()
    {
        _cfg.SetCVar(CCVars.CMUUiConfigured, true);
    }
}
