using System.Linq;
using Content.Client._RMC14.LinkAccount;
using Content.Client.UserInterface.Screens;
using Content.Shared._Mono.CCVar;
using Content.Shared._RMC14.CCVar;
using Content.Shared._RMC14.NightVision;
using Content.Shared.CCVar;
using Content.Shared.HUD;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Prototypes;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class MiscTab : Control
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private LinkAccountManager _linkAccount = default!;

    public MiscTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var themes = _prototypeManager.EnumeratePrototypes<HudThemePrototype>().ToList();
        themes.Sort();
        var themeEntries = new List<OptionDropDownCVar<string>.ValueOption>();
        foreach (var gear in themes)
        {
            themeEntries.Add(new OptionDropDownCVar<string>.ValueOption(gear.ID, Loc.GetString(gear.Name)));
        }

        var layoutEntries = new List<OptionDropDownCVar<string>.ValueOption>();
        foreach (var layout in Enum.GetValues(typeof(ScreenType)))
        {
            layoutEntries.Add(new OptionDropDownCVar<string>.ValueOption(layout.ToString()!, Loc.GetString($"ui-options-hud-layout-{layout.ToString()!.ToLower()}")));
        }

        var xenoNightVisionEntries = new List<OptionDropDownCVar<int>.ValueOption>
        {
            new((int) NightVisionState.Off, Loc.GetString("rmc-ui-xeno-night-vision-default-off")),
            new((int) NightVisionState.Half, Loc.GetString("rmc-ui-xeno-night-vision-default-half")),
            new((int) NightVisionState.Full, Loc.GetString("rmc-ui-xeno-night-vision-default-full")),
        };

        // Channel can be null in replays so.
        // ReSharper disable once ConditionalAccessQualifierIsNonNullableAccordingToAPIContract
        ShowOocPatronColor.Visible = _linkAccount.Tier != null;

        Control.AddOptionDropDown(CVars.InterfaceTheme, DropDownHudTheme, themeEntries);
        Control.AddOptionDropDown(CCVars.UILayout, DropDownHudLayout, layoutEntries);
        // AU14: viewport centering for the Separated layout (chat panel otherwise pushes the view left).
        Control.AddOptionCheckBox(Content.Shared.CMU14.CCVar.AU14CCVars.CenterSeparatedViewport, CenterSeparatedViewportCheckBox);
        var separatedHudStatusSideEntries = new List<OptionDropDownCVar<string>.ValueOption>
        {
            new("right", Loc.GetString("au14-ui-options-separated-hud-status-side-right")),
            new("left", Loc.GetString("au14-ui-options-separated-hud-status-side-left")),
        };
        Control.AddOptionDropDown(Content.Shared.CMU14.CCVar.AU14CCVars.SeparatedHudStatusSide, SeparatedHudStatusSideDropdown, separatedHudStatusSideEntries);

        Control.AddOptionCheckBox(CVars.DiscordEnabled, DiscordRich);
        Control.AddOptionCheckBox(CCVars.ShowOocPatronColor, ShowOocPatronColor);
        Control.AddOptionCheckBox(CCVars.LoocAboveHeadShow, ShowLoocAboveHeadCheckBox);
        Control.AddOptionCheckBox(CCVars.HudHeldItemShow, ShowHeldItemCheckBox);
        Control.AddOptionCheckBox(CCVars.CombatModeIndicatorsPointShow, ShowCombatModeIndicatorsCheckBox);
        Control.AddOptionCheckBox(CCVars.OpaqueStorageWindow, OpaqueStorageWindowCheckBox);
        Control.AddOptionCheckBox(CCVars.ChatEnableFancyBubbles, FancySpeechBubblesCheckBox);
        Control.AddOptionCheckBox(CCVars.ChatFancyNameBackground, FancyNameBackgroundsCheckBox);
        Control.AddOptionCheckBox(CCVars.StaticStorageUI, StaticStorageUI);
        // CMU14
        var constructionModeEntries = new List<OptionDropDownCVar<bool>.ValueOption>
        {
            new(true, Loc.GetString("cmu-ui-options-construction-mode-improved")),
            new(false, Loc.GetString("cmu-ui-options-construction-mode-default")),
        };
        Control.AddOptionDropDown(CCVars.ConstructionMenuImproved, DropDownConstructionMode, constructionModeEntries);

        Control.AddOptionCheckBox(RMCCVars.RMCAutoPunctuate, RMCAutoPunctuate);
        Control.AddOptionCheckBox(RMCCVars.RMCAutoEjectMagazines, RMCAutoEjectMagazines);
        Control.AddOptionCheckBox(RMCCVars.RMCDamageYourself, RMCDamageYourself);
        Control.AddOptionCheckBox(RMCCVars.RMCShowNewPlayerIcons, RMCShowNewPlayerIcons);
        Control.AddOptionDropDown(RMCCVars.RMCXenoDefaultNightVision, RMCXenoNightVisionDefault, xenoNightVisionEntries);
        Control.AddOptionCheckBox(MonoCVars.AreaEchoEnabled, AreaEchoCheckBox); // Mono
        Control.AddOptionCheckBox(MonoCVars.AreaEchoHighResolution, AreaEchoHighResolutionCheckBox); // Mono
        Control.AddOptionCheckBox(CCVars.InterfaceChatFollowButton, ChatFollowButton);

        Control.Initialize();
    }
}
