using System;
using System.Collections.Generic;
using System.Linq;
using Content.Shared.Chat;
using Content.Shared.CCVar;
using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Chat;
using Robust.Shared.Utility;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.UserInterface.Systems.Chat.Controls;

[GenerateTypedNameReferences]
public sealed partial class ChannelFilterPopup : Popup
{
    // order in which the available channel filters show up when available
    public static readonly ChatChannel[] ChannelFilterOrder =
    {
        ChatChannel.Local,
        ChatChannel.Whisper,
        ChatChannel.Emotes,
        ChatChannel.Radio,
        ChatChannel.Notifications,
        ChatChannel.Damage,
        ChatChannel.Visual,
        ChatChannel.LOOC,
        ChatChannel.OOC,
        ChatChannel.Dead,
        ChatChannel.Admin,
        ChatChannel.AdminAlert,
        ChatChannel.AdminChat,
        ChatChannel.MentorChat,
        ChatChannel.Server
    };

    private readonly Dictionary<ChatChannel, ChannelFilterCheckbox> _filterStates = new();
    private readonly Dictionary<string, ChatTabButton> _tabButtons = new();
    private readonly Dictionary<string, CheckBox> _radioFilterStates = new();
    private string? _draggingTabId;
    private string? _dragTargetTabId;
    private bool _filtersReadOnly;

    public event Action<ChatChannel, bool>? OnChannelFilter;
    public event Action<string, bool>? OnRadioFilter;
    public event Action<string>? OnNewHighlights;
    public event Action<string>? OnTabSelected;
    public event Action<string>? OnTabAdded;
    public event Action<string>? OnTabRemoved;
    public event Action<string, string>? OnTabRenamed;
    public event Action<string, string>? OnTabMoved;
    public event Action<string, string?, string?>? OnStyleChanged;
    public event Action<string>? OnStyleReset;
    public event Action<bool>? OnLegacyModeChanged;
    public event Action<bool>? OnColorWholeMessageChanged;

    public ChannelFilterPopup()
    {
        RobustXamlLoader.Load(this);

        FiltersPageButton.ToggleMode = true;
        TabsPageButton.ToggleMode = true;
        StylesPageButton.ToggleMode = true;
        DisplayPageButton.ToggleMode = true;
        FiltersPageButton.HorizontalExpand = true;
        TabsPageButton.HorizontalExpand = true;
        StylesPageButton.HorizontalExpand = true;
        DisplayPageButton.HorizontalExpand = true;
        FiltersPageButton.OnPressed += _ => ShowSettingsPage(FiltersPage);
        TabsPageButton.OnPressed += _ => ShowSettingsPage(TabsPage);
        StylesPageButton.OnPressed += _ => ShowSettingsPage(StylesPage);
        DisplayPageButton.OnPressed += _ => ShowSettingsPage(DisplayPage);
        ShowSettingsPage(FiltersPage);

        HighlightButton.OnPressed += HighlightsEntered;
        AddTabButton.OnPressed += AddTabPressed;
        RenameTabButton.OnPressed += RenameTabPressed;
        RenameTabNameEdit.OnTextEntered += RenameTabEntered;
        RemoveTabButton.OnPressed += RemoveTabPressed;
        ColorWholeMessageCheckBox.OnPressed += ColorWholeMessagePressed;
        LegacyChatCheckBox.OnPressed += LegacyModePressed;

        // Add a placeholder text to the highlights TextEdit.
        HighlightEdit.Placeholder = new Rope.Leaf(Loc.GetString("hud-chatbox-highlights-placeholder"));

        // Load highlights if any were saved.
        var cfg = IoCManager.Resolve<IConfigurationManager>();
        string highlights = cfg.GetCVar(CCVars.ChatHighlights);

        if (!string.IsNullOrEmpty(highlights))
        {
            UpdateHighlights(highlights);
        }

        ApplyCrtTheme();
    }

    /// <summary>
    ///     Every panel in this popup is authored with a baked <c>PanelOverride</c> colour, which also
    ///     beats any stylesheet rule. For CRT users, drop those and use style classes so the popup
    ///     tracks the palette, then let <see cref="CrtLobbyTheme"/> tag the buttons, labels, line
    ///     edits and scrollbars.
    /// </summary>
    /// <remarks>
    ///     Safe to use CrtLobbyTheme here even though it skips chat: it only bails on a
    ///     <c>ChatBox</c>, and this popup is created into the modal root, not under one.
    /// </remarks>
    private void ApplyCrtTheme()
    {
        if (!StyleNano.CrtUiEnabled)
            return;

        FilterPopupPanel.PanelOverride = null;
        FilterPopupPanel.AddStyleClass(StyleNano.StyleClassCrtPanel);
        ApplyCrtTheme(FilterPopupPanel);
    }

    /// <summary>
    ///     Re-themes a subtree built after construction. Both halves are needed: CrtLobbyTheme only
    ///     tags controls that exist when it runs, and it never touches <see cref="PanelContainer"/>,
    ///     which the rows here author with their own baked colours.
    /// </summary>
    private static void ApplyCrtTheme(Control container)
    {
        if (!StyleNano.CrtUiEnabled)
            return;

        foreach (var panel in GetDescendantPanels(container))
        {
            panel.PanelOverride = null;
            panel.AddStyleClass(StyleNano.StyleClassCrtInsetPanel);
        }

        CrtLobbyTheme.Apply(container);
    }

    private static IEnumerable<PanelContainer> GetDescendantPanels(Control root)
    {
        foreach (var child in root.Children)
        {
            if (child is PanelContainer panel)
                yield return panel;

            foreach (var nested in GetDescendantPanels(child))
            {
                yield return nested;
            }
        }
    }

    public bool IsActive(ChatChannel channel)
    {
        return _filterStates.TryGetValue(channel, out var checkbox) && checkbox.Pressed;
    }

    public void SetActive(ChatChannel channel, bool isActive, bool quiet = false)
    {
        if (_filterStates.TryGetValue(channel, out var checkbox) && checkbox.Pressed != isActive)
        {
            checkbox.Pressed = isActive;
            if (!quiet)
                OnChannelFilter?.Invoke(checkbox.Channel, checkbox.Pressed);
        }
    }

    public void SetActiveMask(ChatChannel channels, bool quiet = false)
    {
        foreach (var (channel, checkbox) in _filterStates)
        {
            var active = (channels & channel) != 0;
            if (checkbox.Pressed == active)
                continue;

            checkbox.Pressed = active;
            if (!quiet)
                OnChannelFilter?.Invoke(checkbox.Channel, checkbox.Pressed);
        }
    }

    public ChatChannel GetActive()
    {
        ChatChannel active = 0;

        foreach (var (key, value) in _filterStates)
        {
            if (value.IsHidden || !value.Pressed)
            {
                continue;
            }

            active |= key;
        }

        return active;
    }

    public void SetChannels(ChatChannel channels)
    {
        foreach (var channel in ChannelFilterOrder)
        {
            if (!_filterStates.TryGetValue(channel, out var checkbox))
            {
                checkbox = new ChannelFilterCheckbox(channel);
                _filterStates.Add(channel, checkbox);
                checkbox.OnPressed += CheckboxPressed;
                checkbox.Pressed = true;
            }

            checkbox.Disabled = _filtersReadOnly;
            if ((channels & channel) == 0)
            {
                if (checkbox.Parent == FilterVBox)
                {
                    FilterVBox.RemoveChild(checkbox);
                }
            }
            else if (checkbox.IsHidden)
            {
                FilterVBox.AddChild(checkbox);
            }
        }

        ApplyCrtTheme(FilterVBox);
    }

    public void SetFiltersReadOnly(bool readOnly)
    {
        _filtersReadOnly = readOnly;
        foreach (var checkbox in _filterStates.Values)
        {
            checkbox.Disabled = readOnly;
        }
    }

    public void ConfigureTabs(IReadOnlyList<ChatTabSettings> tabs, string activeTabId)
    {
        _draggingTabId = null;
        _dragTargetTabId = null;

        while (TabsList.ChildCount > 0)
        {
            TabsList.RemoveChild(0);
        }

        _tabButtons.Clear();
        var activeTab = tabs.FirstOrDefault(tab => string.Equals(tab.Id, activeTabId, StringComparison.OrdinalIgnoreCase));
        var activeIsAll = activeTab != null &&
                          string.Equals(activeTab.Id, ChatUserSettings.AllTabId, StringComparison.OrdinalIgnoreCase);

        foreach (var tab in tabs)
        {
            var capturedId = tab.Id;
            var isAll = string.Equals(tab.Id, ChatUserSettings.AllTabId, StringComparison.OrdinalIgnoreCase);
            var button = new ChatTabButton(tab.Id)
            {
                Text = ChatUserSettings.GetDisplayTitle(tab), // CMU14 hardcode Localization
                ToggleMode = true,
                Mode = BaseButton.ActionMode.Release,
                Pressed = tab.Id == activeTabId,
                HorizontalExpand = true,
                MinHeight = 28,
                CanDrag = !isAll
            };
            button.OnPressed += _ => OnTabSelected?.Invoke(capturedId);
            button.DragStarted += OnTabDragStarted;
            button.DragEntered += OnTabDragEntered;
            button.DragExited += OnTabDragExited;
            button.DragEnded += OnTabDragEnded;
            TabsList.AddChild(button);
            _tabButtons[capturedId] = button;
        }

        UpdateTabDragVisuals();
        RenameTabNameEdit.Text = activeTab?.Title ?? string.Empty;
        RenameTabNameEdit.Editable = activeTab != null && !activeIsAll;
        RenameTabButton.Disabled = activeTab == null || activeIsAll;
        RemoveTabButton.Disabled = tabs.Count <= 1 ||
                                   string.Equals(activeTabId, ChatUserSettings.AllTabId, StringComparison.OrdinalIgnoreCase);

        ApplyCrtTheme(TabsList);
    }

    public void ConfigureRadioFilters(IReadOnlyList<ChatRadioTarget> radios, IReadOnlyList<string> activeLabels, bool radioEnabled)
    {
        while (RadioFilterVBox.ChildCount > 0)
        {
            RadioFilterVBox.RemoveChild(0);
        }

        _radioFilterStates.Clear();

        if (radios.Count == 0)
        {
            RadioFilterVBox.AddChild(new Label
            {
                Text = Loc.GetString("hud-chatbox-filter-radios-empty"),
                Modulate = Color.FromHex("#7f8792")
            });
            return;
        }

        var allRadios = activeLabels.Count == 0;
        foreach (var radio in radios)
        {
            var checkbox = new CheckBox
            {
                Text = radio.Name,
                Pressed = allRadios || activeLabels.Any(label => string.Equals(label, radio.Label, StringComparison.OrdinalIgnoreCase)),
                Disabled = !radioEnabled,
                Modulate = Color.TryFromHex(radio.Color, out var radioColor) ? radioColor : Color.White,
                // Match the channel filters in the column beside these.
                MinHeight = 26
            };

            var capturedLabel = radio.Label;
            checkbox.OnPressed += args =>
            {
                var pressed = ((CheckBox) args.Button).Pressed;
                OnRadioFilter?.Invoke(capturedLabel, pressed);
            };

            RadioFilterVBox.AddChild(checkbox);
            _radioFilterStates[capturedLabel] = checkbox;
        }

        ApplyCrtTheme(RadioFilterVBox);
    }

    public void ConfigureStyles(IReadOnlyList<ChatStyleSettings> styles, IReadOnlyList<ChatStyleTarget> targets)
    {
        while (StyleRows.ChildCount > 0)
        {
            StyleRows.RemoveChild(0);
        }

        foreach (var target in targets)
        {
            var style = styles.FirstOrDefault(entry => string.Equals(entry.Target, target.Key, StringComparison.OrdinalIgnoreCase));
            var color = style?.Color ?? target.DefaultColor;
            var fontSize = style?.FontSize?.ToString() ?? target.DefaultFontSize?.ToString() ?? string.Empty;
            var accent = Color.TryFromHex(color, out var accentColor) ? accentColor : Color.FromHex("#737987");

            var rowPanel = new PanelContainer
            {
                HorizontalExpand = true,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex("#151923"),
                    BorderColor = Color.FromHex("#303747"),
                    BorderThickness = new Thickness(1),
                    ContentMarginLeftOverride = 7,
                    ContentMarginRightOverride = 7,
                    ContentMarginTopOverride = 6,
                    ContentMarginBottomOverride = 6
                }
            };

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 8,
                HorizontalExpand = true
            };
            rowPanel.AddChild(row);

            var nameBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 6,
                MinWidth = 205,
                HorizontalExpand = true
            };

            nameBox.AddChild(new PanelContainer
            {
                MinWidth = 7,
                MinHeight = 30,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = accent,
                    ContentMarginLeftOverride = 1,
                    ContentMarginRightOverride = 1
                }
            });

            nameBox.AddChild(new Label
            {
                Text = target.Name,
                HorizontalExpand = true,
                ClipText = true,
                VerticalAlignment = VAlignment.Center,
                Modulate = Color.FromHex("#D6DCE0")
            });
            row.AddChild(nameBox);

            var controls = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 5,
                HorizontalAlignment = HAlignment.Right
            };
            row.AddChild(controls);

            var colorEdit = new LineEdit
            {
                Text = color,
                PlaceHolder = Loc.GetString("hud-chatbox-style-color-placeholder"),
                ToolTip = Loc.GetString("hud-chatbox-style-color-tooltip"),
                MinWidth = 104,
                MaxWidth = 112
            };
            controls.AddChild(colorEdit);

            var sizeEdit = new LineEdit
            {
                Text = fontSize,
                PlaceHolder = Loc.GetString(
                    "hud-chatbox-style-size-placeholder",
                    ("min", ChatUserSettings.MinFontSize),
                    ("max", ChatUserSettings.MaxFontSize)),
                ToolTip = Loc.GetString(
                    "hud-chatbox-style-size-tooltip",
                    ("min", ChatUserSettings.MinFontSize),
                    ("max", ChatUserSettings.MaxFontSize)),
                MinWidth = 54,
                MaxWidth = 62
            };
            controls.AddChild(sizeEdit);

            var applyButton = new Button
            {
                Text = Loc.GetString("hud-chatbox-style-apply"),
                MinWidth = 46,
                ToolTip = Loc.GetString("hud-chatbox-style-apply-tooltip")
            };
            applyButton.OnPressed += _ => OnStyleChanged?.Invoke(
                target.Key,
                colorEdit.Text,
                sizeEdit.Text);
            controls.AddChild(applyButton);

            var resetButton = new Button
            {
                Text = Loc.GetString("hud-chatbox-style-reset"),
                MinWidth = 54,
                ToolTip = Loc.GetString("hud-chatbox-style-reset-tooltip")
            };
            resetButton.OnPressed += _ => OnStyleReset?.Invoke(target.Key);
            controls.AddChild(resetButton);

            StyleRows.AddChild(rowPanel);
        }

        ApplyCrtTheme(StyleRows);
    }

    public void SetLegacyMode(bool enabled)
    {
        LegacyChatCheckBox.Pressed = enabled;
    }

    public void SetColorWholeMessage(bool enabled)
    {
        ColorWholeMessageCheckBox.Pressed = enabled;
    }

    public void UpdateHighlights(string highlights)
    {
        HighlightEdit.TextRope = new Rope.Leaf(highlights);
    }

    private void CheckboxPressed(ButtonEventArgs args)
    {
        var checkbox = (ChannelFilterCheckbox) args.Button;
        OnChannelFilter?.Invoke(checkbox.Channel, checkbox.Pressed);
    }

    private void HighlightsEntered(ButtonEventArgs _args)
    {
        OnNewHighlights?.Invoke(Rope.Collapse(HighlightEdit.TextRope));
    }

    private void AddTabPressed(ButtonEventArgs _args)
    {
        OnTabAdded?.Invoke(NewTabNameEdit.Text);
        NewTabNameEdit.Text = string.Empty;
    }

    private void RenameTabEntered(LineEdit.LineEditEventArgs args)
    {
        RenameSelectedTab();
    }

    private void RenameTabPressed(ButtonEventArgs _args)
    {
        RenameSelectedTab();
    }

    private void RenameSelectedTab()
    {
        foreach (var (id, button) in _tabButtons)
        {
            if (!button.Pressed ||
                string.Equals(id, ChatUserSettings.AllTabId, StringComparison.OrdinalIgnoreCase))
                continue;

            OnTabRenamed?.Invoke(id, RenameTabNameEdit.Text);
            return;
        }
    }

    private void OnTabDragStarted(string tabId)
    {
        if (string.Equals(tabId, ChatUserSettings.AllTabId, StringComparison.OrdinalIgnoreCase))
            return;

        _draggingTabId = tabId;
        _dragTargetTabId = null;
        UpdateTabDragVisuals();
    }

    private void OnTabDragEntered(string targetTabId)
    {
        if (_draggingTabId == null)
            return;

        if (string.Equals(_draggingTabId, targetTabId, StringComparison.OrdinalIgnoreCase) ||
            string.Equals(targetTabId, ChatUserSettings.AllTabId, StringComparison.OrdinalIgnoreCase))
        {
            _dragTargetTabId = null;
            UpdateTabDragVisuals();
            return;
        }

        _dragTargetTabId = targetTabId;
        UpdateTabDragVisuals();
    }

    private void OnTabDragExited(string targetTabId)
    {
        if (_draggingTabId == null ||
            !string.Equals(_dragTargetTabId, targetTabId, StringComparison.OrdinalIgnoreCase))
            return;

        _dragTargetTabId = null;
        UpdateTabDragVisuals();
    }

    private void OnTabDragEnded(string tabId)
    {
        var draggingTabId = _draggingTabId;
        if (draggingTabId == null)
            return;

        var targetTabId = _dragTargetTabId;

        _draggingTabId = null;
        _dragTargetTabId = null;

        UpdateTabDragVisuals();

        if (targetTabId != null)
            OnTabMoved?.Invoke(draggingTabId, targetTabId);
    }

    private void UpdateTabDragVisuals()
    {
        foreach (var (tabId, button) in _tabButtons)
        {
            var dragging = string.Equals(tabId, _draggingTabId, StringComparison.OrdinalIgnoreCase);
            var dropTarget = string.Equals(tabId, _dragTargetTabId, StringComparison.OrdinalIgnoreCase);
            button.SetDragVisualState(dragging, dropTarget);
        }
    }

    private void RemoveTabPressed(ButtonEventArgs _args)
    {
        foreach (var (id, button) in _tabButtons)
        {
            if (button.Pressed)
            {
                OnTabRemoved?.Invoke(id);
                return;
            }
        }
    }

    private void LegacyModePressed(ButtonEventArgs args)
    {
        OnLegacyModeChanged?.Invoke(((CheckBox) args.Button).Pressed);
    }

    private void ColorWholeMessagePressed(ButtonEventArgs args)
    {
        OnColorWholeMessageChanged?.Invoke(((CheckBox) args.Button).Pressed);
    }

    private void ShowSettingsPage(Control page)
    {
        FiltersPage.Visible = page == FiltersPage;
        TabsPage.Visible = page == TabsPage;
        StylesPage.Visible = page == StylesPage;
        DisplayPage.Visible = page == DisplayPage;

        FiltersPageButton.Pressed = page == FiltersPage;
        TabsPageButton.Pressed = page == TabsPage;
        StylesPageButton.Pressed = page == StylesPage;
        DisplayPageButton.Pressed = page == DisplayPage;
    }

    public void UpdateUnread(ChatChannel channel, int? unread)
    {
        if (_filterStates.TryGetValue(channel, out var checkbox))
            checkbox.UpdateUnreadCount(unread);
    }
}
