using System;
using Content.Client._CMU14.Interface;
using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using Content.Shared.Ghost;
using Content.Shared.Ghost.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Voting.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class VotePopup : Control
    {
        [Dependency] private IGameTiming _gameTiming = default!;
        [Dependency] private IVoteManager _voteManager = default!;
        [Dependency] private IEntityNetworkManager _net = default!;
        [Dependency] private IConfigurationManager _cfg = default!;
        [Dependency] private IStylesheetManager _stylesheetManager = default!;

        private readonly VoteManager.ActiveVote _vote;
        private readonly Button[] _voteButtons;
        // Separate counts are shown for CRT vote bars and hidden in the standard theme.
        private readonly Label[] _voteCounts;
        private readonly NetEntity? _targetEntity;
        private int _optionColumns = -1;
        private int _optionMinWidth = -1;
        private int _optionMinHeight = -1;

        private const int CompactOptionMinWidth = 220;
        private const int WideOptionMinWidth = 400;
        private const int SingleOptionMinWidth = 560;
        private const int WideOptionTextLength = 24;
        private const int VeryWideOptionTextLength = 42;
        private const int TallOptionTextLength = 32;

        /// <summary>
        ///     Matches HSeparationOverride on VoteOptionsContainer. Needed here to work out how many
        ///     columns actually fit.
        /// </summary>
        private const int OptionSeparation = CmuPanelMetrics.RowSeparation;

        /// <summary>
        ///     Horizontal margin on MainContent, doubled. The options have this much less room than
        ///     the popup itself. Derived rather than typed: the XAML sets that margin from the same
        ///     constant, and if this number stops matching it, options get sliced off at the border.
        /// </summary>
        private const int ContentHorizontalMargin = CmuPanelMetrics.ContentPaddingHorizontal * 2;

        private const float LargeUiScale = 1.35f;

        private float OptionScale => _cfg.GetCVar(CCVars.CMUVoteUiLarge) ? LargeUiScale : 1f;

        public VotePopup(VoteManager.ActiveVote vote)
        {
            _vote = vote;
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            ApplyCrtPalette();
            CrtLobbyTheme.Apply(this);
            _stylesheetManager.CrtThemeChanged += OnThemeChanged;
            _cfg.OnValueChanged(CCVars.CMUVoteUiLarge, OnVoteUiLargeChanged);

            if (_vote.TargetEntity != null && _vote.TargetEntity != 0)
            {
                _targetEntity = new NetEntity(_vote.TargetEntity.Value);
                FollowVoteTarget.Visible = true;
                FollowVoteTarget.OnPressed += _ => AttemptFollowVoteEntity();
            }

            Modulate = Color.White;
            _voteButtons = new Button[vote.Entries.Length];
            _voteCounts = new Label[vote.Entries.Length];
            var group = new ButtonGroup();

            for (var i = 0; i < _voteButtons.Length; i++)
            {
                var button = new Button
                {
                    ToggleMode = true,
                    Group = group,
                    HorizontalExpand = true,
                    MinHeight = CmuPanelMetrics.Row,
                    ClipText = false,
                    RectClipContent = false,
                    TextAlign = StyleNano.CrtUiEnabled ? Label.AlignMode.Left : Label.AlignMode.Center,
                    StyleClasses = { StyleNano.StyleClassCrtButton }
                };
                button.Label.AddStyleClass(StyleNano.StyleClassCrtButtonLabel);
                button.Label.HorizontalExpand = true;
                button.Label.VAlign = Label.VAlignMode.Center;

                {
                    // The count is its own label so it can sit hard right while the name stays left -
                    // a Button has exactly one Label and it cannot align two things at once.
                    var count = new Label
                    {
                        Visible = StyleNano.CrtUiEnabled,
                        HorizontalAlignment = HAlignment.Right,
                        VerticalAlignment = VAlignment.Center,
                        Margin = new Thickness(0, 0, 10, 0),
                    };
                    count.AddStyleClass(StyleNano.StyleClassCrtButtonLabel);
                    button.AddChild(count);
                    _voteCounts[i] = count;
                }

                _voteButtons[i] = button;
                VoteOptionsContainer.AddChild(button);
                var i1 = i;
                button.OnPressed += _ => _voteManager.SendCastVote(vote.Id, i1);
            }

            MinimizeButton.OnPressed += _ => SetMinimized(true);
            RestoreButton.OnPressed += _ => SetMinimized(false);
            ReflowOptions(GetRawOptionTexts());
        }

        protected override void Resized()
        {
            base.Resized();

            // Column count depends on how much room we actually got, and that isn't known until the
            // first layout pass - nor when the window or the lobby split is resized afterwards.
            ReflowOptions(GetRawOptionTexts());
        }

        [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            _stylesheetManager.CrtThemeChanged -= OnThemeChanged;
            _cfg.UnsubValueChanged(CCVars.CMUVoteUiLarge, OnVoteUiLargeChanged);
        }

        private void OnVoteUiLargeChanged(bool _)
        {
            // Reset the cache or ReflowOptions decides nothing changed and returns early.
            _optionColumns = -1;
            ReflowOptions(GetRawOptionTexts());
        }

        private void OnThemeChanged()
        {
            ApplyCrtPalette();
            CrtLobbyTheme.Apply(this);
            UpdateData();
        }

        private void ApplyCrtPalette()
        {
            Stylesheet = _stylesheetManager.SheetNano;
            VotePanel.PanelOverride = CreateVotePanelStyleBox();
            VoteCaller.FontColorOverride = CrtTerminalPalette.Text;
            MinimizedTitle.FontColorOverride = CrtTerminalPalette.TextBright;
            MinimizeButton.Label.FontColorOverride = CrtTerminalPalette.TextBright;
            RestoreButton.Label.FontColorOverride = CrtTerminalPalette.TextBright;
            FollowVoteTarget.Label.FontColorOverride = CrtTerminalPalette.TextBright;
        }

        /// <summary>
        ///     One ground, not a bordered box - the same chassis as <c>CrtScreenPanel</c>, built here
        ///     by hand because this panel needs its own <see cref="CmuPanelMetrics.PanelPadding"/>
        ///     inset rather than the shared class's zero margin.
        /// </summary>
        private static CrtStyleBox CreateVotePanelStyleBox()
        {
            return new CrtStyleBox
            {
                BackgroundColor = CrtTerminalPalette.Surface0,
                BorderColor = CrtTerminalPalette.Line,
                CornerColor = CrtTerminalPalette.Line,
                // Off-theme has no ladder to separate this panel from what's behind it, so it keeps a
                // border; under CRT the fill against Void does that job and a border is the
                // box-in-box this pass has been removing everywhere else.
                BorderThickness = StyleNano.CrtUiEnabled ? new Thickness(0) : new Thickness(1),
                CornerLength = 11,
                ContentMarginLeftOverride = CmuPanelMetrics.PanelPadding.Left,
                ContentMarginRightOverride = CmuPanelMetrics.PanelPadding.Right,
                ContentMarginTopOverride = CmuPanelMetrics.PanelPadding.Top,
                ContentMarginBottomOverride = CmuPanelMetrics.PanelPadding.Bottom
            };
        }

        public void UpdateData()
        {
            // TextBright rather than the RichTextLabel default: this is the question the popup
            // exists to ask, and the caller line above it is deliberately dim so the two don't
            // compete for the same first glance.
            VoteTitle.SetMessage(FormattedMessage.FromUnformatted(_vote.Title),
                defaultColor: StyleNano.CrtUiEnabled ? CrtTerminalPalette.TextBright : null);
            VoteCaller.Text = Loc.GetString("ui-vote-created", ("initiator", _vote.Initiator));
            MinimizedTitle.Text = _vote.Title;
            var buttonTexts = new string[_voteButtons.Length];

            // Total, not max: a bar should read as this option's share of the vote, so a lone vote in
            // a four-way split is a quarter bar rather than a full one.
            var totalVotes = 0;
            foreach (var e in _vote.Entries)
            {
                totalVotes += e.Votes;
            }

            for (var i = 0; i < _voteButtons.Length; i++)
            {
                var entry = _vote.Entries[i];
                string buttonText;
                if (_vote.DisplayVotes)
                {
                    buttonText = Loc.GetString("ui-vote-button", ("text", entry.Text), ("votes", entry.Votes));
                }
                else
                {
                    buttonText = Loc.GetString("ui-vote-button-no-votes", ("text", entry.Text));
                }

                // Reflow still measures the combined string. It is what decides how wide an option
                // has to be, and under CRT the name and the count are drawn at opposite ends of that
                // same width - so the text it measures has to include both.
                buttonTexts[i] = buttonText;
                _voteButtons[i].ToolTip = buttonText;

                _voteCounts[i].Visible = StyleNano.CrtUiEnabled;
                _voteButtons[i].TextAlign = StyleNano.CrtUiEnabled ? Label.AlignMode.Left : Label.AlignMode.Center;
                if (StyleNano.CrtUiEnabled)
                {
                    var isOurs = _vote.OurVote == i;

                    // ">" rather than a checkmark: the OSD face is an unknown quantity outside ASCII,
                    // and a missing-glyph box is a worse failure than a plain marker. Un-selected rows
                    // get two spaces so every option's name still starts on the same column.
                    _voteButtons[i].Text = (isOurs ? "> " : "  ") + entry.Text;

                    // Four things change together for the own-vote row - marker, brighter track,
                    // stepped-up fill, wider edge - so no single pixel has to be noticed.
                    _voteButtons[i].StyleBoxOverride = new CmuVoteBarStyleBox
                    {
                        TrackColor = isOurs ? CrtTerminalPalette.Surface2 : CrtTerminalPalette.Surface1,
                        // Not Accent: at full brightness the fill washed out the text on top of it as
                        // the share grew (~1.2:1 and 1:1). Surface4 stays a rung above the non-ours
                        // fill without competing; the edge stripe still carries the accent.
                        FillColor = isOurs ? CrtTerminalPalette.Surface4 : CrtTerminalPalette.Surface3,
                        AccentColor = CrtTerminalPalette.Accent,
                        Fraction = totalVotes > 0 ? entry.Votes / (float) totalVotes : 0f,
                        IsOurVote = isOurs,
                        AccentWidth = isOurs ? 4f : 2f,
                    };
                    _voteButtons[i].Label.FontColorOverride = CrtTerminalPalette.TextBright;

                    if (_voteCounts[i] is { } count)
                    {
                        count.Text = _vote.DisplayVotes ? entry.Votes.ToString() : string.Empty;
                        count.FontColorOverride = CrtTerminalPalette.TextBright;
                    }
                }
                else
                {
                    _voteButtons[i].StyleBoxOverride = null;
                    _voteButtons[i].Label.FontColorOverride = null;
                    _voteButtons[i].Text = buttonText;
                }

                if (_vote.OurVote == i)
                    _voteButtons[i].Pressed = true;
            }

            ReflowOptions(buttonTexts);
        }

        private string[] GetRawOptionTexts()
        {
            var texts = new string[_vote.Entries.Length];
            for (var i = 0; i < _vote.Entries.Length; i++)
            {
                texts[i] = _vote.Entries[i].Text;
            }

            return texts;
        }

        private void ReflowOptions(string[] texts)
        {
            if (texts.Length == 0)
                return;

            var scale = OptionScale;
            var longest = GetLongestTextLine(texts);
            // One column under CRT. The options are bars now, and bars are only comparable when they
            // share a baseline and a width - side by side in three columns they are four unrelated
            // rectangles rather than one chart.
            var columns = StyleNano.CrtUiEnabled ? 1 : GetOptionColumns(texts.Length, longest, scale);
            var minWidth = (int) (GetOptionMinWidth(columns, longest) * scale);
            var minHeight = (int) ((longest > TallOptionTextLength ? CmuPanelMetrics.RowTall : CmuPanelMetrics.Row) * scale);

            if (_optionColumns == columns &&
                _optionMinWidth == minWidth &&
                _optionMinHeight == minHeight)
            {
                return;
            }

            _optionColumns = columns;
            _optionMinWidth = minWidth;
            _optionMinHeight = minHeight;

            VoteOptionsContainer.Columns = columns;

            foreach (var button in _voteButtons)
            {
                button.MinWidth = minWidth;
                button.MinHeight = minHeight;
                button.ClipText = false;
                button.RectClipContent = false;
            }
        }

        private int GetOptionColumns(int optionCount, int longestText, float scale)
        {
            if (optionCount <= 1)
                return 1;

            var preferred = longestText switch
            {
                > VeryWideOptionTextLength => 1,
                > WideOptionTextLength => 2,
                _ => Math.Min(3, optionCount),
            };

            // Clamp against the width actually available. Picking a column count purely from text
            // length is what let the options run past the panel: the popup sets RectClipContent, so
            // a column that doesn't fit is a button with its label sliced off rather than a row that
            // wraps. Width is zero until the first layout pass, so fall back to the preference then
            // and let Resized correct it.
            var available = Width - ContentHorizontalMargin;
            if (available <= 0)
                return preferred;

            var columnWidth = CompactOptionMinWidth * scale + OptionSeparation;
            var fits = (int) ((available + OptionSeparation) / columnWidth);

            return Math.Clamp(fits, 1, preferred);
        }

        private static int GetOptionMinWidth(int columns, int longestText)
        {
            if (columns == 1)
                return Math.Max(SingleOptionMinWidth, 12 * longestText);

            if (longestText > WideOptionTextLength)
                return Math.Max(WideOptionMinWidth, 10 * longestText);

            return CompactOptionMinWidth;
        }

        private static int GetLongestTextLine(string[] texts)
        {
            var longest = 0;
            foreach (var text in texts)
            {
                var lineStart = 0;
                for (var i = 0; i <= text.Length; i++)
                {
                    if (i != text.Length && text[i] != '\n')
                        continue;

                    longest = Math.Max(longest, i - lineStart);
                    lineStart = i + 1;
                }
            }

            return longest;
        }

        private void AttemptFollowVoteEntity()
        {
            if (_targetEntity != null)
            {
                var msg = new GhostWarpToTargetRequestEvent(_targetEntity.Value);
                _net.SendSystemNetworkMessage(msg);
            }
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            // Logger.GetSawmill("content").Debug($"{_gameTiming.ServerTime}, {_vote.StartTime}, {_vote.EndTime}");

            var curTime = _gameTiming.RealTime;
            var timeLeft = _vote.EndTime - curTime;
            if (timeLeft < TimeSpan.Zero)
                timeLeft = TimeSpan.Zero;

            // Round up a second.
            timeLeft = TimeSpan.FromSeconds(Math.Ceiling(timeLeft.TotalSeconds));

            var text = $"{timeLeft:m\\:ss}";
            TimeLeftText.Text = text;
            if (MinimizedContent.Visible)
                MinimizedTimeLeft.Text = text;

            // Same colour the round clock escalates through as it runs down - green, amber, red -
            // just on the text rather than a swapped style class, since these two already carry
            // CrtHeading for their size and a second class competing for the same font-colour
            // property is a tie with no defined winner.
            if (StyleNano.CrtUiEnabled)
            {
                var color = CmuCountdownUrgency.GetColor(timeLeft.TotalSeconds);
                TimeLeftText.FontColorOverride = color;
                MinimizedTimeLeft.FontColorOverride = color;
            }
        }

        private void SetMinimized(bool minimized)
        {
            MainContent.Visible = !minimized;
            MinimizedContent.Visible = minimized;

            if (minimized)
            {
                MinWidth = 280;
                MaxWidth = 400;
                MinimizedTitle.Text = _vote.Title;
            }
            else
            {
                MinWidth = 560;
                MaxWidth = 1280;
            }
        }
    }
}
