using System.Linq;
using System.Numerics;
using Content.Client.Gameplay;
using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Content.Shared.Administration;
using Content.Shared.CCVar;
using Content.Shared.Ghost;
using Content.Shared.Ghost.Systems;
using Content.Shared.Voting;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.State;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Console;
using Robust.Shared.Maths;
using Robust.Shared.Network;
using Robust.Shared.Timing;

namespace Content.Client.Voting.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class VoteCallMenu : BaseWindow
    {
        private const bool CallVoteCreationEnabled = false;

        [Dependency] private IClientConsoleHost _consoleHost = default!;
        [Dependency] private IVoteManager _voteManager = default!;
        [Dependency] private IGameTiming _gameTiming = default!;
        [Dependency] private IClientNetManager _netManager = default!;
        [Dependency] private IEntityManager _entityManager = default!;
        [Dependency] private IEntityNetworkManager _entNetManager = default!;
        [Dependency] private IConfigurationManager _cfg = default!;
        [Dependency] private IStateManager _state = default!;
        [Dependency] private IStylesheetManager _stylesheetManager = default!;

        private VotingSystem _votingSystem;

        public StandardVoteType Type;

        public Dictionary<StandardVoteType, CreateVoteOption> AvailableVoteOptions = new Dictionary<StandardVoteType, CreateVoteOption>()
        {
            { StandardVoteType.Restart, new CreateVoteOption("ui-vote-type-restart", new(), false, null) },
            { StandardVoteType.Preset, new CreateVoteOption("ui-vote-type-gamemode", new(), false, null) },
            { StandardVoteType.Map, new CreateVoteOption("ui-vote-type-map", new(), false, null) },
            { StandardVoteType.Votekick, new CreateVoteOption("ui-vote-type-votekick", new(), true, 0) }
           // { StandardVoteType.Platoon, new CreateVoteOption("ui-vote-type-platoon", new(), false, null) }
        };

        public Dictionary<string, string> VotekickReasons = new Dictionary<string, string>()
        {
            { VotekickReasonType.Raiding.ToString(), Loc.GetString("ui-vote-votekick-type-raiding") },
            { VotekickReasonType.Cheating.ToString(), Loc.GetString("ui-vote-votekick-type-cheating") },
            { VotekickReasonType.Spam.ToString(), Loc.GetString("ui-vote-votekick-type-spamming") }
        };

        public Dictionary<NetUserId, (NetEntity, string)> PlayerList = new();

        public OptionButton? _followDropdown = null;

        public bool IsAllowedVotekick = false;

        public VoteCallMenu()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);
            _votingSystem = _entityManager.System<VotingSystem>();

            ApplyCrtPalette();
            CrtLobbyTheme.Apply(this);
            VoteNotTrustedLabel.Text = Loc.GetString("ui-vote-trusted-users-notice", ("timeReq", _cfg.GetCVar(CCVars.VotekickEligibleVoterDeathtime)));

            foreach (StandardVoteType voteType in Enum.GetValues<StandardVoteType>())
            {
                var option = AvailableVoteOptions[voteType];
                VoteTypeButton.AddItem(Loc.GetString(option.Name), (int)voteType);
            }

            _state.OnStateChanged += OnStateChanged;
            _cfg.OnValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
            _cfg.OnValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
            CloseButton.OnPressed += _ => Close();
            CreateButton.OnPressed += CreatePressed;
            VoteTypeButton.OnItemSelected += VoteTypeSelected;
            FollowButton.OnPressed += FollowSelected;

            SetCallVoteCreationEnabled(CallVoteCreationEnabled);
        }

        protected override void Opened()
        {
            base.Opened();

            _netManager.ClientSendMessage(new MsgVoteMenu());

            _voteManager.CanCallVoteChanged += CanCallVoteChanged;
            _votingSystem.VotePlayerListResponse += UpdateVotePlayerList;
            _votingSystem.RequestVotePlayerList();
        }

        public override void Close()
        {
            base.Close();

            _voteManager.CanCallVoteChanged -= CanCallVoteChanged;
            _votingSystem.VotePlayerListResponse -= UpdateVotePlayerList;
        }

        [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            _cfg.UnsubValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
            _cfg.UnsubValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
        }

        private void OnCrtUiEnabledChanged(bool _)
        {
            ApplyCrtPalette();
            CrtLobbyTheme.Apply(this);
        }

        private void OnCrtUiColorChanged(string _)
        {
            ApplyCrtPalette();
            CrtLobbyTheme.Apply(this);
        }

        private void ApplyCrtPalette()
        {
            Stylesheet = _stylesheetManager.SheetNano;
            RootPanel.PanelOverride = CreatePanelStyleBox();
            OptionsPanel.PanelOverride = CreateInsetStyleBox();
        }

        private void SetCallVoteCreationEnabled(bool enabled)
        {
            CallVoteDisabledLabel.Visible = !enabled;
            VoteTypeButton.Disabled = !enabled;
            VoteOptionsButtonContainer.Visible = enabled;
            FollowButton.Disabled = !enabled;
            CreateButton.Disabled = !enabled;
        }

        private static CrtStyleBox CreatePanelStyleBox()
        {
            return new CrtStyleBox
            {
                BackgroundColor = StyleNano.CrtPanelBackground,
                BorderColor = StyleNano.CrtGreenDim,
                CornerColor = StyleNano.CrtGreen.WithAlpha(0.28f),
                BorderThickness = new Thickness(1),
                CornerLength = 10,
                ContentMarginLeftOverride = 10,
                ContentMarginRightOverride = 10,
                ContentMarginTopOverride = 8,
                ContentMarginBottomOverride = 8
            };
        }

        private static CrtStyleBox CreateInsetStyleBox()
        {
            return new CrtStyleBox
            {
                BackgroundColor = StyleNano.CrtInsetBackground,
                BorderColor = StyleNano.CrtGreenDim,
                CornerColor = StyleNano.CrtGreen.WithAlpha(0.22f),
                BorderThickness = new Thickness(1),
                CornerLength = 8,
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 6,
                ContentMarginBottomOverride = 6
            };
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            UpdateVoteTimeout();
        }

        private void OnStateChanged(StateChangedEventArgs obj)
        {
            if (obj.NewState is not GameplayState)
                return;

            Close();
        }

        private void CanCallVoteChanged(bool obj)
        {
            if (!obj)
                Close();
        }

        private void UpdateVotePlayerList(VotePlayerListResponseEvent msg)
        {
            Dictionary<string, string> optionsList = new();
            Dictionary<NetUserId, (NetEntity, string)> playerList = new();
            foreach ((NetUserId, NetEntity, string) player in msg.Players)
            {
                optionsList.Add(player.Item1.ToString(), player.Item3);
                playerList.Add(player.Item1, (player.Item2, player.Item3));
            }
            if (optionsList.Count == 0)
                optionsList.Add(" ", " ");

            PlayerList = playerList;

            IsAllowedVotekick = !msg.Denied;

            var updatedDropdownOption = AvailableVoteOptions[StandardVoteType.Votekick];
            updatedDropdownOption.Dropdowns = new List<Dictionary<string, string>>() { optionsList, VotekickReasons };
            AvailableVoteOptions[StandardVoteType.Votekick] = updatedDropdownOption;
        }

        private void CreatePressed(BaseButton.ButtonEventArgs obj)
        {
            var typeId = VoteTypeButton.SelectedId;
            var voteType = AvailableVoteOptions[(StandardVoteType)typeId];

            var commandArgs = "";

            if (voteType.Dropdowns == null || voteType.Dropdowns.Count == 0)
            {
                _consoleHost.LocalShell.RemoteExecuteCommand($"createvote {((StandardVoteType)typeId).ToString()}");
            }
            else
            {
                int i = 0;
                foreach(var dropdowns in VoteOptionsButtonContainer.Children)
                {
                    if (dropdowns is OptionButton optionButton && AvailableVoteOptions[(StandardVoteType)typeId].Dropdowns != null)
                    {
                        commandArgs += AvailableVoteOptions[(StandardVoteType)typeId].Dropdowns[i].ElementAt(optionButton.SelectedId).Key + " ";
                        i++;
                    }
                }
                _consoleHost.LocalShell.RemoteExecuteCommand($"createvote {((StandardVoteType)typeId).ToString()} {commandArgs}");
            }

            Close();
        }

        private void UpdateVoteTimeout()
        {
            var typeKey = (StandardVoteType)VoteTypeButton.SelectedId;
            var isAvailable = _voteManager.CanCallStandardVote(typeKey, out var timeout);
            if (!CallVoteCreationEnabled || typeKey == StandardVoteType.Votekick && !IsAllowedVotekick)
                CreateButton.Disabled = true;
            else
                CreateButton.Disabled = !isAvailable;

            VoteTypeTimeoutLabel.Visible = !isAvailable;

            if (!isAvailable)
            {
                if (timeout == TimeSpan.Zero)
                {
                    VoteTypeTimeoutLabel.Text = Loc.GetString("ui-vote-type-not-available");
                }
                else
                {
                    var remaining = timeout - _gameTiming.RealTime;
                    VoteTypeTimeoutLabel.Text = Loc.GetString("ui-vote-type-timeout", ("remaining", remaining.ToString("mm\\:ss")));
                }
            }
        }

        private static void ButtonSelected(OptionButton.ItemSelectedEventArgs obj)
        {
            obj.Button.SelectId(obj.Id);
        }

        private void FollowSelected(Button.ButtonEventArgs obj)
        {
            if (_followDropdown == null)
                return;

            if (_followDropdown.SelectedId >= PlayerList.Count)
                return;

            var netEntity = PlayerList.ElementAt(_followDropdown.SelectedId).Value.Item1;

            var msg = new GhostWarpToTargetRequestEvent(netEntity);
            _entNetManager.SendSystemNetworkMessage(msg);
        }

        private void VoteTypeSelected(OptionButton.ItemSelectedEventArgs obj)
        {
            VoteTypeButton.SelectId(obj.Id);

            VoteNotTrustedLabel.Visible = false;
            if ((StandardVoteType)obj.Id == StandardVoteType.Votekick)
            {
                if (!IsAllowedVotekick)
                {
                    VoteNotTrustedLabel.Visible = true;
                    var updatedDropdownOption = AvailableVoteOptions[StandardVoteType.Votekick];
                    updatedDropdownOption.Dropdowns = new List<Dictionary<string, string>>();
                    AvailableVoteOptions[StandardVoteType.Votekick] = updatedDropdownOption;
                }
                else
                {
                    _votingSystem.RequestVotePlayerList();
                }
            }

            VoteWarningLabel.Visible = AvailableVoteOptions[(StandardVoteType)obj.Id].EnableVoteWarning;
            FollowButton.Visible = false;

            var voteList = AvailableVoteOptions[(StandardVoteType)obj.Id].Dropdowns;

            VoteOptionsButtonContainer.RemoveAllChildren();
            if (voteList != null)
            {
                int i = 0;
                foreach (var voteDropdown in voteList)
                {
                    var optionButton = new OptionButton
                    {
                        HorizontalExpand = true,
                        MinWidth = 280,
                    };
                    CrtLobbyTheme.ApplyToOptionButton(optionButton);
                    int j = 0;
                    foreach (var (key, value) in voteDropdown)
                    {
                        optionButton.AddItem(Loc.GetString(value), j);
                        j++;
                    }
                    VoteOptionsButtonContainer.AddChild(optionButton);
                    optionButton.Visible = true;
                    optionButton.OnItemSelected += ButtonSelected;
                    if (AvailableVoteOptions[(StandardVoteType)obj.Id].FollowDropdownId != null && AvailableVoteOptions[(StandardVoteType)obj.Id].FollowDropdownId == i)
                    {
                        _followDropdown = optionButton;
                        FollowButton.Visible = true;
                    }
                    i++;
                }
            }
        }

        protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        {
            return DragMode.Move;
        }
    }

    [UsedImplicitly, AnyCommand]
    public sealed partial class VoteMenuCommand : LocalizedCommands
    {
        public override string Command => "votemenu";

        public override void Execute(IConsoleShell shell, string argStr, string[] args)
        {
            new VoteCallMenu().OpenCentered();
        }
    }

    public record struct CreateVoteOption
    {
        public string Name;
        public List<Dictionary<string, string>> Dropdowns;
        public bool EnableVoteWarning;
        public int? FollowDropdownId;  // If set, this will enable the Follow button and use the dropdown matching the ID as input.

        public CreateVoteOption(string name, List<Dictionary<string, string>> dropdowns, bool enableVoteWarning, int? followDropdownId)
        {
            Name = name;
            Dropdowns = dropdowns;
            EnableVoteWarning = enableVoteWarning;
            FollowDropdownId = followDropdownId;
        }
    }
}
