- type: job
  abstract: true
  parent: CMJobBase
  id: AU14JobSecurityAndroidBase
  name: au14-job-name-securityandroid
  description: au14-job-description-securityandroid
  playTimeTracker: AU14JobAndroid
  basePlaytimeTracker: true
  setPreference: true
  canBeAntag: false
  whitelisted: true
  whitelistParent: RMCWhitelistMedium
  jobEntity: AU14MobSecurityAndroid
  jobPreviewEntity: AU14MobSecurityAndroidDummy

- type: playTimeTracker
  id: AU14JobAndroid
  isHumanoid: true

- type: startingGear
  id: AU14GearSecurityAndroidBase
  equipment:
    shoes: RMCBootsPMCFilled
