using System.Linq;
using Content.Shared.CMU14.Ambassador;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.Ambassador;

[GenerateTypedNameReferences]
public sealed partial class AmbassadorThirdPartyWindow : DefaultWindow
{
    public event Action<string>? OnCallThirdParty;

    private List<string> _thirdPartyIds = new();
    private Dictionary<string, (string DisplayName, float Cost)> _thirdParties = new();
    private HashSet<string> _calledParties = new();
    private string? _selectedThirdPartyId;

    public AmbassadorThirdPartyWindow()
    {
        RobustXamlLoader.Load(this);

        ThirdPartyList.OnItemSelected += args =>
        {
            if (args.ItemList[args.ItemIndex].Metadata is string id)
                SelectThirdParty(id);
        };

        ThirdPartyList.OnItemDeselected += args =>
        {
            if (args.ItemList[args.ItemIndex].Metadata is string id && id == _selectedThirdPartyId)
                SelectThirdParty(null);
        };

        CallBtn.OnPressed += _ =>
        {
            if (_selectedThirdPartyId is { } id &&
                _thirdParties.ContainsKey(id) &&
                !_calledParties.Contains(id))
            {
                OnCallThirdParty?.Invoke(id);
<<<<<<< HEAD:Content.Client/AU14/Ambassador/AmbassadorThirdPartyWindow.xaml.cs
                StatusLabel.Text = Loc.GetString("au14-ambassador-third-party-requesting"); // RuMC edit
=======
                StatusLabel.Text = Loc.GetString("ambassador-third-party-requesting");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Ambassador/AmbassadorThirdPartyWindow.xaml.cs
            }
        };
    }

    public void UpdateState(AmbassadorThirdPartyBuiState s)
    {
<<<<<<< HEAD:Content.Client/AU14/Ambassador/AmbassadorThirdPartyWindow.xaml.cs
        BudgetLabel.Text = Loc.GetString("au14-ambassador-console-budget", ("amount", s.Budget.ToString("F0"))); // RuMC edit
=======
        BudgetLabel.Text = Loc.GetString("ambassador-console-budget", ("amount", s.Budget.ToString("F0")));
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Ambassador/AmbassadorThirdPartyWindow.xaml.cs

        var newIds = s.CallableParties.Keys.ToList();
        var changed = !_thirdPartyIds.SequenceEqual(newIds) || !_calledParties.SetEquals(s.CalledParties);

        _thirdParties = s.CallableParties;
        _calledParties = s.CalledParties;

        if (changed)
        {
            var previousSelectedKey = _selectedThirdPartyId;

            _thirdPartyIds = newIds;
            ThirdPartyList.Clear();

            if (_thirdPartyIds.Count == 0)
            {
<<<<<<< HEAD:Content.Client/AU14/Ambassador/AmbassadorThirdPartyWindow.xaml.cs
                StatusLabel.Text = Loc.GetString("au14-ambassador-third-party-none-available"); // RuMC edit
                SelectThirdParty(null);
                CostLabel.Text = Loc.GetString("au14-ambassador-third-party-cost-na"); // RuMC edit
=======
                StatusLabel.Text = Loc.GetString("ambassador-third-party-none");
                SelectThirdParty(null);
                CostLabel.Text = Loc.GetString("ambassador-third-party-cost-na");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Ambassador/AmbassadorThirdPartyWindow.xaml.cs
                return;
            }

            StatusLabel.Text = "";

            for (int i = 0; i < _thirdPartyIds.Count; i++)
            {
                var id = _thirdPartyIds[i];
                var info = s.CallableParties[id];
                var name = Loc.GetString(info.DisplayName); // RuMC edit
                var label = _calledParties.Contains(id)
<<<<<<< HEAD:Content.Client/AU14/Ambassador/AmbassadorThirdPartyWindow.xaml.cs
                // RuMC edit start
                    ? Loc.GetString("au14-ambassador-third-party-list-item-called", ("name", name), ("cost", info.Cost.ToString("F0")))
                    : Loc.GetString("au14-ambassador-third-party-list-item", ("name", name), ("cost", info.Cost.ToString("F0")));
                // RuMC edit end
=======
                    ? Loc.GetString(
                        "ambassador-third-party-entry-called",
                        ("name", info.DisplayName),
                        ("cost", info.Cost.ToString("F0")))
                    : Loc.GetString(
                        "ambassador-third-party-entry",
                        ("name", info.DisplayName),
                        ("cost", info.Cost.ToString("F0")));
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Ambassador/AmbassadorThirdPartyWindow.xaml.cs

                ThirdPartyList.Add(new ItemList.Item(ThirdPartyList)
                {
                    Text = label,
                    Metadata = id,
                });
            }

            var restoreIdx = previousSelectedKey != null ? _thirdPartyIds.IndexOf(previousSelectedKey) : -1;
            var selectIdx = restoreIdx >= 0 ? restoreIdx : _thirdPartyIds.FindIndex(id => !_calledParties.Contains(id));
            if (selectIdx < 0)
                selectIdx = 0;

            ThirdPartyList[selectIdx].Selected = true;
            SelectThirdParty(_thirdPartyIds[selectIdx]);
        }
        else
        {
            SelectThirdParty(_selectedThirdPartyId);
        }
    }

    private void SelectThirdParty(string? id)
    {
        _selectedThirdPartyId = id;

        if (id == null || !_thirdParties.TryGetValue(id, out var info))
        {
<<<<<<< HEAD:Content.Client/AU14/Ambassador/AmbassadorThirdPartyWindow.xaml.cs
            // RuMC edit start
            CostLabel.Text = _thirdPartyIds.Count == 0
                ? Loc.GetString("au14-ambassador-third-party-cost-na")
                : Loc.GetString("au14-ambassador-third-party-cost", ("cost", "0"));
            // RuMC edit end
=======
            CostLabel.Text = _thirdPartyIds.Count == 0
                ? Loc.GetString("ambassador-third-party-cost-na")
                : Loc.GetString("ambassador-third-party-cost", ("cost", "0"));
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Ambassador/AmbassadorThirdPartyWindow.xaml.cs
            CallBtn.Disabled = true;
            return;
        }

<<<<<<< HEAD:Content.Client/AU14/Ambassador/AmbassadorThirdPartyWindow.xaml.cs
        CostLabel.Text = Loc.GetString("au14-ambassador-third-party-cost", ("cost", info.Cost.ToString("F0"))); // RuMC edit
=======
        CostLabel.Text = Loc.GetString("ambassador-third-party-cost", ("cost", info.Cost.ToString("F0")));
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Ambassador/AmbassadorThirdPartyWindow.xaml.cs
        CallBtn.Disabled = _calledParties.Contains(id);
    }
}
