using Content.Shared.CMU14.Ambassador;
using Content.Shared.CMU14.ColonyEconomy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.Ambassador;

[GenerateTypedNameReferences]
public sealed partial class AmbassadorConsoleWindow : DefaultWindow
{
    public AmbassadorConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(AmbassadorConsoleBuiState s)
    {
        BudgetLabel.Text = Loc.GetString("ambassador-console-budget", ("amount", s.Budget.ToString("F0")));
        FactionLabel.Text = Loc.GetString("ambassador-console-faction", ("faction", s.FactionName));

        // Economy with prices
        EmbargoStatus.Text = s.EmbargoActive
            ? Loc.GetString("ambassador-console-embargo-active", ("cost", s.EmbargoCostPerMinute.ToString("F0")))
            : Loc.GetString("ambassador-console-embargo-inactive", ("cost", s.EmbargoCostPerMinute.ToString("F0")));
        TradePactStatus.Text = s.TradePactActive
            ? Loc.GetString("ambassador-console-trade-pact-active", ("cost", s.TradePactCostPerMinute.ToString("F0")))
            : Loc.GetString("ambassador-console-trade-pact-inactive", ("cost", s.TradePactCostPerMinute.ToString("F0")));

        // Comms jam with price
        CommsJamStatus.Text = s.CommsJamActive
            ? Loc.GetString("ambassador-console-comms-jam-active", ("cost", s.CommsJamCostPerMinute.ToString("F0")))
            : Loc.GetString("ambassador-console-comms-normal", ("cost", s.CommsJamCostPerMinute.ToString("F0")));

        // Broadcast cost
        BroadcastCostLabel.Text = Loc.GetString("ambassador-console-broadcast-cost", ("cost", s.BroadcastCost.ToString("F0")));

        // Signal with prices
        var signalText = Loc.GetString("ambassador-console-signal-normal");
        if (s.SignalBoostActive)
            signalText = Loc.GetString("ambassador-console-signal-boost-active", ("cost", s.SignalBoostCostPerMinute.ToString("F0")));
        else if (s.SignalJamActive)
            signalText = Loc.GetString("ambassador-console-signal-jam-active", ("cost", s.SignalJamCostPerMinute.ToString("F0")));
        else
            signalText = Loc.GetString(
                "ambassador-console-signal-normal-costs",
                ("boost", s.SignalBoostCostPerMinute.ToString("F0")),
                ("jam", s.SignalJamCostPerMinute.ToString("F0")));
        SignalStatus.Text = signalText;

        // Radar scan button with price
        ScanRadarBtn.Text = Loc.GetString("ambassador-console-scan-radar-cost", ("cost", s.RadarScanCost.ToString("F0")));

        // Economy status
        UpdateEconomyStatus(s.EconomyStatus);

        // Update radar list
        RadarList.RemoveAllChildren();
        if (s.RadarList.Count == 0)
        {
            RadarList.AddChild(new Label { Text = Loc.GetString("ambassador-console-radar-no-data") });
        }
        else
        {
            foreach (var name in s.RadarList)
            {
                RadarList.AddChild(new Label { Text = Loc.GetString("ambassador-console-radar-entry", ("name", name)) });
            }
        }
    }

    private void UpdateEconomyStatus(EconomyStatusState econ)
    {
        EconomyStatusPanel.RemoveAllChildren();
        EconomyStatusPanel.AddChild(new Label
        {
            Text = Loc.GetString("ambassador-console-sales-tax", ("value", econ.SalesTaxPercent.ToString("F0")))
        });
        EconomyStatusPanel.AddChild(new Label
        {
            Text = Loc.GetString("ambassador-console-income-tax", ("value", econ.IncomeTaxPercent.ToString("F0")))
        });
        EconomyStatusPanel.AddChild(new Label
        {
            Text = Loc.GetString("ambassador-console-transit-tariff", ("value", econ.TransitTariffPercent.ToString("F0")))
        });

        if (econ.ActiveEmbargoes.Count > 0)
        {
            EconomyStatusPanel.AddChild(new Label
            {
                Text = Loc.GetString("ambassador-console-active-embargoes", ("values", string.Join(", ", econ.ActiveEmbargoes))),
                StyleClasses = { "Caution" }
            });
        }
        else
        {
            EconomyStatusPanel.AddChild(new Label
            {
                Text = Loc.GetString("ambassador-console-no-embargoes"),
                StyleClasses = { "LabelSubText" }
            });
        }

        if (econ.ActiveTradePacts.Count > 0)
        {
            EconomyStatusPanel.AddChild(new Label
            {
                Text = Loc.GetString("ambassador-console-active-trade-pacts", ("values", string.Join(", ", econ.ActiveTradePacts)))
            });
        }
        else
        {
            EconomyStatusPanel.AddChild(new Label
            {
                Text = Loc.GetString("ambassador-console-no-trade-pacts"),
                StyleClasses = { "LabelSubText" }
            });
        }
    }
}
