- type: job
  parent: RMCJobRibbonBase
  displayWeight: 10
  id: CMUJobColonyPrisonGuard
  name: cmu-colony-name-prison-guard
  description: cmu-colony-description-prison-guard
  roundSide: Civilian
  roundForce: COLONY
  roundRole: ColonyPrisonGuard
  setPreference: true
  startingGear: CMUGearColonyPrisonGuard
  icon: AU14JobIconColonyColonist
  supervisors: cmu-colony-supervisors-colonist
  spawnMenuRoleName: cmu-spawn-role-colony-prison-guard-cmu 
  playTimeTracker: CMUJobColonyPrisonGuard
  ranks:
    RMCRankCivilian: []
  roundComponents:
  - type: Skills
    preset: RMCSkillPresetSurvivorMarshal
  - type: JobPrefix
    prefix: cmu-colony-prefix-prison-guard
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: mp
  accessGroups:
  - Colonist
  - auorbitalmanagement
  - aucmb

- type: startingGear
  id: CMUGearColonyPrisonGuard
  equipment:
    id: AU14IDCardColonyColonist
    jumpsuit: CMJumpsuitLiaisonBlack
    back: CMSatchelSecuritySurvivorFill
    outerClothing: RMCArmorVestWeYa
    ears: RMCHeadsetDistressWeYa
    head: RMCArmorHelmetPMCDark
    gloves: RMCHandsVeteran
    shoes: RMCShoesJackboots

- type: entity
  parent: CMSpawnPointJobBase
  id: CMUSpawnPointColonyPrisonGuard
  name: Spawn Point Colony Prison Guard
  components:
  - type: SpawnPoint
    job_id: CMUJobColonyPrisonGuard
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: CMUJobColonyPrisonGuard
  isHumanoid: true
