- type: job
  parent: RMCJobRibbonBase
  displayWeight: 12
  id: CMUJobColonyReactorTechnician
  name: cmu-colony-name-reactor-technician
  description: cmu-colony-description-reactor-technician
  roundSide: Civilian
  roundForce: COLONY
  roundRole: ColonyReactorTechnician
  setPreference: true
  startingGear: CMUGearColonyReactorTechnician
  icon: AU14JobIconColonyColonist
  supervisors: cmu-colony-supervisors-colonist
  spawnMenuRoleName: cmu-spawn-role-colony-reactor-technician-cmu 
  playTimeTracker: CMUJobColonyReactorTechnician
  ranks:
    RMCRankCivilian: []
  roundComponents:
  - type: Skills
    skills:
      RMCSkillEndurance: 2
      RMCSkillConstruction: 2
      RMCSkillEngineer: 3
  - type: JobPrefix
    prefix: cmu-colony-prefix-reactor-technician
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/CMU14/Interface/cmucolonyblips.rsi
      state: colonist
  accessGroups:
  - Colonist
  - auorbitalmanagement

- type: startingGear
  id: CMUGearColonyReactorTechnician
  equipment:
    jumpsuit: RMCJumpsuitNormCivilianWhiteAlt
    pocket2: RMCWelderIndustrial
    id: AU14IDCardColonyColonist
  storage:
    back:
    - RMCMaskGasSPP

- type: playTimeTracker
  id: CMUJobColonyReactorTechnician
  isHumanoid: true
