# Этот вид белого списка не используется Russian Marine Corps
## legacy/deprecated - do not use
- type: job
  parent: CMJobBase
  id: AU14JobGeneralWhitelist
  playTimeTracker: AU14JobGeneralWhitelist
  whitelisted: true
  hidden: true

- type: playTimeTracker
  id: AU14JobGeneralWhitelist
