using System.Numerics;
using Content.Client.Resources;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;

namespace Content.Client.CMU14.Lobby;

[GenerateTypedNameReferences]
public sealed partial class LobbyLineupSection : Control
{
    [Dependency] private IConfigurationManager _configuration = default!;
    [Dependency] private IResourceCache _resources = default!;
    private readonly Vector2[] _beamVertices = new Vector2[4];
    private Color _accent = Color.White;
    private float _effectRemaining;
    private float _effectDuration;
    private bool _disco;
    private int _fontSize;

    public LobbyLineupSection()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetSection(string name, Color accent, int count, int index)
    {
        _accent = accent;
        Heading.Text = Loc.GetString("cmu-lobby-lineup-section", ("section", name.ToUpperInvariant()), ("count", count));
        Heading.FontColorOverride = accent;
        ToolTip = name + "\n" + Loc.GetString("cmu-lobby-lineup-bay", ("number", (index + 1).ToString("D2")));
    }

    public void PlayTeamEffect(bool disco, float duration)
    {
        _disco = disco;
        _effectRemaining = _effectDuration = duration;
    }

    protected override Vector2 MeasureOverride(Vector2 availableSize)
    {
        base.MeasureOverride(availableSize);
        return Vector2.Zero;
    }

    protected override Vector2 ArrangeOverride(Vector2 finalSize)
    {
        var headingHeight = Math.Min(24, finalSize.Y * 0.18f);
        var fontSize = Math.Clamp((int) (headingHeight * 0.6f), 8, 12);
        if (_fontSize != fontSize)
        {
            _fontSize = fontSize;
            Heading.FontOverride = _resources.GetFont("/Fonts/NotoSans/NotoSans-Regular.ttf", fontSize);
        }
        Heading.Arrange(new UIBox2(6, 0, Math.Max(6, finalSize.X - 6), headingHeight));
        Cards.Arrange(UIBox2.FromDimensions(new Vector2(4, headingHeight), LobbyLineupLayout.FormationSize(finalSize)));
        return finalSize;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        _effectRemaining = Math.Max(0, _effectRemaining - args.DeltaSeconds);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);
        var size = PixelSize;
        var heading = Math.Min(24 * UIScale, size.Y * 0.18f);
        var horizon = size.Y * 0.77f;
        handle.DrawRect(new UIBox2(Vector2.Zero, size), Color.FromHex("#101C22F5"));
        handle.DrawRect(new UIBox2(0, 0, size.X, heading), Color.FromHex("#071016F5"));
        handle.DrawRect(new UIBox2(0, 0, size.X, 2 * UIScale), _accent.WithAlpha(0.85f));
        for (var x = 12f * UIScale; x < size.X; x += 60 * UIScale)
            handle.DrawLine(new(x, heading), new(x, horizon), Color.FromHex("#27353C"));
        handle.DrawRect(new UIBox2(0, horizon, size.X, size.Y), Color.FromHex("#1B2B31"));
        for (var x = -(float) size.X; x < size.X * 2; x += 60 * UIScale)
            handle.DrawLine(new(size.X / 2 + (x - size.X / 2) * 0.35f, horizon), new(x, size.Y), Color.FromHex("#384A50"));
        for (var y = 0.1f; y < 1; y += 0.25f)
            handle.DrawLine(new(0, horizon + (size.Y - horizon) * y), new(size.X, horizon + (size.Y - horizon) * y), Color.FromHex("#384A50"));
        handle.DrawLine(new(0, horizon), new(size.X, horizon), _accent.WithAlpha(0.35f));

        if (_effectRemaining <= 0)
            return;
        var reduced = _configuration.GetCVar(CCVars.ReducedMotion);
        var phase = reduced ? 0 : (_effectDuration - _effectRemaining) * 1.8f;
        var beam = _beamVertices;
        for (var i = 0; i < 3; i++)
        {
            var color = !_disco ? _accent : i == 0 ? Color.Cyan : i == 1 ? Color.Magenta : Color.FromHex("#FFCE69");
            var top = size.X * (i + 1) / 4;
            var bottom = top + MathF.Sin(phase + i * 2) * size.X * 0.3f;
            beam[0] = new(top - 2 * UIScale, heading);
            beam[1] = new(top + 2 * UIScale, heading);
            beam[2] = new(bottom + size.X * 0.16f, size.Y);
            beam[3] = new(bottom - size.X * 0.16f, size.Y);
            handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, beam, color.WithAlpha(0.11f * Math.Min(1, _effectRemaining)));
        }
    }
}
