- type: loadout
  id: WebbingSurgicalBlueAU14
  inhand:
  - CMWebbingSurgicalBlue

- type: loadout
  id: WebbingSurgicalGreenCMU14
  inhand:
  - CMWebbingSurgicalGreen

- type: loadout
  id: DropSurgicalGreenCMU14
  inhand:
  - CMU14DropSurgicalGreen

- type: loadout
  id: DropSurgicalBlueCMU14
  inhand:
  - CMU14DropSurgicalBlue

- type: loadout
  id: DropSurgicalBlackCMU14
  inhand:
  - CMU14DropSurgicalBlack

- type: loadout
  id: ToolWebbingFilledAU14
  inhand:
  - RMCToolWebbingFilled

- type: loadout
  id: WebbingBlackAU14
  inhand:
  - CMWebbingBlack

- type: loadout
  id: WebbingBrownAU14
  inhand:
  - CMWebbingBrown
