- type: job
  abstract: true
  parent: AU14JobWorkingJoeBase
  id: AU14JobGOVFORWorkingJoeBase
  roundSide: Govfor
  roundForce: GOVFOR
  roundRole: WorkingJoe
  roundProfiles:
  - AU14RoundJobProfileWorkingJoe
  icon: "AU14JobIconGovWorkingJoe"
  spawnMenuRoleName: cmu-spawn-role-working-joe-govfor 
  supervisors: au14-job-supervisors-workingjoe-military
  usePlayerProfile: false
  jobEntity: AU14MobWorkingJoeGOVFOR
  displayWeight: -2
  accessGroups:
  - AU14GovforCommand
  - AUPrisonStaff
  - auwy
  roundComponents:
  - type: AU14CallsignRole
    category: SYNTH

- type: job
  abstract: true
  parent: AU14JobWorkingJoeBase
  id: AU14JobOPFORWorkingJoeBase
  roundSide: Opfor
  roundForce: OPFOR
  roundRole: WorkingJoe
  roundProfiles:
  - AU14RoundJobProfileWorkingJoe
  icon: "AU14JobIconOPFORWorkingJoe"
  spawnMenuRoleName: cmu-spawn-role-working-joe-opfor
  supervisors: au14-job-supervisors-workingjoe-military
  usePlayerProfile: false
  jobEntity: AU14MobWorkingJoeOPFOR
  displayWeight: -2
  accessGroups:
  - AU14OpforCommand
  - AUPrisonStaff
  - auwy
  roundComponents:
  - type: AU14CallsignRole
    category: SYNTH

- type: job
  parent: AU14JobGOVFORWorkingJoeBase
  id: AU14JobGOVFORWorkingJoe
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
    - NoEnglish
    - CMUProstheticLeftArm
    - CMUProstheticRightArm
    - CMUProstheticLeftLeg
    - CMUProstheticRightLeg
    - SlowRunner
    - Anemic
- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORWorkingJoe
  name: Spawn Point Working Joe (GOVFOR)
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORWorkingJoe
  - type: Sprite
    state: syn_spawn

- type: job
  parent: AU14JobOPFORWorkingJoeBase
  id: AU14JobOPFORWorkingJoe
  hidden: true
  requirements:
  - !type:RoleTimeRequirement
    role: AU14JobGOVFORAuxSupportSynth
    time: 9000 # 2.5 hours
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
    - SlowRunner
    - Anemic

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointOPFORWorkingJoe
  name: Spawn Point Working Joe (OPFOR)
  components:
  - type: SpawnPoint
    job_id: AU14JobOPFORWorkingJoe
  - type: Sprite
    state: syn_spawn
