- type: job
<<<<<<< HEAD:Resources/Prototypes/_CMU14/Roles/CLF/AU14JobCLFCellLeader.yml
  parent: RMCJobRibbonBase # RuCM замена медалей на ленточки для колонистов
=======
  parent: RMCJobRibbonBase
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Resources/Prototypes/CMU14/Roles/CLF/AU14JobCLFCellLeader.yml
  id: AU14JobCLFCellLeader
  roundSide: ThirdParty
  roundForce: CLF
  roundRole: CLFCellLeader
  roundComponents:
  - type: AU14CallsignRole
    suffix: "6"
    commandElement: true
  - type: NpcFactionMember
    factions:
    - AUColonist
    - CLF
  - type: CLFMember
    statusIcon: CLFFactionLeader
  - type: ANPRCRadioUser
  - type: ANPRCCryptoAuthority
  - type: Skills
    skills:
      RMCSkillCqc: 2
      RMCSkillConstruction: 2
      RMCSkillEndurance: 2
      RMCSkillEngineer: 2
      RMCSkillFirearms: 2
      RMCSkillFireman: 2
      RMCSkillIntel: 2
      RMCSkillJtac: 4
      RMCSkillLeadership: 3
      RMCSkillMedical: 1
      RMCSkillNavigations: 1
      RMCSkillOverwatch: 1
      RMCSkillPolice: 1
      RMCSkillPowerLoader: 1
      RMCSkillSurgery: 1
      RMCSkillVehicles: 1
      RMCSkillSpecialistWeapons: 1
  - type: JobPrefix
    prefix: au14-job-prefix-clfcellleader
  - type: StartingMindRole
    mindRole: MindRoleCLFLeader
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/CMU14/Interface/au14colonyjobicons.rsi
      state: colonist
  - type: ShowMarineIcons
    factions:
    - CLF
  - type: FactionLanguageLeader
    factionTag: CLF
  - type: MarineOrders

  name: au14-job-name-clfcellleader
  description: au14-job-description-clfcellleader
  setPreference: true
  ignoreAllegiance: true
  playTimeTracker: AU14JobCLFCellLeader
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5 hours
  - !type:TraitsRequirement
    inverted: true
    traits:
    - NonResuscitable
    - Epilepsy
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCLFCellLeader
  icon: RMCJobIconCLFCellCommander
  hasIcon: false
  requireAdminNotify: true
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-clfcellleader
  spawnMenuRoleName: cmu-spawn-role-clf-cell-leader-cmu 
  accessGroups:
  - Colonist
  roleWeight: 0.25
  weight: 10 # priority role

- type: startingGear
  id: AU14GearCLFCellLeader
  equipment:
    outerClothing: AU14ExternalWebbing
    gloves: RMCHandsVeteranSPP
    shoes: RMCScoutShoes
    neck: RMCCLFCellLeaderArmband
    head: AU14CivBallCapBlack
    id: AU14IDCardCLFCivilian
    eyes: RMCGlassesAviators
    pocket1: AU14StampCLFCell
  inhand:
  - AU14HeavyCellKit
  - AU14CLFHeadset
  storage:
    back:
    - ANPRCFillCardCLF
    - AU14CLFStandingOrdersPad

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCLFCellLeader
  name: Spawn Point CLF Cell Leader
  components:
  - type: SpawnPoint
    job_id: AU14JobCLFCellLeader
  - type: Sprite
    state: syn_spawn
  - type: SafehouseMarker

- type: playTimeTracker
  id: AU14JobCLFCellLeader
  isHumanoid: true

- type: roleLoadout
  id: JobAU14JobCLFCellLeader
  points: 7
  groups:
  - CivSatchelAU14
  - CivFootwearAU14
  - CivJumpsuitAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC
  - EyewearRMC
  - MasksRMC
  - HeadwearCLFAU14
