- type: job
<<<<<<< HEAD:Resources/Prototypes/_CMU14/Roles/CLF/AU14JobCLFRadioOperator.yml
  parent: RMCJobRibbonBase # RuCM замена медалей на ленточки для колонистов
=======
  parent: RMCJobRibbonBase
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Resources/Prototypes/CMU14/Roles/CLF/AU14JobCLFRadioOperator.yml
  id: AU14JobCLFRadioOperator
  roundSide: ThirdParty
  roundForce: CLF
  roundRole: CLFRadioOperator
  roundComponents:
  - type: AU14CallsignRole
    suffix: ROMEO
  - type: NpcFactionMember
    factions:
    - AUColonist
    - CLF
  - type: CLFMember
  - type: ANPRCRadioUser
  - type: Skills
    skills:
      RMCSkillEndurance: 1
      RMCSkillFirearms: 2
      RMCSkillConstruction: 2
      RMCSkillEngineer: 2
      RMCSkillFireman: 1
      RMCSkillJtac: 4
      RMCSkillLeadership: 1
      RMCSkillIntel: 1
      RMCSkillVehicles: 1
      RMCSkillPolice: 1
  - type: JobPrefix
    prefix: au14-job-prefix-clfradiooperator
  - type: StartingMindRole
    mindRole: MindRoleCLFGuerrilla
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/CMU14/Interface/au14colonyjobicons.rsi
      state: colonist
  - type: ShowMarineIcons
    factions:
    - CLF
  - type: FactionLanguageMember
    factionTag: CLF
  - type: MarineOrders

  name: au14-job-name-clfradiooperator
  description: au14-job-description-clfradiooperator
  setPreference: true
  ignoreAllegiance: true
  playTimeTracker: AU14JobCLFRadioOperator
  basePlaytimeTracker: true
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - NonResuscitable
    - Epilepsy
    - NoEnglish
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCLFRadioOperator
  icon: "RMCJobIconCLFSoldier"
  hasIcon: false
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-clflrs
<<<<<<< HEAD:Resources/Prototypes/_CMU14/Roles/CLF/AU14JobCLFRadioOperator.yml
  spawnMenuRoleName: Радиооператор КОФ (CMU)
=======
  spawnMenuRoleName: cmu-spawn-role-clf-radio-operator-cmu 
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Resources/Prototypes/CMU14/Roles/CLF/AU14JobCLFRadioOperator.yml
  accessGroups:
  - Colonist
  roleWeight: 0.25

- type: startingGear
  id: AU14GearCLFRadioOperator
  equipment:
    id: AU14IDCardCLFCivilian
    pocket1: ANPRCFreqCardCLF
  inhand:
  - AU14CLFHeadset

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCLFRadioOperator
  name: точка появления радиооператора КОФ
  components:
  - type: SpawnPoint
    job_id: AU14JobCLFRadioOperator
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCLFRadioOperator
  isHumanoid: true

- type: roleLoadout
  id: JobAU14JobCLFRadioOperator
  points: 7
  groups:
  - CivSatchelAU14
  - CivFootwearAU14
  - CivHatsAU14
  - CivGlassesAU14
  - CivJumpsuitAU14
  - CivJacketAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC
