// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 wray-git
// SPDX-License-Identifier: AGPL-3.0-only
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Content.Client.CMU14.UI;
using Content.Client.Construction;
using Content.Shared.CMU14.Construction.CustomConstruction;
using Content.Shared.Construction.Prototypes;
using Content.Shared.Item;
using Content.Shared.Stacks;
using Robust.Client.AutoGenerated;
using Robust.Shared.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.CMU14.Construction.CustomConstruction;

/// <summary>
/// The "drastically improved" add/change-recipe editor: spawnlist + category dropdowns (each with an
/// "Add new…" option; a new spawnlist is confirmed with a button, then the category list updates to
/// that spawnlist), plus a step builder. Materials are chosen from a dropdown of common materials with
/// a "Custom" stack-id field that is validated. Submitting fires <see cref="OnSubmit"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ConstructionEditorWindow : DefaultWindow
{
    // Sentinel option id meaning "Add new…" / "Custom". Large positive: OptionButton treats negatives
    // (e.g. -1) as "no selection", which silently drops the value.
    private const int CustomId = 1_000_000;
    private const string DefaultSpawnlist = "AU14";

    // Material dropdown: friendly label → CM material stack id. These are the stacks the construction
    // menu's held sheets actually provide (see _RMC14/Entities/Objects/Materials/Sheets). Vanilla ids
    // like "Steel"/"Glass" index fine but can never be satisfied by the menu's sheets, so we don't use them.
    private static readonly (string LabelKey, string Stack)[] CommonMaterials =
    {
        ("construction-editor-common-material-metal", "CMSteel"),
        ("construction-editor-common-material-plasteel", "CMPlasteel"),
        ("construction-editor-common-material-glass", "CMGlass"),
        ("construction-editor-common-material-reinforced-glass", "CMGlassReinforced"),
        ("construction-editor-common-material-phoron-glass", "CMGlassPhoron"),
        ("construction-editor-common-material-phoron", "CMPhoron"),
        ("construction-editor-common-material-wood", "RMCWood"),
        ("construction-editor-common-material-aluminum", "RMCAluminum"),
        ("construction-editor-common-material-plastic", "RMCPlastic"),
        ("construction-editor-common-material-cardboard", "RMCSheetCardboard"),
    };

    // Tool dropdown: display label → construction tool quality id.
    private static readonly (string LabelKey, string Quality)[] Tools =
    {
        ("construction-editor-tool-wrench", "Anchoring"),
        ("construction-editor-tool-welder", "Welding"),
        ("construction-editor-tool-screwdriver", "Screwing"),
        ("construction-editor-tool-crowbar", "Prying"),
        ("construction-editor-tool-wirecutter", "Cutting"),
    };

    public event Action<SubmitCustomConstructionEditorEvent>? OnSubmit;

    /// <summary>Fired (spawnlist, category) when the admin confirms a bulk removal of a whole group.</summary>
    public event Action<(string spawnlist, string category)>? OnRemoveGroup;

    private readonly IPrototypeManager _prototype;
    private readonly IComponentFactory _componentFactory;

    private string _protoId = string.Empty;
    private string _entryKey = string.Empty;
    private readonly List<CustomConstructionStepData> _steps = new();
    private readonly List<CustomConstructionStepData> _deconstructSteps = new();
    private readonly List<string> _spawnlistValues = new();
    private readonly List<string> _categoryValues = new();

    // spawnlist → categories present in it (for the spawnlist-scoped category dropdown).
    private readonly Dictionary<string, SortedSet<string>> _categoriesBySpawnlist = new();

    public ConstructionEditorWindow()
    {
        RobustXamlLoader.Load(this);
        _prototype = IoCManager.Resolve<IPrototypeManager>();
        _componentFactory = IoCManager.Resolve<IComponentFactory>();

        SpawnlistDropdown.OnItemSelected += args =>
        {
            SpawnlistDropdown.SelectId(args.Id);
            var addingNew = args.Id == CustomId;
            NewSpawnlistRow.Visible = addingNew;

            // For an existing spawnlist, refresh categories immediately. For a new one, wait for Confirm.
            if (!addingNew && _spawnlistValues.Count > args.Id)
                RefreshCategories(_spawnlistValues[args.Id], string.Empty);
        };
        ConfirmSpawnlistButton.OnPressed += _ =>
        {
            var name = NewSpawnlistEdit.Text.Trim();
            if (name.Length == 0)
                return;
            // A brand-new spawnlist has no categories yet.
            RefreshCategories(name, string.Empty);
        };

        for (var i = 0; i < CommonMaterials.Length; i++)
            MaterialDropdown.AddItem(Loc.GetString(CommonMaterials[i].LabelKey), i);
        // Custom materials are added via the "+Custom Material" entity picker below, not a dropdown entry.
        MaterialDropdown.OnItemSelected += args => MaterialDropdown.SelectId(args.Id);

        CategoryDropdown.OnItemSelected += args =>
        {
            CategoryDropdown.SelectId(args.Id);
            NewCategoryEdit.Visible = args.Id == CustomId;
        };

        for (var i = 0; i < Tools.Length; i++)
            ToolDropdown.AddItem(Loc.GetString(Tools[i].LabelKey), i);
        ToolDropdown.OnItemSelected += args => ToolDropdown.SelectId(args.Id);

        // Deconstruction tool dropdown reuses the same tool list; default to the crowbar (the classic
        // deconstruct tool) so the common case is one click.
        for (var i = 0; i < Tools.Length; i++)
            DeconstructToolDropdown.AddItem(Loc.GetString(Tools[i].LabelKey), i);
        DeconstructToolDropdown.OnItemSelected += args => DeconstructToolDropdown.SelectId(args.Id);
        var crowbarIndex = Array.FindIndex(Tools, t => t.Quality == "Prying");
        DeconstructToolDropdown.SelectId(crowbarIndex >= 0 ? crowbarIndex : 0);

        AddMaterialButton.OnPressed += _ => AddMaterialStep();
        AddToolButton.OnPressed += _ => AddToolStep();
        PickEntityMaterialButton.OnPressed += _ => PickEntityStep(CustomConstructionStepKind.EntityMaterial);
        PickEntityToolButton.OnPressed += _ => PickEntityStep(CustomConstructionStepKind.EntityTool);
        RemoveStepButton.OnPressed += _ => RemoveLastStep();
        ClearStepsButton.OnPressed += _ => ClearSteps();

        AddDeconstructToolButton.OnPressed += _ => AddDeconstructToolStep();
        PickDeconstructEntityToolButton.OnPressed += _ => PickDeconstructEntityStep();
        RemoveDeconstructStepButton.OnPressed += _ => RemoveLastDeconstructStep();
        ClearDeconstructStepsButton.OnPressed += _ => ClearDeconstructSteps();

        OkButton.OnPressed += _ => Submit();
        CancelButton.OnPressed += _ => Close();

        RemoveGroupButton.OnPressed += _ => ArmGroupRemoval();
        RemoveGroupConfirmButton.OnPressed += _ => ConfirmGroupRemoval();

        ApplyGmodStyle();
    }

    /// <summary>Skins the editor to match the improved construction menu (dark panel, accent headers, flat buttons).</summary>
    private void ApplyGmodStyle()
    {
        RootPanel.PanelOverride = GmodStyle.Panel(GmodStyle.PanelBg);

        // The dropdowns and every action button get the flat hover look; OK is tinted as the primary action.
        GmodStyle.Modernize(SpawnlistDropdown);
        GmodStyle.Modernize(CategoryDropdown);
        GmodStyle.Modernize(MaterialDropdown);
        GmodStyle.Modernize(ToolDropdown);
        GmodStyle.Modernize(ConfirmSpawnlistButton);
        GmodStyle.Modernize(AddMaterialButton);
        GmodStyle.Modernize(AddToolButton);
        GmodStyle.Modernize(PickEntityMaterialButton);
        GmodStyle.Modernize(PickEntityToolButton);
        GmodStyle.Modernize(RemoveStepButton);
        GmodStyle.Modernize(ClearStepsButton);
        GmodStyle.Modernize(DeconstructToolDropdown);
        GmodStyle.Modernize(AddDeconstructToolButton);
        GmodStyle.Modernize(PickDeconstructEntityToolButton);
        GmodStyle.Modernize(RemoveDeconstructStepButton);
        GmodStyle.Modernize(ClearDeconstructStepsButton);
        GmodStyle.Modernize(OkButton, baseBg: GmodStyle.RowSelected, selectedBg: GmodStyle.RowSelected);
        GmodStyle.Modernize(CancelButton);

        GmodStyle.RecolorKeyLabels(RootPanel);
        MaterialWarning.FontColorOverride = Color.FromHex("#FF6E6E");
    }

    public void Populate(OpenCustomConstructionEditorEvent ev)
    {
        _protoId = ev.ProtoId;
        _entryKey = ev.EntryKey;
        Title = Loc.GetString(ev.IsEdit ? "construction-editor-title-edit" : "construction-editor-title-add");
        ItemLabel.Text = ev.ItemName;

        BuildCategoryMap();
        MergeServerCategories(ev.AvailableCategoriesBySpawnlist);
        PopulateSpawnlists(ev.AvailableSpawnlists, ev.Spawnlist);
        RefreshCategories(ev.Spawnlist, ev.Category);

        _steps.Clear();
        _steps.AddRange(ev.Steps);
        RefreshSteps();
        MaterialWarning.Visible = false;

        _deconstructSteps.Clear();
        _deconstructSteps.AddRange(ev.DeconstructSteps);
        RefreshDeconstructSteps();

        // The deconstruction-steps section is always shown (it is most meaningful for structures, but the user
        // wants it visible on every generator menu by default). The server ignores it for in-hand items.

        HealthEdit.Text = ev.Health > 0 ? ev.Health.ToString() : string.Empty;
    }

    private void BuildCategoryMap()
    {
        _categoriesBySpawnlist.Clear();
        foreach (var proto in _prototype.EnumeratePrototypes<ConstructionPrototype>())
        {
            if (string.IsNullOrEmpty(proto.Category))
                continue;

            var spawnlist = string.IsNullOrEmpty(proto.Spawnlist) ? DefaultSpawnlist : proto.Spawnlist;
            if (!_categoriesBySpawnlist.TryGetValue(spawnlist, out var set))
            {
                set = new SortedSet<string>(StringComparer.InvariantCulture);
                _categoriesBySpawnlist[spawnlist] = set;
            }
            set.Add(ConstructionLocalization.LocalizeOrRaw(proto.Category));
        }
    }

    /// <summary>
    /// Folds in categories the server read from generated entry files. These cover spawnlists/categories
    /// created in-game whose prototypes aren't loaded yet, so they wouldn't appear from <see cref="BuildCategoryMap"/>.
    /// </summary>
    private void MergeServerCategories(Dictionary<string, List<string>> categoriesBySpawnlist)
    {
        foreach (var (spawnlist, categories) in categoriesBySpawnlist)
        {
            if (string.IsNullOrEmpty(spawnlist))
                continue;

            if (!_categoriesBySpawnlist.TryGetValue(spawnlist, out var set))
            {
                set = new SortedSet<string>(StringComparer.InvariantCulture);
                _categoriesBySpawnlist[spawnlist] = set;
            }

            foreach (var category in categories)
            {
                if (!string.IsNullOrEmpty(category))
                    set.Add(category);
            }
        }
    }

    private void PopulateSpawnlists(List<string> available, string current)
    {
        SpawnlistDropdown.Clear();
        _spawnlistValues.Clear();

        if (!available.Contains(current))
            available.Insert(0, current);

        for (var i = 0; i < available.Count; i++)
        {
            SpawnlistDropdown.AddItem(available[i], i);
            _spawnlistValues.Add(available[i]);
        }

        SpawnlistDropdown.AddItem(Loc.GetString("construction-editor-add-new"), CustomId);

        var sel = available.IndexOf(current);
        SpawnlistDropdown.SelectId(sel >= 0 ? sel : 0);
        NewSpawnlistRow.Visible = false;
    }

    /// <summary>Repopulates the category dropdown with the categories present in <paramref name="spawnlist"/>.</summary>
    private void RefreshCategories(string spawnlist, string current)
    {
        CategoryDropdown.Clear();
        _categoryValues.Clear();

        var categories = new SortedSet<string>(StringComparer.InvariantCulture);
        if (_categoriesBySpawnlist.TryGetValue(spawnlist, out var existing))
            categories.UnionWith(existing);
        if (!string.IsNullOrEmpty(current))
            categories.Add(current);

        var i = 0;
        foreach (var category in categories)
        {
            CategoryDropdown.AddItem(category, i);
            _categoryValues.Add(category);
            i++;
        }

        CategoryDropdown.AddItem(Loc.GetString("construction-editor-add-new"), CustomId);

        var sel = _categoryValues.IndexOf(current);
        if (sel >= 0)
        {
            CategoryDropdown.SelectId(sel);
            NewCategoryEdit.Visible = false;
        }
        else
        {
            // No matching category — default to "Add new…" so the admin names one.
            CategoryDropdown.SelectId(CustomId);
            NewCategoryEdit.Visible = true;
            if (!string.IsNullOrEmpty(current))
                NewCategoryEdit.Text = current;
        }
    }

    private void AddMaterialStep()
    {
        var sel = MaterialDropdown.SelectedId;
        var material = sel >= 0 && sel < CommonMaterials.Length ? CommonMaterials[sel].Stack : string.Empty;

        if (material.Length == 0)
            return;

        // Validate against real stack prototypes; warn instead of creating a recipe that can't build.
        if (!_prototype.HasIndex<StackPrototype>(material))
        {
            MaterialWarning.Text = Loc.GetString("construction-editor-material-notfound", ("material", material));
            MaterialWarning.Visible = true;
            return;
        }

        MaterialWarning.Visible = false;

        if (!int.TryParse(AmountEdit.Text.Trim(), out var amount) || amount < 1)
            amount = 1;
        if (!float.TryParse(MatDoAfterEdit.Text.Trim(), NumberStyles.Float, CultureInfo.InvariantCulture, out var doAfter) || doAfter <= 0)
            doAfter = 1f;

        _steps.Add(new CustomConstructionStepData { Kind = CustomConstructionStepKind.Material, Value = material, Amount = amount, DoAfter = doAfter });
        AmountEdit.Text = string.Empty;
        MatDoAfterEdit.Text = string.Empty;
        RefreshSteps();
    }

    private void AddToolStep()
    {
        var idx = ToolDropdown.SelectedId;
        if (idx < 0 || idx >= Tools.Length)
            idx = 0;

        if (!float.TryParse(ToolDoAfterEdit.Text.Trim(), NumberStyles.Float, CultureInfo.InvariantCulture, out var doAfter) || doAfter <= 0)
            doAfter = 1f;

        _steps.Add(new CustomConstructionStepData { Kind = CustomConstructionStepKind.Tool, Value = Tools[idx].Quality, Amount = 0, DoAfter = doAfter });
        ToolDoAfterEdit.Text = string.Empty;
        RefreshSteps();
    }

    /// <summary>Opens the entity selector and adds a custom material/tool step for the chosen prototype. Uses the
    /// dedicated amount/seconds boxes on the custom row (amount only applies to consumed materials), so a custom
    /// material/tool gets a set count and do-after just like the dropdown steps.</summary>
    private void PickEntityStep(CustomConstructionStepKind kind)
    {
        var isMaterial = kind == CustomConstructionStepKind.EntityMaterial;

        // Capture the amount/duration now, before the selector takes focus.
        var amount = isMaterial && int.TryParse(CustomAmountEdit.Text.Trim(), out var a) && a > 0 ? a : 1;
        var doAfter = float.TryParse(CustomDoAfterEdit.Text.Trim(), NumberStyles.Float, CultureInfo.InvariantCulture, out var d) && d > 0 ? d : 1f;

        var selector = new EntitySelectorWindow();
        selector.OnEntitySelected += id =>
        {
            if (string.IsNullOrEmpty(id))
                return;

            _steps.Add(new CustomConstructionStepData { Kind = kind, Value = id, Amount = amount, DoAfter = doAfter });
            CustomAmountEdit.Text = string.Empty;
            CustomDoAfterEdit.Text = string.Empty;
            RefreshSteps();
        };
        selector.OpenCentered();
    }

    private void RemoveLastStep()
    {
        if (_steps.Count == 0)
            return;
        _steps.RemoveAt(_steps.Count - 1);
        RefreshSteps();
    }

    private void ClearSteps()
    {
        _steps.Clear();
        RefreshSteps();
    }

    private void RefreshSteps()
    {
        StepsList.Clear();
        foreach (var step in _steps)
        {
            var text = step.Kind switch
            {
                CustomConstructionStepKind.Tool =>
                    Loc.GetString("construction-editor-step-tool", ("tool", step.Value), ("sec", step.DoAfter)),
                CustomConstructionStepKind.EntityMaterial =>
                    Loc.GetString("construction-editor-step-entity-material", ("amount", step.Amount), ("entity", step.Value), ("sec", step.DoAfter)),
                CustomConstructionStepKind.EntityTool =>
                    Loc.GetString("construction-editor-step-entity-tool", ("entity", step.Value), ("sec", step.DoAfter)),
                _ =>
                    Loc.GetString("construction-editor-step-material", ("amount", step.Amount), ("material", step.Value), ("sec", step.DoAfter)),
            };
            StepsList.AddItem(text, null, false);
        }
    }

    // -------------------------------------------------------------------------
    // Deconstruction steps (tools only - the material refund is auto-derived from the build steps)
    // -------------------------------------------------------------------------

    private void AddDeconstructToolStep()
    {
        var idx = DeconstructToolDropdown.SelectedId;
        if (idx < 0 || idx >= Tools.Length)
            idx = 0;

        if (!float.TryParse(DeconstructDoAfterEdit.Text.Trim(), NumberStyles.Float, CultureInfo.InvariantCulture, out var doAfter) || doAfter <= 0)
            doAfter = 2f;

        _deconstructSteps.Add(new CustomConstructionStepData { Kind = CustomConstructionStepKind.Tool, Value = Tools[idx].Quality, Amount = 0, DoAfter = doAfter });
        DeconstructDoAfterEdit.Text = string.Empty;
        RefreshDeconstructSteps();
    }

    /// <summary>Opens the entity selector and adds a custom (held-not-consumed) tool step to the deconstruction list.</summary>
    private void PickDeconstructEntityStep()
    {
        var selector = new EntitySelectorWindow();
        selector.OnEntitySelected += id =>
        {
            if (string.IsNullOrEmpty(id))
                return;

            _deconstructSteps.Add(new CustomConstructionStepData { Kind = CustomConstructionStepKind.EntityTool, Value = id, Amount = 0, DoAfter = 2f });
            RefreshDeconstructSteps();
        };
        selector.OpenCentered();
    }

    private void RemoveLastDeconstructStep()
    {
        if (_deconstructSteps.Count == 0)
            return;
        _deconstructSteps.RemoveAt(_deconstructSteps.Count - 1);
        RefreshDeconstructSteps();
    }

    private void ClearDeconstructSteps()
    {
        _deconstructSteps.Clear();
        RefreshDeconstructSteps();
    }

    private void RefreshDeconstructSteps()
    {
        DeconstructStepsList.Clear();
        foreach (var step in _deconstructSteps)
        {
            var text = step.Kind == CustomConstructionStepKind.EntityTool
                ? Loc.GetString("construction-editor-step-entity-tool", ("entity", step.Value), ("sec", step.DoAfter))
                : Loc.GetString("construction-editor-step-tool", ("tool", step.Value), ("sec", step.DoAfter));
            DeconstructStepsList.AddItem(text, null, false);
        }
    }

    private void Submit()
    {
        var spawnlist = SpawnlistDropdown.SelectedId == CustomId
            ? NewSpawnlistEdit.Text.Trim()
            : _spawnlistValues.Count > SpawnlistDropdown.SelectedId ? _spawnlistValues[SpawnlistDropdown.SelectedId] : string.Empty;

        var category = CategoryDropdown.SelectedId == CustomId
            ? NewCategoryEdit.Text.Trim()
            : _categoryValues.Count > CategoryDropdown.SelectedId ? _categoryValues[CategoryDropdown.SelectedId] : string.Empty;

        OnSubmit?.Invoke(new SubmitCustomConstructionEditorEvent
        {
            ProtoId = _protoId,
            EntryKey = _entryKey,
            Spawnlist = spawnlist,
            Category = category,
            Steps = new List<CustomConstructionStepData>(_steps),
            DeconstructSteps = new List<CustomConstructionStepData>(_deconstructSteps),
            Health = int.TryParse(HealthEdit.Text.Trim(), out var hp) && hp > 0 ? hp : 0,
        });

        Close();
    }

    // -------------------------------------------------------------------------
    // Danger zone: bulk-remove the selected spawnlist/category (gated + delayed).
    // -------------------------------------------------------------------------

    private (string Spawnlist, string Category) CurrentGroup()
    {
        var spawnlist = SpawnlistDropdown.SelectedId == CustomId
            ? NewSpawnlistEdit.Text.Trim()
            : _spawnlistValues.Count > SpawnlistDropdown.SelectedId ? _spawnlistValues[SpawnlistDropdown.SelectedId] : string.Empty;
        var category = CategoryDropdown.SelectedId == CustomId
            ? NewCategoryEdit.Text.Trim()
            : _categoryValues.Count > CategoryDropdown.SelectedId ? _categoryValues[CategoryDropdown.SelectedId] : string.Empty;
        return (spawnlist, category);
    }

    private void ArmGroupRemoval()
    {
        // The destructive bulk removal must be explicitly acknowledged.
        if (!RemoveIncludeAllCheck.Pressed)
        {
            RemoveWarningLabel.Visible = true;
            RemoveWarningLabel.FontColorOverride = Color.FromHex("#FFD24C");
            RemoveWarningLabel.Text = Loc.GetString("construction-editor-remove-need-check");
            return;
        }

        var (spawnlist, category) = CurrentGroup();
        if (string.IsNullOrEmpty(spawnlist))
            return;

        // Bright warning for 3 seconds before the Confirm button arms - a deliberate speed bump.
        RemoveWarningLabel.Visible = true;
        RemoveWarningLabel.FontColorOverride = Color.FromHex("#FF3030");
        RemoveWarningLabel.Text = Loc.GetString("construction-editor-remove-warning", ("spawnlist", spawnlist), ("category", category));
        RemoveGroupButton.Disabled = true;
        RemoveGroupConfirmButton.Visible = true;
        RemoveGroupConfirmButton.Disabled = true;

        Timer.Spawn(TimeSpan.FromSeconds(3), () =>
        {
            RemoveGroupConfirmButton.Disabled = false;
            RemoveWarningLabel.Text = Loc.GetString("construction-editor-remove-ready", ("spawnlist", spawnlist), ("category", category));
        });
    }

    private void ConfirmGroupRemoval()
    {
        var (spawnlist, category) = CurrentGroup();
        if (string.IsNullOrEmpty(spawnlist))
            return;

        OnRemoveGroup?.Invoke((spawnlist, category));
        Close();
    }
}
