using System.Globalization;
using System.Linq;
using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Content.Shared.CMU14.BalanceRating;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.BalanceRating;

[GenerateTypedNameReferences]
public sealed partial class CMUBalanceRatingStatisticsWindow : DefaultWindow
{
    private CMUBalanceRatingDashboard _dashboard = new([], 0, 0);

    public event Action? OnRefresh;

    public CMUBalanceRatingStatisticsWindow()
    {
        RobustXamlLoader.Load(this);

        Search.OnTextChanged += _ => RefreshRows();
        RefreshButton.OnPressed += _ => OnRefresh?.Invoke();

        CrtLobbyTheme.Apply(this);
    }

    public void UpdateDashboard(CMUBalanceRatingDashboard dashboard)
    {
        _dashboard = dashboard;
        SummaryLabel.Text = Loc.GetString(
            "cmu-balance-rating-statistics-summary",
            ("polls", dashboard.TotalPolls),
            ("responses", dashboard.TotalResponses),
            ("entries", dashboard.Entries.Count));

        RefreshRows();
    }

    private void RefreshRows()
    {
        StatisticsGrid.DisposeAllChildren();
        AddHeaders();

        var query = Search.Text.Trim();
        var entries = _dashboard.Entries
            .Where(entry => MatchesSearch(entry, query))
            .OrderBy(entry => entry.TargetName, StringComparer.CurrentCultureIgnoreCase)
            .ThenBy(entry => entry.TargetId, StringComparer.OrdinalIgnoreCase)
            .ThenBy(entry => entry.Target)
            .ThenBy(entry => entry.Metric)
            .ToList();

        EmptyLabel.Visible = entries.Count == 0;
        TablePanel.Visible = entries.Count > 0;

        foreach (var entry in entries)
            AddEntry(entry);

        CrtLobbyTheme.Apply(StatisticsGrid);
    }

    private bool MatchesSearch(CMUBalanceRatingStatisticsEntry entry, string query)
    {
        if (query.Length == 0)
            return true;

        return entry.TargetName.Contains(query, StringComparison.CurrentCultureIgnoreCase) ||
               entry.TargetId.Contains(query, StringComparison.OrdinalIgnoreCase) ||
               GetTargetName(entry.Target).Contains(query, StringComparison.CurrentCultureIgnoreCase) ||
               GetMetricName(entry.Metric).Contains(query, StringComparison.CurrentCultureIgnoreCase);
    }

    private void AddHeaders()
    {
        AddHeader("cmu-balance-rating-statistics-header-target-name", 180);
        AddHeader("cmu-balance-rating-statistics-header-target-id", 210);
        AddHeader("cmu-balance-rating-statistics-header-target-type", 80);
        AddHeader("cmu-balance-rating-statistics-header-metric", 80);
        AddHeader("cmu-balance-rating-statistics-header-average", 70);
        AddHeader("cmu-balance-rating-statistics-header-responses", 80);
        AddHeader("cmu-balance-rating-statistics-header-polls", 60);
        AddHeader("cmu-balance-rating-statistics-header-rating-1", 36);
        AddHeader("cmu-balance-rating-statistics-header-rating-2", 36);
        AddHeader("cmu-balance-rating-statistics-header-rating-3", 36);
        AddHeader("cmu-balance-rating-statistics-header-rating-4", 36);
        AddHeader("cmu-balance-rating-statistics-header-rating-5", 36);
    }

    private void AddHeader(string locId, float minWidth)
    {
        StatisticsGrid.AddChild(new Label
        {
            Text = Loc.GetString(locId),
            MinWidth = minWidth,
            ClipText = true,
            ToolTip = Loc.GetString(locId),
            StyleClasses = { StyleClass.LabelSubText },
        });
    }

    private void AddEntry(CMUBalanceRatingStatisticsEntry entry)
    {
        AddCell(entry.TargetName, 180);
        AddCell(entry.TargetId, 210);
        AddCell(GetTargetName(entry.Target), 80);
        AddCell(GetMetricName(entry.Metric), 80);
        AddCell(
            entry.Responses == 0
                ? Loc.GetString("cmu-balance-rating-statistics-no-average")
                : entry.Average.ToString("0.00", CultureInfo.CurrentCulture),
            70);
        AddCell(entry.Responses.ToString(CultureInfo.CurrentCulture), 80);
        AddCell(entry.Polls.ToString(CultureInfo.CurrentCulture), 60);
        AddCell(entry.Rating1.ToString(CultureInfo.CurrentCulture), 36);
        AddCell(entry.Rating2.ToString(CultureInfo.CurrentCulture), 36);
        AddCell(entry.Rating3.ToString(CultureInfo.CurrentCulture), 36);
        AddCell(entry.Rating4.ToString(CultureInfo.CurrentCulture), 36);
        AddCell(entry.Rating5.ToString(CultureInfo.CurrentCulture), 36);
    }

    private void AddCell(string text, float minWidth)
    {
        StatisticsGrid.AddChild(new Label
        {
            Text = text,
            MinWidth = minWidth,
            ClipText = true,
            ToolTip = text,
        });
    }

    private static string GetTargetName(CMUBalanceRatingTarget target)
    {
        return Loc.GetString(target switch
        {
            CMUBalanceRatingTarget.Weapon => "cmu-balance-rating-statistics-target-weapon",
            CMUBalanceRatingTarget.Xeno => "cmu-balance-rating-statistics-target-xeno",
            CMUBalanceRatingTarget.Map => "cmu-balance-rating-statistics-target-map",
            _ => "cmu-balance-rating-statistics-target-unknown",
        });
    }

    private static string GetMetricName(CMUBalanceRatingMetric metric)
    {
        return Loc.GetString(metric switch
        {
            CMUBalanceRatingMetric.Power => "cmu-balance-rating-statistics-metric-power",
            CMUBalanceRatingMetric.Fun => "cmu-balance-rating-statistics-metric-fun",
            _ => "cmu-balance-rating-statistics-metric-unknown",
        });
    }
}
