using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Content.Shared.CMU14.BalanceRating;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.CMU14.BalanceRating;

[GenerateTypedNameReferences]
public sealed partial class CMUBalanceRatingPopup : Control
{
    private static readonly SpriteSpecifier MapIcon = new SpriteSpecifier.Rsi(
        new ResPath("/Textures/_RMC14/Structures/Machines/map_table.rsi"),
        "maptable");

    [Dependency] private IEntitySystemManager _systems = default!;
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IStylesheetManager _styles = default!;

    public event Action<byte>? RatingSelected;
    public event Action? Expired;

    public long PollId { get; }

    private readonly Button[] _buttons;
    private readonly TimeSpan _endTime;
    private readonly SpriteSystem _sprite;
    private bool _completed;

    public CMUBalanceRatingPopup(
        long pollId,
        CMUBalanceRatingTarget target,
        CMUBalanceRatingMetric metric,
        string targetId,
        string targetName,
        TimeSpan endTime)
    {
        PollId = pollId;
        _endTime = endTime;

        IoCManager.InjectDependencies(this);
        _sprite = _systems.GetEntitySystem<SpriteSystem>();
        RobustXamlLoader.Load(this);

        Stylesheet = _styles.SheetNano;
        CrtLobbyTheme.Apply(this);
        Modulate = Color.White.WithAlpha(0.97f);

        QuestionLabel.SetMessage(FormattedMessage.FromUnformatted(Loc.GetString(GetQuestionLocId(target, metric))));
        TargetLabel.SetMessage(FormattedMessage.FromUnformatted(targetName));
        var icon = target == CMUBalanceRatingTarget.Map
            ? MapIcon
            : new SpriteSpecifier.EntityPrototype(targetId);
        TargetIcon.Texture = _sprite.Frame0(icon);

        if (metric == CMUBalanceRatingMetric.Fun)
        {
            LowEndpointLabel.Text = Loc.GetString("cmu-balance-rating-endpoint-unfun");
            HighEndpointLabel.Text = Loc.GetString("cmu-balance-rating-endpoint-fun");
        }
        else
        {
            LowEndpointLabel.Text = Loc.GetString("cmu-balance-rating-endpoint-weak");
            HighEndpointLabel.Text = Loc.GetString("cmu-balance-rating-endpoint-powerful");
        }

        _buttons =
        [
            Rating1Button,
            Rating2Button,
            Rating3Button,
            Rating4Button,
            Rating5Button,
        ];

        for (var i = 0; i < _buttons.Length; i++)
        {
            var rating = (byte) (i + 1);
            var button = _buttons[i];
            button.ToolTip = Loc.GetString("cmu-balance-rating-option-tooltip", ("rating", rating));
            button.OnPressed += _ => SelectRating(rating);
        }

        UpdateCountdown();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var remaining = UpdateCountdown();
        if (_completed || remaining > TimeSpan.Zero)
            return;

        Complete();
        Expired?.Invoke();
    }

    private void SelectRating(byte rating)
    {
        if (_completed)
            return;

        Complete();
        RatingSelected?.Invoke(rating);
    }

    private void Complete()
    {
        if (_completed)
            return;

        _completed = true;
        foreach (var button in _buttons)
        {
            button.Disabled = true;
        }
    }

    private TimeSpan UpdateCountdown()
    {
        var remaining = _endTime - _timing.RealTime;
        if (remaining < TimeSpan.Zero)
            remaining = TimeSpan.Zero;

        var seconds = (int) Math.Ceiling(remaining.TotalSeconds);
        var rounded = TimeSpan.FromSeconds(seconds);
        var time = rounded.TotalHours >= 1
            ? $"{(int) rounded.TotalHours}:{rounded.Minutes:D2}:{rounded.Seconds:D2}"
            : $"{(int) rounded.TotalMinutes}:{rounded.Seconds:D2}";
        TimeLeftLabel.Text = Loc.GetString("cmu-balance-rating-time-left", ("time", time));

        return remaining;
    }

    private static string GetQuestionLocId(CMUBalanceRatingTarget target, CMUBalanceRatingMetric metric)
    {
        return (target, metric) switch
        {
            (CMUBalanceRatingTarget.Weapon, CMUBalanceRatingMetric.Power) =>
                "cmu-balance-rating-question-weapon-power",
            (CMUBalanceRatingTarget.Weapon, CMUBalanceRatingMetric.Fun) =>
                "cmu-balance-rating-question-weapon-fun",
            (CMUBalanceRatingTarget.Xeno, CMUBalanceRatingMetric.Power) =>
                "cmu-balance-rating-question-xeno-power",
            (CMUBalanceRatingTarget.Xeno, CMUBalanceRatingMetric.Fun) =>
                "cmu-balance-rating-question-xeno-fun",
            (CMUBalanceRatingTarget.Map, CMUBalanceRatingMetric.Fun) =>
                "cmu-balance-rating-question-map-fun",
            _ => "cmu-balance-rating-question-generic",
        };
    }
}
