using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Content.Shared.CMU14.CharacterDescription;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.CharacterDescription.UI;

[GenerateTypedNameReferences]
public sealed partial class DetailedExamineWindow : DefaultWindow
{
    [Dependency] private  IStylesheetManager _stylesheetManager = default!;

    public DetailedExamineWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Stylesheet = _stylesheetManager.SheetNano;
        CrtLobbyTheme.ApplyWindow(this, useCrtTypography: true);
    }

    public void UpdateState(DetailedExamineEuiState state)
    {
        Title = state.Name;
        ContentContainer.DisposeAllChildren();

        CharacterDescriptionRowBuilder.AddHeading(ContentContainer, state.Name);
        CharacterDescriptionRowBuilder.AddRow(ContentContainer, Loc.GetString("detailed-examine-age"), state.Age > 0 ? state.Age.ToString() : null, Loc.GetString("detailed-examine-age-tooltip"));
        CharacterDescriptionRowBuilder.AddRow(ContentContainer, Loc.GetString("detailed-examine-height"), state.Height, Loc.GetString("detailed-examine-height-tooltip"));
        CharacterDescriptionRowBuilder.AddRow(ContentContainer, Loc.GetString("detailed-examine-weight"), state.Weight > 0 ? Loc.GetString("detailed-examine-weight-value", ("weight", state.Weight)) : null, Loc.GetString("detailed-examine-weight-tooltip"));
        CharacterDescriptionRowBuilder.AddRow(ContentContainer, Loc.GetString("detailed-examine-build"), state.Build, Loc.GetString("detailed-examine-build-tooltip"));
        CharacterDescriptionRowBuilder.AddRow(ContentContainer, Loc.GetString("detailed-examine-skin-tone"), state.SkinToneName, Loc.GetString("detailed-examine-skin-tone-tooltip"));
        CharacterDescriptionRowBuilder.AddRow(ContentContainer, Loc.GetString("detailed-examine-hair-color"), state.HairColorName, Loc.GetString("detailed-examine-hair-color-tooltip"));
        CharacterDescriptionRowBuilder.AddRow(ContentContainer, Loc.GetString("detailed-examine-eye-color"), state.EyeColorName, Loc.GetString("detailed-examine-eye-color-tooltip"));
        CharacterDescriptionRowBuilder.AddRow(ContentContainer, Loc.GetString("detailed-examine-allegiance"), state.Allegiance, Loc.GetString("detailed-examine-allegiance-tooltip"));
        CharacterDescriptionRowBuilder.AddRow(ContentContainer, Loc.GetString("detailed-examine-origin"), state.Origin, Loc.GetString("detailed-examine-origin-tooltip"));

        CharacterDescriptionRowBuilder.AddSeparator(ContentContainer);

        CharacterDescriptionRowBuilder.AddParagraph(ContentContainer, Loc.GetString("detailed-examine-full-description"), state.FullDescription, Loc.GetString("detailed-examine-full-description-tooltip"));
        CharacterDescriptionRowBuilder.AddParagraph(ContentContainer, Loc.GetString("detailed-examine-medical-record"), state.MedicalRecord, Loc.GetString("detailed-examine-medical-record-tooltip"));
        CharacterDescriptionRowBuilder.AddParagraph(ContentContainer, Loc.GetString("detailed-examine-criminal-record"), state.CriminalRecord, Loc.GetString("detailed-examine-criminal-record-tooltip"));
        CharacterDescriptionRowBuilder.AddParagraph(ContentContainer, Loc.GetString("detailed-examine-general-record"), state.GeneralRecord, Loc.GetString("detailed-examine-general-record-tooltip"));

        CrtLobbyTheme.Apply(ContentContainer);
    }
}
