using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14;

[GenerateTypedNameReferences]
public sealed partial class ColonyCommsConsole : DefaultWindow
{
    public ColonyCommsConsole()
    {
        RobustXamlLoader.Load(this);
    }
}
