using Robust.Client.AutoGenerated;
using Robust.Client.State;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.CMU14.Chemistry.Research;

[GenerateTypedNameReferences]
public sealed partial class ResearchDataTerminalWindow : DefaultWindow
{
    public TimeSpan NextUpdate;
    public ResearchDataTerminalWindow()
    {
        RobustXamlLoader.Load(this);
    }
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        var time = IoCManager.Resolve<IGameTiming>().CurTime;
        TimeLeftBar.Value = (float)(NextUpdate - time).TotalMilliseconds;
        TimeLeft.Text = Loc.GetString("research-data-ui-time-left", ("TIME", Math.Max(0, (int)(NextUpdate - time).TotalSeconds)));
    }
}
