- type: loadout
  id: AU14SprayCleanerExperimentalAU14
<<<<<<< HEAD:Resources/Prototypes/_CMU14/Roles/Shared/Loadouts/Items/RoleSpecific/Synthetic/AU14SprayCleanerExperimentalAU14.yml
  # cost: 2 # RuMC edit
=======
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Resources/Prototypes/CMU14/Roles/Shared/Loadouts/Items/RoleSpecific/Synthetic/AU14SprayCleanerExperimentalAU14.yml
  inhand:
  - AU14SprayCleanerExperimental
# Civilian Synth Specializations
