using Content.Shared.CMU14.Hospital;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.Hospital;

[GenerateTypedNameReferences]
public sealed partial class HospitalEmergencyComputerWindow : DefaultWindow
{
    public HospitalEmergencyComputerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(HospitalEmergencyComputerBuiState state)
    {
        StatusLabel.Text = state.StatusText;
        LandingZoneLabel.Text = state.HasLandingZone
            ? Loc.GetString("hospital-emergency-landing-zone-linked")
            : Loc.GetString("hospital-emergency-landing-zone-unavailable");

        IncidentReportLabel.Text = string.IsNullOrWhiteSpace(state.IncidentReport)
            ? Loc.GetString("hospital-emergency-no-active-incident")
            : state.IncidentReport;

        CasualtiesLabel.Text = state.Casualties.ToString();
        SeverityLabel.Text = state.Severity == 0
            ? "--"
            : Loc.GetString("hospital-emergency-severity-value", ("severity", state.Severity));
        RewardLabel.Text = Loc.GetString("hospital-emergency-reward-value", ("amount", state.Reward));
        PatientsLabel.Text = Loc.GetString("hospital-emergency-patients-value",
            ("active", state.ActivePatients),
            ("cleared", state.FullyHealedPatients));
        TimerLabel.Text = state.SecondsRemaining > 0
            ? Loc.GetString("hospital-emergency-timer-seconds", ("seconds", state.SecondsRemaining))
            : "--";

        var vipAudit = state.LastVipPenalty > 0
            ? Loc.GetString("hospital-emergency-audit-vip-penalty", ("amount", state.LastVipPenalty))
            : string.Empty;
        var deathAudit = state.LastPermanentDeathPenalty > 0
            ? Loc.GetString("hospital-emergency-audit-death-penalty", ("amount", state.LastPermanentDeathPenalty))
            : string.Empty;

        AuditLabel.Text = state.LastPayout > 0 ||
            state.LastMissedInjuries > 0 ||
            state.LastVipPenalty > 0 ||
            state.LastPermanentDeathPenalty > 0
            ? Loc.GetString("hospital-emergency-audit-summary",
                ("payout", state.LastPayout),
                ("missed", state.LastMissedInjuries),
                ("vip", vipAudit),
                ("death", deathAudit))
            : Loc.GetString("hospital-emergency-audit-none");

        ApproveLandingButton.Disabled = !state.CanApproveLanding;
        SkipContractButton.Disabled = !state.CanSkipContract;
        RequestPickupButton.Disabled = !state.CanRequestPickup;
        ReleaseShuttleButton.Disabled = !state.CanReleaseShuttle;
    }
}
