using System.Linq;
using System.Numerics;
using Content.Shared.CMU14.AllianceConsole;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.CMU14.AllianceConsole;

[GenerateTypedNameReferences]
public sealed partial class AllianceConsoleWindow : DefaultWindow
{
    public event Action<string, AllianceStatus>? OnSetStatus;

    private readonly IPrototypeManager _prototypes = IoCManager.Resolve<IPrototypeManager>();

    private readonly Dictionary<string, OptionButton> _factionButtons = new();

    public AllianceConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(AllianceConsoleBuiState state)
    {
        var side = AllianceConsoleComponent.ResolveFaction(_prototypes, state.Faction); // CMU14
        FactionLabel.Text = Loc.GetString(
            "alliance-console-faction-title",
            ("faction", side?.Name ?? state.Faction));

        // Rebuild faction list if the set of factions changed.
        var existing = _factionButtons.Keys.ToHashSet();
        var incoming = state.ControllableFactions.ToHashSet();
        if (!existing.SetEquals(incoming))
        {
            FactionList.RemoveAllChildren();
            _factionButtons.Clear();

            foreach (var faction in state.ControllableFactions.OrderBy(f => f))
            {
                var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 6 };

                var displayName = AllianceConsoleComponent.ResolveFaction(_prototypes, faction)?.Name ?? faction; // CMU14
                var label = new Label { Text = displayName, HorizontalExpand = true, MinSize = new Vector2(160, 0) };
                row.AddChild(label);

                var btn = new OptionButton { MinSize = new Vector2(130, 0) };
                btn.AddItem(Loc.GetString("alliance-console-status-neutral"), (int) AllianceStatus.Neutral);
                btn.AddItem(Loc.GetString("alliance-console-status-friendly"), (int) AllianceStatus.Friendly);
                btn.AddItem(Loc.GetString("alliance-console-status-hostile"), (int) AllianceStatus.Hostile);

                var capturedFaction = faction;
                btn.OnItemSelected += args =>
                {
                    btn.SelectId(args.Id);
                    OnSetStatus?.Invoke(capturedFaction, (AllianceStatus) args.Id);
                };

                row.AddChild(btn);
                FactionList.AddChild(row);
                _factionButtons[faction] = btn;
            }
        }

        // Sync button selections to current state.
        foreach (var (faction, btn) in _factionButtons)
        {
            var status = state.FactionStatuses.TryGetValue(faction, out var s) ? s : AllianceStatus.Neutral;
            btn.SelectId((int) status);
        }
    }
}
