using System.Linq;
using Content.Shared.CMU14.Threats.Mobs.WorkingJoe;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.Threats.Mobs.WorkingJoe;

[GenerateTypedNameReferences]
public sealed partial class WorkingJoeVoiceWindow : DefaultWindow
{
    private static readonly string[] QuestionCategories =
    {
        "Curious", "Interrogation", "Identification", "Concern"
    };

    private const string AllButtonName = "WorkingJoeVoiceAllButton";
    private const string FavoritesButtonName = "WorkingJoeVoiceFavoritesButton";
    private const string RecentButtonName = "WorkingJoeVoiceRecentButton";
    private const int MaxRecent = 5;
    private readonly WorkingJoeVoiceFavorites _favorites;
    private readonly List<string> _recentIds = new();

    private List<WorkingJoeVoiceLine> _allLines = new();
    private string? _selectedCategory;
    private bool _showFavorites;
    private Button? _allButton;
    private Button? _favButton;
    private Button? _recentButton;

    public WorkingJoeVoiceWindow(WorkingJoeVoiceFavorites favorites)
    {
        _favorites = favorites;
        RobustXamlLoader.Load(this);
        SearchBar.OnTextChanged += _ => RebuildList();
    }

    public event Action<string>? OnLineSelected;

    public void SetLines(List<WorkingJoeVoiceLine> lines)
    {
        _allLines = lines.OrderBy(l => l.Category).ThenBy(l => l.DisplayName).ToList();
        RebuildCategories();
        RebuildList();
    }

    private void RebuildCategories()
    {
        CategoryList.RemoveAllChildren();

        var allButton = new Button
        {
<<<<<<< HEAD:Content.Client/_CMU14/Threats/Mobs/WorkingJoe/WorkingJoeVoiceWindow.xaml.cs
            Text = Loc.GetString("working-joe-voice-category-all"), // RuMC edit
=======
            Name = AllButtonName,
            Text = Loc.GetString("working-joe-voice-category-all"),
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Threats/Mobs/WorkingJoe/WorkingJoeVoiceWindow.xaml.cs
            HorizontalExpand = true,
            ToggleMode = true,
            Pressed = _selectedCategory == null && !_showFavorites
        };
        allButton.OnPressed += _ =>
        {
            _selectedCategory = null;
            _showFavorites = false;
            RebuildList();
            UpdateCategoryButtonStates();
        };
        _allButton = allButton; // RuMC edit
        CategoryList.AddChild(allButton);

        var favButton = new Button
        {
<<<<<<< HEAD:Content.Client/_CMU14/Threats/Mobs/WorkingJoe/WorkingJoeVoiceWindow.xaml.cs
            Text = Loc.GetString("working-joe-voice-category-favorites"), // RuMC edit
=======
            Name = FavoritesButtonName,
            Text = Loc.GetString("working-joe-voice-category-favorites"),
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Threats/Mobs/WorkingJoe/WorkingJoeVoiceWindow.xaml.cs
            HorizontalExpand = true,
            ToggleMode = true,
            Pressed = _showFavorites
        };
        favButton.OnPressed += _ =>
        {
            _showFavorites = true;
            _selectedCategory = null;
            RebuildList();
            UpdateCategoryButtonStates();
        };
        _favButton = favButton; // RuMC edit
        CategoryList.AddChild(favButton);

        var recentButton = new Button
        {
<<<<<<< HEAD:Content.Client/_CMU14/Threats/Mobs/WorkingJoe/WorkingJoeVoiceWindow.xaml.cs
            Text = Loc.GetString("working-joe-voice-category-recent"), // RuMC edit
=======
            Name = RecentButtonName,
            Text = Loc.GetString("working-joe-voice-category-recent"),
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Threats/Mobs/WorkingJoe/WorkingJoeVoiceWindow.xaml.cs
            HorizontalExpand = true,
            ToggleMode = true,
            Pressed = _selectedCategory == "__recent"
        };
        recentButton.OnPressed += _ =>
        {
            _selectedCategory = "__recent";
            _showFavorites = false;
            RebuildList();
            UpdateCategoryButtonStates();
        };
        _recentButton = recentButton; // RuMC edit
        CategoryList.AddChild(recentButton);

        List<string> nonQuestionCategories = _allLines
            .Select(l => l.Category)
            .Distinct()
            .Where(c => !QuestionCategories.Contains(c))
            .OrderBy(c => c)
            .ToList();

        List<string> questionCategories = _allLines
            .Select(l => l.Category)
            .Distinct()
            .Where(c => QuestionCategories.Contains(c))
            .OrderBy(c => Array.IndexOf(QuestionCategories, c))
            .ToList();

        foreach (string category in nonQuestionCategories)
        {
            AddCategoryButton(category);
        }

        if (questionCategories.Count > 0)
        {
            var separator = new PanelContainer
            {
                MinHeight = 2,
                HorizontalExpand = true,
                Margin = new(0, 6)
            };
            CategoryList.AddChild(separator);

            var label = new Label
            {
<<<<<<< HEAD:Content.Client/_CMU14/Threats/Mobs/WorkingJoe/WorkingJoeVoiceWindow.xaml.cs
                Text = Loc.GetString("working-joe-voice-questions-label"), // RuMC edit
=======
                Text = Loc.GetString("working-joe-voice-category-questions"),
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Threats/Mobs/WorkingJoe/WorkingJoeVoiceWindow.xaml.cs
                FontColorOverride = Color.FromHex("#AAAAAA"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new(0, 2)
            };
            CategoryList.AddChild(label);

            foreach (string category in questionCategories)
            {
                AddCategoryButton(category);
            }
        }
    }

    private void AddCategoryButton(string category)
    {
        var key = $"working-joe-voice-category-{category.ToLowerInvariant()}"; // RuMC edit
        var button = new Button
        {
            Name = category, // RuMC edit
            Text = Loc.TryGetString(key, out var translated) ? translated : category, // RuMC edit
            HorizontalExpand = true,
            ToggleMode = true,
            Pressed = _selectedCategory == category
        };
        button.OnPressed += _ =>
        {
            _selectedCategory = category;
            _showFavorites = false;
            RebuildList();
            UpdateCategoryButtonStates();
        };
        CategoryList.AddChild(button);
    }

    private void UpdateCategoryButtonStates()
    {
        foreach (Control child in CategoryList.Children)
        {
            if (child is not Button btn)
                continue;

<<<<<<< HEAD:Content.Client/_CMU14/Threats/Mobs/WorkingJoe/WorkingJoeVoiceWindow.xaml.cs
            if (btn == _allButton) // RuMC edit
                btn.Pressed = _selectedCategory == null && !_showFavorites;
            else if (btn == _favButton) // RuMC edit
                btn.Pressed = _showFavorites;
            else if (btn == _recentButton) // RuMC edit
=======
            if (btn.Name == AllButtonName)
                btn.Pressed = _selectedCategory == null && !_showFavorites;
            else if (btn.Name == FavoritesButtonName)
                btn.Pressed = _showFavorites;
            else if (btn.Name == RecentButtonName)
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Threats/Mobs/WorkingJoe/WorkingJoeVoiceWindow.xaml.cs
                btn.Pressed = _selectedCategory == "__recent";
            else
                btn.Pressed = btn.Name == _selectedCategory; // RuMC edit
        }
    }

    private void RebuildList()
    {
        LineList.RemoveAllChildren();

        string search = SearchBar.Text.Trim().ToLowerInvariant();

        List<WorkingJoeVoiceLine> filtered;

        if (_selectedCategory == "__recent")
        {
            filtered = _recentIds
                .Select(id => _allLines.FirstOrDefault(l => l.EmoteId == id))
                .Where(l => l != null)
                .Where(l => string.IsNullOrEmpty(search) || l!.DisplayName.ToLowerInvariant().Contains(search))
                .ToList()!;
        }
        else if (_showFavorites)
        {
            filtered = _allLines
                .Where(l => _favorites.Contains(l.EmoteId))
                .Where(l => string.IsNullOrEmpty(search) || l.DisplayName.ToLowerInvariant().Contains(search))
                .ToList();
        }
        else
        {
            filtered = _allLines
                .Where(l => _selectedCategory == null || l.Category == _selectedCategory)
                .Where(l => string.IsNullOrEmpty(search) || l.DisplayName.ToLowerInvariant().Contains(search))
                .ToList();
        }

        foreach (WorkingJoeVoiceLine line in filtered)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                SeparationOverride = 4
            };

            bool isFav = _favorites.Contains(line.EmoteId);
            var favButton = new Button
            {
                Text = isFav ? "\u2605" : "\u2606",
                MinWidth = 30,
                MaxWidth = 30,
                ToolTip = Loc.GetString(isFav
                    ? "working-joe-voice-favorite-remove"
                    : "working-joe-voice-favorite-add")
            };
            string emoteId = line.EmoteId;
            favButton.OnPressed += _ =>
            {
                _favorites.Toggle(emoteId);
                RebuildList();
            };
            row.AddChild(favButton);

            var lineButton = new Button
            {
                Text = line.DisplayName,
                HorizontalExpand = true,
                StyleClasses = { "OpenRight" }
            };
            lineButton.OnPressed += _ =>
            {
                OnLineSelected?.Invoke(emoteId);
                AddRecent(emoteId);
            };
            row.AddChild(lineButton);

            LineList.AddChild(row);
        }

        if (!filtered.Any())
        {
            LineList.AddChild(new Label
            {
<<<<<<< HEAD:Content.Client/_CMU14/Threats/Mobs/WorkingJoe/WorkingJoeVoiceWindow.xaml.cs
                Text = Loc.GetString("working-joe-voice-no-results"), // RuMC edit
=======
                Text = Loc.GetString("working-joe-voice-no-results"),
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Threats/Mobs/WorkingJoe/WorkingJoeVoiceWindow.xaml.cs
                FontColorOverride = Color.FromHex("#888888"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new(0, 12)
            });
        }
    }

    private void AddRecent(string emoteId)
    {
        _recentIds.Remove(emoteId);
        _recentIds.Insert(0, emoteId);
        if (_recentIds.Count > MaxRecent)
            _recentIds.RemoveAt(_recentIds.Count - 1);
    }
}
