- type: antagSpecifier
  id: SerialKiller
  prefRoles: [ SerialKillerRole ]
  jobBlacklistGroup:
  - AllGovforJobs
  - AllOpforJobs
  - AllCLFJobs
# - AllColonyDepartmentHeadJobs
  - AllSynthJobs
  briefing:
    text: serialkiller-role-greeting
    color: DarkRed
    sound: "/Audio/Ambience/Antag/headrev_start.ogg"
  startingGear: AU14GearSerialKiller
  startingSkills:
    RMCSkillCqc: 2
    RMCSkillMeleeWeapons: 3
  components:
  - type: SerialKiller
  - type: ColonyBounty
    bounty: 2250
    reason: Wanted for multiple homicides - suspect at large
    recordName: Serial Killer (Unknown)
    includePrints: true
    includeDna: true
    includeLanguages: true
    capturedFaxPaper: AUPaperSerialKillerCaptured
  mindRoles:
  - MindRoleSerialKiller

- type: entity
  id: SerialKiller
  parent: BaseGameRule
  components:
  - type: GameRule
  - type: SerialKillerRule
  - type: AntagSelection
    selectionTime: JobsAssigned
    antags:
    - !type:RandomAntagCount
      proto: SerialKiller
      range:
        min: 1
        max: 2

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleSerialKiller
  name: Serial Killer Mind Role
  components:
  - type: MindRole
    antagPrototype: SerialKillerRole
    exclusiveAntag: true
    roleType: SoloAntagonist

- type: antag
  parent: CMUAntagColonyBase
  id: SerialKillerRole
  name: roles-antag-serialkiller-name
  setPreference: true
  objective: roles-antag-serialkiller-objective

- type: startingGear
  id: AU14GearSerialKiller
  storage:
    back:
    - AUPaperSerialKiller
    - RMCLighter
