using System.Linq;
using Content.Shared.CMU14.Round.Objectives;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.Round.Objectives;

[GenerateTypedNameReferences]
public sealed partial class ObjectivesConsoleWindow : FancyWindow
{
    public Action<string>? RequestIntelCallback;

    public ObjectivesConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        CloseButton.OnPressed += _ => Close();
    }

    public void UpdateObjectives(List<ObjectiveEntry> objectives, int currentWinPoints, int requiredWinPoints)
    {
        CurrentWinPointsLabel.Text = $"Current Win Points: {currentWinPoints}";
        RequiredWinPointsLabel.Text = $"Points to Final Objective: {requiredWinPoints}";

        ObjectivesList.DisposeAllChildren();
        foreach (var obj in SortForDisplay(objectives))
        {
            var entry = new ObjectiveEntryControl();
            entry.SetData(obj, id => RequestIntelCallback?.Invoke(id));
            ObjectivesList.AddChild(entry);
        }
    }

    private static IEnumerable<ObjectiveEntry> SortForDisplay(List<ObjectiveEntry> objectives)
    {
        return objectives
            .OrderBy(o => TypeRank(o.Type))
            .ThenBy(o => StatusRank(o.Status));
    }

    private static int TypeRank(ObjectiveTypeDisplay type) => type switch
    {
        ObjectiveTypeDisplay.Win => 0,
        ObjectiveTypeDisplay.Major => 1,
        _ => 2,
    };

    private static int StatusRank(ObjectiveStatusDisplay status) => status switch
    {
        ObjectiveStatusDisplay.Uncompleted => 0,
        ObjectiveStatusDisplay.Repeating => 1,
        _ => 2,
    };
}
