// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 wray-git
// SPDX-License-Identifier: AGPL-3.0-only
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client.CMU14.SavedBuilds;
using Content.Client.Resources;
using Content.Client.UserInterface.Controls;
using Content.Shared.CMU14.SavedBuilds;
using Content.Shared._RMC14.Prototypes;
using Content.Shared.Construction.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Construction.UI;

/// <summary>
/// Improved Gmod-style construction menu. Implements <see cref="IConstructionMenuView"/> as a drop-in
/// replacement for <see cref="ConstructionMenu"/> - the presenter sees the same interface and drives it
/// through the grouped grid-population path.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class GmodConstructionMenu : DefaultWindow, IConstructionMenuView
{
    private const string LogoPath = "/Textures/Logo/logo.png";

    // Mirror the presenter's private category-name constants so we can fire the right events.
    private const string FavoriteCatName = "construction-category-favorites";
    private const string ForAllCategoryName = "construction-category-all";

    // Palette: the whole menu chrome is SOLID; only the center item grid is low-opacity so the
    // game world shows through there (and nowhere else). For that to work, every layer BEHIND the
    // center grid (the window background panel and RootPanel) must be transparent, while the
    // surrounding panels paint their own solid backgrounds.
    // USCM Amber Terminal palette (see memory project-ui-palette). Chrome panels are the dark amber-tinted
    // panel color; the center grid stays low-opacity near-black so the game world shows through there.
    // Modern dark-slate palette (the USCM amber look was dropped). Flat: StyleBoxFlat can't round corners,
    // so true rounded edges would need 9-slice texture assets (deferred art pass).
    private static readonly Color RootBg = Color.Transparent;
    private static readonly Color PanelBg = Color.FromHex("#1E222B");     // side panels (solid)
    private static readonly Color CenterBg = Color.FromHex("#12141A99");  // see-through center grid
    private static readonly Color DetailBg = Color.FromHex("#1A1E26");
    private static readonly Color RowBg = Color.FromHex("#232833");       // list/button rows
    private static readonly Color RowHover = Color.FromHex("#2D3340");
    private static readonly Color RowSelected = Color.FromHex("#2B3A57"); // accent-tinted selection
    private static readonly Color Accent = Color.FromHex("#4C8DFF");      // modern blue accent
    private static readonly Color SubtleBorder = Color.FromHex("#2A2F3A");
    // Regular spawnlist buttons share one blue-tinted color so they read as a single group; the synthetic
    // "Saved Builds" and "Favorites" buttons stay the neutral RowBg so they stand apart from the spawnlists.
    private static readonly Color SpawnlistBg = Color.FromHex("#28324A");
    private static readonly Color SpawnlistSelected = Color.FromHex("#33476E");
    // Category sub-buttons nested under a selected spawnlist: darker than the spawnlist color so they read
    // as a child level of the tree.
    private static readonly Color CategoryBg = Color.FromHex("#20283A");
    private static readonly Color CategorySelected = Color.FromHex("#2C3E63");

    /// <summary>A modern flat panel stylebox (subtle border) over the given background.</summary>
    private static StyleBoxFlat Panel(Color bg) => new()
    {
        BackgroundColor = bg,
        BorderColor = SubtleBorder,
        BorderThickness = new Thickness(1),
    };

    /// <summary>A flat button stylebox with comfortable padding.</summary>
    private static StyleBoxFlat ButtonBox(Color bg, Color border) => new()
    {
        BackgroundColor = bg,
        BorderColor = border,
        BorderThickness = new Thickness(1),
        Padding = new Thickness(8, 5, 8, 5),
    };

    /// <summary>
    /// Applies the modern flat look to a button per-instance - <see cref="ContainerButton.StyleBoxOverride"/>
    /// bypasses the global stylesheet - with a hover swap and an accent-tinted selected state for toggles.
    /// </summary>
    private void Modernize(ContainerButton btn, bool toggle = false, Color? baseBg = null, Color? selectedBg = null)
    {
        var normal = baseBg ?? RowBg;
        var selectedColor = selectedBg ?? RowSelected;

        void Refresh()
        {
            var selected = toggle && btn.Pressed;
            btn.StyleBoxOverride = ButtonBox(selected ? selectedColor : normal, selected ? Accent : SubtleBorder);
        }

        btn.OnMouseEntered += _ =>
        {
            if (!btn.Disabled && !(toggle && btn.Pressed))
                btn.StyleBoxOverride = ButtonBox(RowHover, SubtleBorder);
        };
        btn.OnMouseExited += _ => Refresh();
        if (toggle)
            btn.OnToggled += _ => Refresh();
        Refresh();
    }

    // Detail slide-out animation.
    private const float DetailTargetWidth = 260f;
    private const float DetailSlideSpeed = 1600f; // px/sec
    private float _detailCurrentWidth;
    private float _detailGoalWidth;

    // Adapter stubs - the presenter writes to these to track state, but they never enter the visual tree.
    private readonly ListContainer _stubRecipes = new();
    private readonly OptionButton _stubOptionCategories = new();
    private readonly GridContainer _stubGrid = new();

    private string[] _categories = Array.Empty<string>();
    private string _currentTreeCategory = ForAllCategoryName;

    // Spawnlist tree (left panel). One toggle button per spawnlist; AU14 is the default group.
    private const string DefaultSpawnlist = "AU14";
    // The right-hand top-bar tab ("Z-Level (Experimental)") is a separate PAGE that gathers the experimental
    // z-level spawnlists (the buildable Tiles and the ZLevel stairs/beams); the Spawnlists page shows everything
    // else. The two top-bar tabs flip between these pages.
    private const string TilesSpawnlist = "Tiles";

    // The z-level page's spawnlist set lives in one shared place (Content.Client.CMU14.Construction) so the
    // presenter's "All" view can exclude the very same spawnlists this page gathers - keeping the two pages
    // as separate main categories that never share constructs.
    private static bool IsZLevelPageSpawnlist(string spawnlist) =>
        CMU14.Construction.ZLevelPageSpawnlists.Contains(spawnlist);
    private readonly Dictionary<string, BaseButton> _spawnlistButtons = new();
    private string _selectedSpawnlist = DefaultSpawnlist;
    private Texture? _logoTexture;

    // Per-spawnlist collapsible category lists in the left tree. Selecting a spawnlist expands its categories
    // beneath it (so a large spawnlist can be sorted by category); only the selected spawnlist's list is built
    // and shown at a time. _categoryContainers holds every spawnlist's (initially empty/hidden) child box;
    // _categoryButtons holds the currently-expanded spawnlist's buttons, keyed by the raw category value.
    [Dependency] private  IPrototypeManager _prototypeManager = default!;
    private readonly Dictionary<string, BoxContainer> _categoryContainers = new();
    private readonly Dictionary<string, BaseButton> _categoryButtons = new();
    // Per-spawnlist arrow glyph updaters (▶ collapsed / ▼ expanded); only spawnlists that actually have
    // categories get one. _expandedSpawnlist is the single spawnlist whose category list is currently shown.
    private readonly Dictionary<string, Action<bool>> _spawnlistArrowSetters = new();
    private string? _expandedSpawnlist;
    // Smaller font for the nested category buttons so they read as a sub-level. Built once (needs the cache).
    private Font? _categoryFont;

    // Collapsible-spawnlist arrow glyphs (same symbol font coverage as the ✕ close button in the top bar).
    private const string ArrowCollapsed = "▶";
    private const string ArrowExpanded = "▼";

    // Which top-bar page is shown. Spawnlists = every spawnlist except Tiles; Tiles = only the Tiles spawnlist.
    private enum MenuPage { Spawnlists, Tiles }
    private MenuPage _currentPage = MenuPage.Spawnlists;
    private IReadOnlyList<string> _allSpawnlists = Array.Empty<string>();

    // "Saved Builds" - a synthetic spawnlist that lists user-saved builds instead of recipes.
    private BaseButton? _savedBuildsButton;
    private bool _savedBuildsActive;
    private SavedBuildInfo? _currentSavedBuild;
    private readonly SavedBuildListSystem _savedBuildList;

    // Host-only utilities (e.g. opening the saved-builds folder in the host OS file explorer).
    private bool _isAdmin;
    // Construction-menu editing (detail panel "Change Recipe" / "Remove Item"): a Host admin OR a player
    // holding the JModEditor whitelist. The target entity id drives Change Recipe (opens the editor for it);
    // the construction id drives Remove Item (hides that recipe). The server re-validates every request.
    private bool _canEditMenu;
    private string? _currentTargetEntityId;
    private string? _currentRecipeId;

    /// <summary>Whitelist-only role that unlocks menu editing for a non-admin. Must match the server's EditorWhitelistJob.</summary>
    private const string EditorWhitelistJob = "JModEditor";

    // Two-click guard for the saved-build delete button (first click arms, second confirms).
    private bool _saveBuildDeleteArmed;

    public GmodConstructionMenu()
    {
        SetSize = new Vector2(1100, 640);
        MinSize = new Vector2(900, 500);

        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("construction-menu-title");

        _savedBuildList = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SavedBuildListSystem>();
        _savedBuildList.ListUpdated += OnSavedBuildListUpdated;

        // DefaultWindow draws its own opaque background panel (the "windowPanel" styled
        // PanelContainer at child index 0) BEHIND our content. Make it transparent so our
        // semi-transparent panels are the only thing tinting the game world behind the menu.
        if (GetChild(0) is PanelContainer windowPanel)
        {
            windowPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.Transparent,
                BorderColor = Color.Transparent,
                BorderThickness = new Thickness(0f),
            };
        }

        // Solid chrome everywhere except the center item grid, which is the only low-opacity panel.
        RootPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = RootBg };
        TopBarPanel.PanelOverride = Panel(PanelBg);
        TreePanel.PanelOverride = Panel(PanelBg);
        CenterPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = CenterBg };
        ToolsPanel.PanelOverride = Panel(PanelBg);
        // Detail abuts Tools on its right: drop the right border so the two read as one continuous surface.
        DetailPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = DetailBg,
            BorderColor = SubtleBorder,
            BorderThickness = new Thickness(1, 1, 0, 1),
        };

        // Remove the native DefaultWindow title bar - our own slim top bar (Spawnlists tab + mode + close)
        // lives in TopBarPanel. The window stays draggable from its top edge.
        if (GetChild(1) is BoxContainer windowVBox && windowVBox.ChildCount > 0)
            windowVBox.GetChild(0).Visible = false;

        HeaderCloseButton.OnPressed += _ => Close();

        // Apply the modern flat button look to the XAML-defined buttons (per-instance, so it doesn't touch
        // the rest of the game's UI). Toggles get an accent-tinted selected state.
        // The Spawnlists / Tiles tabs act as mutually-exclusive page tabs (neither is greyed out).
        Modernize(TabSpawnlists, toggle: true);
        Modernize(TabTiles, toggle: true);
        TabSpawnlists.OnToggled += args =>
        {
            if (!args.Pressed) { TabSpawnlists.Pressed = true; return; } // can't deselect the active page
            SelectPage(MenuPage.Spawnlists);
        };
        TabTiles.OnToggled += args =>
        {
            if (!args.Pressed) { TabTiles.Pressed = true; return; }
            SelectPage(MenuPage.Tiles);
        };
        Modernize(HeaderCloseButton);
        Modernize(AdvancedDuplicatorButton);
        Modernize(PartnersButton);
        Modernize(ConstructionItemsEditorButton);
        Modernize(MassEntityEditorButton); // AU14: batch add-to-menu tool
        Modernize(TilesEditorButton);
        Modernize(LatheEditorButton);
        Modernize(SpawnlistDeleteButton); // AU14: delete a whole spawnlist and every recipe in it
        Modernize(ZLevelTogglesButton);
        Modernize(ZSyncListsButton); // AU14: z-level border reflection black/whitelist
        Modernize(ToolPermissionsButton); // AU14: Host-only per-ckey editor tool grants
        Modernize(InsforEditorButton);
        Modernize(BuildButton, toggle: true);
        Modernize(FavoriteButton);
        Modernize(EraseButton, toggle: true);
        Modernize(ClearButton);
        Modernize(TreeFavorites, toggle: true);
        Modernize(RecipeChangeButton);
        Modernize(RecipeRemoveButton);
        Modernize(SavedBuildDeleteButton);
        Modernize(SavedBuildFolderButton);
        Modernize(SavedBuildRenameButton);
        Modernize(SavedBuildRenameConfirm);

        // Admin recipe management (detail panel). Change Recipe opens the editor for the recipe's target
        // entity; Remove Item hides the recipe from the menu (works for vanilla recipes too).
        RecipeChangeButton.Text = Loc.GetString("gmod-construction-menu-change-recipe");
        RecipeRemoveButton.Text = Loc.GetString("gmod-construction-menu-remove-item");
        RecipeChangeButton.OnPressed += _ =>
        {
            if (_currentTargetEntityId is { } targetId)
                IoCManager.Resolve<IEntitySystemManager>()
                    .GetEntitySystem<CMU14.Construction.CustomConstruction.CustomConstructionEditorClientSystem>()
                    .RequestChangeRecipe(targetId);
        };
        RecipeRemoveButton.OnPressed += _ =>
        {
            if (_currentRecipeId is not { } recipeId)
                return;

            IoCManager.Resolve<IEntitySystemManager>()
                .GetEntitySystem<CMU14.Construction.CustomConstruction.CustomConstructionEditorClientSystem>()
                .HideRecipe(recipeId);
            CloseDetailPanel();
            // Repopulate so the just-hidden recipe disappears from the grid immediately.
            PopulateRecipes?.Invoke(this, (SearchBar.Text, _currentTreeCategory));
        };

        // Saved-build management (detail panel). Delete removes the selected build; the folder button opens
        // the saved-builds directory in the host OS file explorer.
        SavedBuildDeleteButton.Text = Loc.GetString("gmod-construction-menu-delete-build");
        SavedBuildFolderButton.Text = Loc.GetString("gmod-construction-menu-open-build-folder");
        SavedBuildRenameButton.Text = Loc.GetString("gmod-construction-menu-rename-build");

        // Rename: reveal an inline edit prefilled with the current name; confirm sends the rename to the server.
        SavedBuildRenameButton.OnPressed += _ =>
        {
            if (_currentSavedBuild is not { } saved)
                return;
            SavedBuildRenameEdit.Text = saved.Name;
            SavedBuildRenameRow.Visible = true;
            SavedBuildRenameButton.Visible = false;
        };
        SavedBuildRenameConfirm.OnPressed += _ =>
        {
            if (_currentSavedBuild is not { } saved)
                return;
            var newName = SavedBuildRenameEdit.Text.Trim();
            if (!string.IsNullOrEmpty(newName))
                _savedBuildList.Rename(saved.Id, newName);
            _currentSavedBuild = null;
            CloseDetailPanel();
            // The server replies with a refreshed list (ListUpdated -> PopulateSavedBuilds).
        };

        // Delete: two-click confirm so a stray click can't nuke a saved build.
        SavedBuildDeleteButton.OnPressed += _ =>
        {
            if (_currentSavedBuild is not { } saved)
                return;

            if (!_saveBuildDeleteArmed)
            {
                _saveBuildDeleteArmed = true;
                SavedBuildDeleteButton.Text = Loc.GetString("gmod-construction-menu-delete-build-confirm");
                return;
            }

            _savedBuildList.Delete(saved.Id);
            _currentSavedBuild = null;
            CloseDetailPanel();
        };
        SavedBuildFolderButton.OnPressed += _ => _savedBuildList.OpenFolder();

        // Recolor the static category headers (e.g. "Your Spawnlists", "Construction", "Admin Tools") to
        // the accent. Recipe-mode headers (built by the presenter) are recolored in FrameUpdate as they
        // appear; saved-build headers set their own accent color on creation.
        RecolorKeyLabels(TreePanel);
        RecolorKeyLabels(ToolsPanel);

        // The detail panel collapses smoothly; clip children while it is narrower than its content.
        DetailPanel.RectClipContent = true;

        // Preload the AU14 logo shown next to the AU14 spawnlist entry. (XAML cannot set Texture directly.)
        var cache = IoCManager.Resolve<IResourceCache>();
        try
        {
            _logoTexture = cache.GetResource<TextureResource>(LogoPath).Texture;
        }
        catch
        {
            // Missing texture is non-fatal; the label alone is fine.
        }

        // 🔧 TUNABLE: category sub-button font size (the default UI label is ~12; 10 reads as a sub-level).
        _categoryFont = cache.GetFont("/Fonts/NotoSans/NotoSans-Regular.ttf", 10);

        TreeFavorites.OnToggled += args =>
        {
            if (!args.Pressed)
            {
                if (_currentTreeCategory == FavoriteCatName)
                    TreeFavorites.Pressed = true;
                return;
            }

            // Favorites spans all spawnlists; deselect the spawnlist buttons and collapse their categories.
            foreach (var b in _spawnlistButtons.Values)
                b.Pressed = false;
            DeactivateSavedBuilds();
            CollapseAllCategories();

            _currentTreeCategory = FavoriteCatName;
            PopulateRecipes?.Invoke(this, (SearchBar.Text, FavoriteCatName));
        };

        SearchBar.OnTextChanged += _ =>
        {
            if (_savedBuildsActive)
                PopulateSavedBuilds();
            else
                PopulateRecipes?.Invoke(this, (SearchBar.Text, _currentTreeCategory));
        };

        BuildButton.Text = Loc.GetString("construction-menu-place-ghost");
        BuildButton.OnToggled += args =>
        {
            // Saved builds reuse the detail panel's Build button as a "Place" action (not a toggle).
            if (_currentSavedBuild is { } saved)
            {
                BuildButton.Pressed = false;
                if (args.Pressed)
                {
                    IoCManager.Resolve<IEntitySystemManager>()
                        .GetEntitySystem<SavedBuildPlacementSystem>()
                        .BeginPlacement(saved);
                    // Close the menu so the cursor is free to choose the placement location.
                    Close();
                }
                return;
            }

            BuildButtonToggled?.Invoke(this, args.Pressed);
        };

        EraseButton.Text = Loc.GetString("construction-menu-eraser-mode");
        EraseButton.OnToggled += args => EraseButtonToggled?.Invoke(this, args.Pressed);

        ClearButton.Text = Loc.GetString("construction-menu-clear-all");
        ClearButton.OnPressed += _ => ClearAllGhosts?.Invoke(this, EventArgs.Empty);

        FavoriteButton.OnPressed += _ =>
        {
            // For saved builds the Favorite button is repurposed as "Place at Original".
            if (_currentSavedBuild is { } saved)
            {
                IoCManager.Resolve<IEntitySystemManager>()
                    .GetEntitySystem<SavedBuildPlacementSystem>()
                    .PlaceAtOriginal(saved);
                Close();
                return;
            }

            RecipeFavorited?.Invoke(this, EventArgs.Empty);
        };

        // Admin/Player build-mode toggle. Admins default to instant/free placement, but can opt into the
        // player flow (vanilla construction ghosts + materials) - useful when admins are playing normally.
        // Non-admins can only ever build via ghosts, so the toggle is forced on and disabled for them.
        var adminMgr = IoCManager.Resolve<Administration.Managers.IClientAdminManager>();
        // Host flag only — general admin is no longer enough for the construction-menu editing tools.
        _isAdmin = adminMgr.HasFlag(Shared.Administration.AdminFlags.Host);
        _canEditMenu = _isAdmin
            || IoCManager.Resolve<Players.PlayTimeTracking.JobRequirementsManager>().IsWhitelisted(EditorWhitelistJob);

        // Build-mode dropdown: Player is always available; Admin needs the Spawn flag; Mapper needs Mapping
        // OR Spawn, so admins get the mapper ruleset too without needing a separate flag.
        // You can never select a mode you aren't authorized for (and the server re-validates regardless).
        ModeDropdown.AddItem(Loc.GetString("gmod-construction-menu-mode-player"), ModePlayerId);
        if (adminMgr.HasFlag(Shared.Administration.AdminFlags.Spawn))
            ModeDropdown.AddItem(Loc.GetString("gmod-construction-menu-mode-admin"), ModeAdminId);
        if (adminMgr.HasFlag(Shared.Administration.AdminFlags.Mapping) || adminMgr.HasFlag(Shared.Administration.AdminFlags.Spawn))
            ModeDropdown.AddItem(Loc.GetString("gmod-construction-menu-mode-mapper"), ModeMapperId);
        ModeDropdown.SelectId(ModePlayerId);
        ModeDropdown.OnItemSelected += args =>
        {
            ModeDropdown.SelectId(args.Id);
            ApplyBuildMode(args.Id);
        };
        ApplyBuildMode(ModePlayerId);

        // Partners (Construction category): manage who may include your builds in their saves.
        PartnersButton.OnPressed += _ =>
            IoCManager.Resolve<IEntitySystemManager>()
                .GetEntitySystem<CMU14.SavedBuilds.BuildPartnerClientSystem>()
                .OpenWindow();

        // Construction → AdvancedAtkinsonatorv2: opens the build-save selection window (save your builds).
        AdvancedDuplicatorButton.OnPressed += _ =>
        {
            IoCManager.Resolve<IEntitySystemManager>()
                .GetEntitySystem<Content.Client.CMU14.SavedBuilds.BuildSaveModeSystem>()
                .ToggleWindow();
            Close();
        };

        // Admin Tools → Construction Items Editor. Visible to everyone; the client system
        // pops up "not an admin" for non-admins and otherwise opens the entity selector → editor.
        ConstructionItemsEditorButton.OnPressed += _ =>
            IoCManager.Resolve<IEntitySystemManager>()
                .GetEntitySystem<CMU14.Construction.CustomConstruction.CustomConstructionEditorClientSystem>()
                .OpenItemsEditor();

        // Admin Tools → Tiles Editor (add a tile to the menu) and Lathe Editor (add a lathe print recipe).
        // AU14: Admin Tools -> Mass Entity Editor (multi-select entities, one recipe fanned out to all).
        MassEntityEditorButton.OnPressed += _ =>
            IoCManager.Resolve<IEntitySystemManager>()
                .GetEntitySystem<CMU14.Construction.CustomConstruction.CustomConstructionEditorClientSystem>()
                .OpenMassEditor();

        TilesEditorButton.OnPressed += _ =>
            IoCManager.Resolve<IEntitySystemManager>()
                .GetEntitySystem<CMU14.Construction.CustomConstruction.CustomConstructionEditorClientSystem>()
                .OpenTilesEditor();
        LatheEditorButton.OnPressed += _ =>
            IoCManager.Resolve<IEntitySystemManager>()
                .GetEntitySystem<CMU14.Construction.CustomConstruction.CustomConstructionEditorClientSystem>()
                .OpenLatheEditor();

        // AU14: Admin Tools -> Delete Spawnlist (wipes a spawnlist and every generated recipe in it).
        SpawnlistDeleteButton.OnPressed += _ =>
            IoCManager.Resolve<IEntitySystemManager>()
                .GetEntitySystem<CMU14.Construction.CustomConstruction.CustomConstructionEditorClientSystem>()
                .OpenSpawnlistDelete();

        // Admin Tools -> Z-Level Toggles (allow/deny z-level building per map, persisted across rounds).
        ZLevelTogglesButton.OnPressed += _ =>
            IoCManager.Resolve<IEntitySystemManager>()
                .GetEntitySystem<CMU14.Construction.CustomConstruction.CustomConstructionEditorClientSystem>()
                .OpenZLevelToggles();

        // AU14: Admin Tools -> Z-Sync Lists (which walls mirror across z-levels as map borders).
        ZSyncListsButton.OnPressed += _ =>
            IoCManager.Resolve<IEntitySystemManager>()
                .GetEntitySystem<CMU14.Construction.CustomConstruction.CustomConstructionEditorClientSystem>()
                .OpenZSyncLists();

        // AU14: Admin Tools -> Tool Permissions (Host-only per-ckey grants for the editor tools).
        ToolPermissionsButton.OnPressed += _ =>
            IoCManager.Resolve<IEntitySystemManager>()
                .GetEntitySystem<CMU14.Administration.ToolPermissionClientSystem>()
                .OpenManager();

        // INSFOR -> the faction editor. A server console command, so the server does all
        // authorization (host flag) and a server without the INSFOR feature simply reports an
        // unknown command.
        InsforEditorButton.OnPressed += _ =>
            IoCManager.Resolve<Robust.Shared.Console.IConsoleHost>().ExecuteCommand("insforeditor");
        // The Custom INSFOR editor was cancelled (too logically complicated); its button, command,
        // and flag pipeline were removed - see git history to resurrect them.

        // The spawnlist buttons (and initial selection) are built once the presenter calls SetSpawnlists.
    }

    // -------------------------------------------------------------------------
    // Spawnlist tree
    // -------------------------------------------------------------------------

    /// <summary>The spawnlist currently selected in the left tree.</summary>
    public string SelectedSpawnlist => _selectedSpawnlist;

    /// <summary>Rebuilds the left-tree spawnlist buttons from the presenter's discovered spawnlists.</summary>
    public void SetSpawnlists(IReadOnlyList<string> spawnlists)
    {
        _allSpawnlists = spawnlists;

        // Keep a valid selection for the Spawnlists page (never the Tiles-only entry).
        if (_selectedSpawnlist == TilesSpawnlist || !spawnlists.Contains(_selectedSpawnlist))
            _selectedSpawnlist = spawnlists.FirstOrDefault(s => s != TilesSpawnlist) ?? DefaultSpawnlist;

        BuildTree();

        // Reflect the current selection in the buttons without re-firing population.
        if (_currentPage == MenuPage.Tiles)
        {
            if (_spawnlistButtons.TryGetValue(TilesSpawnlist, out var tilesButton))
                tilesButton.Pressed = true;
            ExpandCategoriesFor(TilesSpawnlist);
        }
        else if (_currentTreeCategory == FavoriteCatName || _savedBuildsActive)
        {
            CollapseAllCategories();
        }
        else
        {
            foreach (var (name, button) in _spawnlistButtons)
                button.Pressed = name == _selectedSpawnlist;
            // Setting Button.Pressed never fires OnToggled, so expand the selection's categories explicitly.
            ExpandCategoriesFor(_selectedSpawnlist);
        }

        RecolorKeyLabels(TreePanel);
    }

    /// <summary>
    /// Rebuilds the left-tree contents for the current page: the Spawnlists page lists every spawnlist except
    /// Tiles (plus the synthetic Saved Builds entry and Favorites), while the Tiles page lists only Tiles.
    /// </summary>
    private void BuildTree()
    {
        SpawnlistContainer.RemoveAllChildren();
        _spawnlistButtons.Clear();
        _categoryContainers.Clear();
        _categoryButtons.Clear();
        _spawnlistArrowSetters.Clear();
        _expandedSpawnlist = null;
        _savedBuildsButton = null;

        if (_currentPage == MenuPage.Tiles)
        {
            // The "Z-Level (Experimental)" page gathers the Tiles and ZLevel spawnlists together.
            foreach (var spawnlist in _allSpawnlists)
            {
                if (!IsZLevelPageSpawnlist(spawnlist))
                    continue;

                AddSpawnlistRow(spawnlist);
            }

            // Favorites and Saved Builds belong to the Spawnlists page only.
            TreeFavorites.Visible = false;
            return;
        }

        foreach (var spawnlist in _allSpawnlists)
        {
            if (IsZLevelPageSpawnlist(spawnlist))
                continue;

            AddSpawnlistRow(spawnlist);
        }

        // Append the synthetic "Saved Builds" spawnlist (player-saved builds, not recipes).
        _savedBuildsButton = MakeSavedBuildsButton();
        SpawnlistContainer.AddChild(_savedBuildsButton);

        TreeFavorites.Visible = Array.IndexOf(_categories, FavoriteCatName) >= 0;
    }

    /// <summary>Flips between the Spawnlists and Tiles pages, rebuilding the tree and selecting a default.</summary>
    private void SelectPage(MenuPage page)
    {
        _currentPage = page;
        TabSpawnlists.Pressed = page == MenuPage.Spawnlists;
        TabTiles.Pressed = page == MenuPage.Tiles;

        _currentTreeCategory = ForAllCategoryName;
        TreeFavorites.Pressed = false;
        DeactivateSavedBuilds();

        BuildTree();
        RecolorKeyLabels(TreePanel);

        string target;
        if (page == MenuPage.Tiles)
        {
            // Prefer the ZLevel spawnlist on this page, falling back to Tiles or whatever is present.
            target = _spawnlistButtons.ContainsKey("ZLevel")
                ? "ZLevel"
                : (_spawnlistButtons.Keys.FirstOrDefault() ?? TilesSpawnlist);
        }
        else
        {
            target = _spawnlistButtons.ContainsKey(_selectedSpawnlist)
                ? _selectedSpawnlist
                : (_spawnlistButtons.Keys.FirstOrDefault() ?? DefaultSpawnlist);
        }

        _selectedSpawnlist = target;
        foreach (var (name, button) in _spawnlistButtons)
            button.Pressed = name == target;

        // Setting Button.Pressed never fires OnToggled, so expand the new selection's categories explicitly.
        ExpandCategoriesFor(target);

        PopulateRecipes?.Invoke(this, (SearchBar.Text, ForAllCategoryName));
    }

    private BaseButton MakeSpawnlistButton(string spawnlist)
    {
        // Only spawnlists that actually have categories get the collapse arrow (nothing to expand otherwise).
        var collapsible = CategoriesForSpawnlist(spawnlist).Count > 0;

        BaseButton button;
        if (spawnlist == DefaultSpawnlist && _logoTexture != null)
        {
            // AU14 gets the emblem next to its label. A ContainerButton has no stylesheet background of
            // its own (unlike a plain Button), so wrap the content in a PanelContainer to give it the same
            // themed, amber-framed background as the other spawnlist entries.
            var containerButton = new ContainerButton
            {
                ToggleMode = true,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 2),
            };

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(6, 4, 6, 4),
            };

            if (collapsible)
            {
                var arrow = new Label { Text = ArrowCollapsed, VerticalAlignment = Control.VAlignment.Center, Margin = new Thickness(0, 0, 4, 0) };
                row.AddChild(arrow);
                _spawnlistArrowSetters[spawnlist] = expanded => arrow.Text = expanded ? ArrowExpanded : ArrowCollapsed;
            }

            // Greyscale (desaturated) AU14 emblem - see GreyscaleTextureRect.
            row.AddChild(new GreyscaleTextureRect
            {
                Texture = _logoTexture,
                SetSize = new Vector2(18, 18),
                Margin = new Thickness(0, 0, 6, 0),
                VerticalAlignment = Control.VAlignment.Center,
            });
            row.AddChild(new Label { Text = spawnlist, VerticalAlignment = Control.VAlignment.Center });

            // Use the shared spawnlist color so the AU14 entry matches the other spawnlist buttons, and swap to
            // the selected tint on toggle (a ContainerButton has no stylesheet background of its own).
            var panel = new PanelContainer { PanelOverride = Panel(SpawnlistBg), Children = { row } };
            containerButton.AddChild(panel);
            containerButton.OnToggled += _ =>
                panel.PanelOverride = Panel(containerButton.Pressed ? SpawnlistSelected : SpawnlistBg);
            button = containerButton;
        }
        else
        {
            var plain = new Button
            {
                // The arrow prefixes the label; the setter rewrites just the glyph on expand/collapse.
                Text = collapsible ? $"{ArrowCollapsed} {spawnlist}" : spawnlist,
                ToggleMode = true,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 2),
            };
            // Shared spawnlist color (distinct from the neutral Saved Builds / Favorites buttons).
            Modernize(plain, toggle: true, SpawnlistBg, SpawnlistSelected);
            if (collapsible)
                _spawnlistArrowSetters[spawnlist] = expanded => plain.Text = $"{(expanded ? ArrowExpanded : ArrowCollapsed)} {spawnlist}";
            button = plain;
        }

        button.OnToggled += args =>
        {
            if (!args.Pressed)
            {
                // Re-clicking the active spawnlist collapses (or re-expands) its category list instead of
                // deselecting it - the spawnlist stays selected and its recipes stay shown.
                if (_selectedSpawnlist == spawnlist && _currentTreeCategory != FavoriteCatName)
                {
                    button.Pressed = true;
                    if (_expandedSpawnlist == spawnlist)
                        CollapseAllCategories();
                    else
                        ExpandCategoriesFor(spawnlist);
                }
                return;
            }

            _selectedSpawnlist = spawnlist;
            _currentTreeCategory = ForAllCategoryName;

            foreach (var (name, other) in _spawnlistButtons)
            {
                if (name != spawnlist)
                    other.Pressed = false;
            }
            TreeFavorites.Pressed = false;
            DeactivateSavedBuilds();

            // Expand this spawnlist's categories beneath it (and collapse the previously-open one).
            ExpandCategoriesFor(spawnlist);

            PopulateRecipes?.Invoke(this, (SearchBar.Text, ForAllCategoryName));
        };

        return button;
    }

    /// <summary>Adds one spawnlist button plus its (initially empty and hidden) category sub-list to the tree.</summary>
    private void AddSpawnlistRow(string spawnlist)
    {
        var button = MakeSpawnlistButton(spawnlist);
        _spawnlistButtons[spawnlist] = button;
        SpawnlistContainer.AddChild(button);

        var categoryBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Visible = false };
        _categoryContainers[spawnlist] = categoryBox;
        SpawnlistContainer.AddChild(categoryBox);
    }

    /// <summary>
    /// Expands the given spawnlist's categories beneath its button and collapses every other spawnlist's list.
    /// Called on both a user click and the programmatic selection paths (setting Button.Pressed does NOT fire
    /// OnToggled), so the categories stay in sync with the selected spawnlist however it was chosen.
    /// </summary>
    private void ExpandCategoriesFor(string spawnlist)
    {
        _categoryButtons.Clear();
        foreach (var (name, box) in _categoryContainers)
        {
            if (name == spawnlist)
                continue;

            box.Visible = false;
            box.RemoveAllChildren();
        }

        // Every other spawnlist's arrow points collapsed.
        foreach (var (name, setArrow) in _spawnlistArrowSetters)
        {
            if (name != spawnlist)
                setArrow(false);
        }

        if (!_categoryContainers.TryGetValue(spawnlist, out var container))
        {
            _expandedSpawnlist = null;
            return;
        }

        container.RemoveAllChildren();
        BuildCategoryButtons(spawnlist, container);

        var expanded = container.ChildCount > 0;
        container.Visible = expanded;
        _expandedSpawnlist = expanded ? spawnlist : null;
        if (_spawnlistArrowSetters.TryGetValue(spawnlist, out var setThis))
            setThis(expanded);

        RecolorKeyLabels(TreePanel);
    }

    /// <summary>Collapses every spawnlist's category sub-list (re-clicking the active spawnlist, or selecting
    /// Favorites / Saved Builds). Points every arrow back to collapsed.</summary>
    private void CollapseAllCategories()
    {
        _categoryButtons.Clear();
        _expandedSpawnlist = null;
        foreach (var box in _categoryContainers.Values)
        {
            box.Visible = false;
            box.RemoveAllChildren();
        }

        foreach (var setArrow in _spawnlistArrowSetters.Values)
            setArrow(false);
    }

    /// <summary>
    /// Fills a spawnlist's category sub-list: an "All" entry (selected by default, mirrors the spawnlist's own
    /// unfiltered view) followed by one button per category actually present in that spawnlist. A spawnlist with
    /// no categorized recipes gets no buttons, so the tree stays compact.
    /// </summary>
    private void BuildCategoryButtons(string spawnlist, BoxContainer container)
    {
        var categories = CategoriesForSpawnlist(spawnlist);
        if (categories.Count == 0)
            return;

        var allButton = MakeCategoryButton(Loc.GetString(ForAllCategoryName), ForAllCategoryName);
        allButton.Pressed = _currentTreeCategory == ForAllCategoryName;
        _categoryButtons[ForAllCategoryName] = allButton;
        container.AddChild(allButton);

        foreach (var (raw, display) in categories)
        {
            var button = MakeCategoryButton(display, raw);
            button.Pressed = _currentTreeCategory == raw;
            _categoryButtons[raw] = button;
            container.AddChild(button);
        }
    }

    private BaseButton MakeCategoryButton(string label, string categoryValue)
    {
        var button = new Button
        {
            Text = label,
            ToggleMode = true,
            HorizontalExpand = true,
            // Indented under the parent spawnlist so it reads as a child level.
            Margin = new Thickness(14, 0, 0, 2),
        };
        Modernize(button, toggle: true, CategoryBg, CategorySelected);
        // Smaller than the spawnlist label so the nesting reads at a glance.
        if (_categoryFont != null)
            button.Label.FontOverride = _categoryFont;

        button.OnToggled += args =>
        {
            if (!args.Pressed)
            {
                // Keep a selection at all times: re-clicking the active category is a no-op.
                if (_currentTreeCategory == categoryValue)
                    button.Pressed = true;
                return;
            }

            _currentTreeCategory = categoryValue;
            foreach (var (value, other) in _categoryButtons)
            {
                if (value != categoryValue)
                    other.Pressed = false;
            }

            PopulateRecipes?.Invoke(this, (SearchBar.Text, categoryValue));
        };

        return button;
    }

    /// <summary>
    /// The distinct categories present in a spawnlist, as (raw category value, localized display name) ordered
    /// by display name. Mirrors the presenter's spawnlist filter: the default "AU14" list spans every non
    /// z-level-page spawnlist (it is the "All" view), while any other spawnlist shows only its own recipes.
    /// </summary>
    private List<(string Raw, string Display)> CategoriesForSpawnlist(string spawnlist)
    {
        var raw = new HashSet<string>();
        foreach (var recipe in _prototypeManager.EnumerateCM<ConstructionPrototype>())
        {
            if (recipe.Hide || string.IsNullOrEmpty(recipe.Category))
                continue;

            var recipeSpawnlist = string.IsNullOrEmpty(recipe.Spawnlist) ? DefaultSpawnlist : recipe.Spawnlist;
            if (spawnlist == DefaultSpawnlist)
            {
                // The AU14 "All" view excludes the separate Z-Level page's spawnlists (see GetAndSortRecipes).
                if (IsZLevelPageSpawnlist(recipeSpawnlist))
                    continue;
            }
            else if (recipeSpawnlist != spawnlist)
            {
                continue;
            }

            raw.Add(recipe.Category);
        }

        return raw
            .Select(c => (Raw: c, Display: ConstructionLocalization.LocalizeOrRaw(c)))
            .OrderBy(c => c.Display, StringComparer.InvariantCulture)
            .ToList();
    }

    // -------------------------------------------------------------------------
    // Saved Builds spawnlist
    // -------------------------------------------------------------------------

    private BaseButton MakeSavedBuildsButton()
    {
        var button = new Button
        {
            Text = Loc.GetString("gmod-construction-menu-saved-builds"),
            ToggleMode = true,
            HorizontalExpand = true,
            Margin = new Thickness(0, 4, 0, 2),
        };
        Modernize(button, toggle: true);

        button.OnToggled += args =>
        {
            if (!args.Pressed)
            {
                if (_savedBuildsActive)
                    button.Pressed = true; // can't deselect the active list by re-clicking
                return;
            }

            foreach (var other in _spawnlistButtons.Values)
                other.Pressed = false;
            TreeFavorites.Pressed = false;
            CollapseAllCategories();

            _savedBuildsActive = true;
            _currentSavedBuild = null;
            CloseDetailPanel();
            _savedBuildList.Refresh();
            PopulateSavedBuilds();
        };

        return button;
    }

    // Build-mode dropdown item ids.
    private const int ModePlayerId = 0;
    private const int ModeAdminId = 1;
    private const int ModeMapperId = 2;

    /// <summary>Pushes the chosen build mode to both the placement system and the selection (save) system.</summary>
    private void ApplyBuildMode(int modeId)
    {
        var mode = modeId switch
        {
            ModeAdminId => BuildSaveMode.Admin,
            ModeMapperId => BuildSaveMode.Mapper,
            _ => BuildSaveMode.Player,
        };

        var sysMan = IoCManager.Resolve<IEntitySystemManager>();
        sysMan.GetEntitySystem<SavedBuildPlacementSystem>().Mode = mode;
        sysMan.GetEntitySystem<BuildSaveModeSystem>().Mode = mode;
    }

    private void DeactivateSavedBuilds()
    {
        _savedBuildsActive = false;
        _currentSavedBuild = null;
        if (_savedBuildsButton != null)
            _savedBuildsButton.Pressed = false;
    }

    private void OnSavedBuildListUpdated()
    {
        if (_savedBuildsActive)
            PopulateSavedBuilds();
    }

    /// <summary>Fills the center grid with saved-build cards grouped by source grid/map name.</summary>
    private void PopulateSavedBuilds()
    {
        GroupedRecipesContainer.RemoveAllChildren();

        var search = SearchBar.Text.Trim();
        var builds = _savedBuildList.Builds.Where(b =>
            string.IsNullOrEmpty(search) || b.Name.Contains(search, StringComparison.InvariantCultureIgnoreCase));

        var anyShown = false;
        foreach (var group in builds
                     .GroupBy(b => string.IsNullOrEmpty(b.Source) ? Loc.GetString("saved-build-unknown-source") : b.Source)
                     .OrderBy(g => g.Key, StringComparer.InvariantCultureIgnoreCase))
        {
            GroupedRecipesContainer.AddChild(new Label
            {
                Text = group.Key,
                StyleClasses = { "LabelKeyText" },
                FontColorOverride = Accent,
                Margin = new Thickness(2, 6, 0, 2),
            });

            var spriteSys = IoCManager.Resolve<IEntityManager>().System<Robust.Client.GameObjects.SpriteSystem>();

            var grid = new GridContainer { Columns = 1, HorizontalExpand = true };
            foreach (var build in group)
            {
                var info = build;

                // Card = a thumbnail of the build + its name/author/count, all inside one clickable button.
                var card = new ContainerButton { HorizontalExpand = true, Margin = new Thickness(0, 0, 0, 2) };
                var row = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    Margin = new Thickness(4, 2, 4, 2),
                };
                if (info.Preview is { Count: > 0 })
                {
                    row.AddChild(new SavedBuildThumbnail(info.Preview, spriteSys, 40f)
                    {
                        Margin = new Thickness(0, 0, 6, 0),
                        VerticalAlignment = Control.VAlignment.Center,
                    });
                }
                row.AddChild(new Label
                {
                    Text = Loc.GetString("saved-build-card",
                        ("name", info.Name), ("author", info.Author), ("count", info.EntityCount)),
                    VerticalAlignment = Control.VAlignment.Center,
                    HorizontalExpand = true,
                });
                card.AddChild(row);
                Modernize(card);
                card.OnPressed += _ => ShowSavedBuildDetail(info);
                grid.AddChild(card);
                anyShown = true;
            }

            GroupedRecipesContainer.AddChild(grid);
        }

        if (!anyShown)
        {
            GroupedRecipesContainer.AddChild(new Label
            {
                Text = Loc.GetString("saved-build-none"),
                Margin = new Thickness(4),
            });
        }
    }

    private void ShowSavedBuildDetail(SavedBuildInfo info)
    {
        _currentSavedBuild = info;

        TargetTexture.SetPrototype(null);
        TargetTexture.Modulate = Color.White;
        TargetName.SetMessage(info.Name);
        TargetDesc.SetMessage(Loc.GetString("saved-build-detail-desc",
            ("author", info.Author),
            ("count", info.EntityCount),
            ("source", string.IsNullOrEmpty(info.Source) ? Loc.GetString("saved-build-unknown-source") : info.Source)));
        RecipeStepList.Clear();
        ConstructionSkillInfo.Visible = false;
        FavoriteButton.Visible = true;
        FavoriteButton.Text = Loc.GetString("saved-build-place-original-button");
        BuildButton.Disabled = false;
        BuildButton.Pressed = false;
        BuildButton.Text = Loc.GetString("saved-build-place-button");

        // Saved-build detail: show Delete (server validates admin/author) and, for admins, the open-folder
        // button. Recipe-management buttons and the ghost erase/clear row don't apply to saved builds.
        _currentTargetEntityId = null;
        _currentRecipeId = null;
        RecipeChangeButton.Visible = false;
        RecipeRemoveButton.Visible = false;
        SavedBuildRenameButton.Visible = true;
        SavedBuildRenameRow.Visible = false;
        SavedBuildDeleteButton.Visible = true;
        _saveBuildDeleteArmed = false;
        SavedBuildDeleteButton.Text = Loc.GetString("gmod-construction-menu-delete-build");
        SavedBuildFolderButton.Visible = _isAdmin;
        GhostActionsRow.Visible = false;

        OpenDetailPanel();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
            _savedBuildList.ListUpdated -= OnSavedBuildListUpdated;
    }

    private int _lastGroupCount = -1;

    /// <summary>Recursively recolors every "LabelKeyText" category header under <paramref name="root"/> to the accent.</summary>
    private void RecolorKeyLabels(Control root)
    {
        foreach (var child in root.Children)
        {
            if (child is Label label && label.HasStyleClass("LabelKeyText"))
                label.FontColorOverride = Accent;
            RecolorKeyLabels(child);
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        // Recipe-mode category headers are built by the shared presenter (no callback), so recolor them
        // whenever the grouped grid's contents change.
        if (GroupedRecipesContainer.ChildCount != _lastGroupCount)
        {
            _lastGroupCount = GroupedRecipesContainer.ChildCount;
            RecolorKeyLabels(GroupedRecipesContainer);
        }

        if (Math.Abs(_detailCurrentWidth - _detailGoalWidth) < 0.5f)
        {
            _detailCurrentWidth = _detailGoalWidth;
            if (_detailGoalWidth <= 0f && DetailPanel.Visible)
                DetailPanel.Visible = false;
            return;
        }

        var step = DetailSlideSpeed * args.DeltaSeconds;
        if (_detailCurrentWidth < _detailGoalWidth)
            _detailCurrentWidth = Math.Min(_detailGoalWidth, _detailCurrentWidth + step);
        else
            _detailCurrentWidth = Math.Max(_detailGoalWidth, _detailCurrentWidth - step);

        DetailPanel.SetWidth = _detailCurrentWidth;
    }

    private void OpenDetailPanel()
    {
        DetailPanel.Visible = true;
        _detailGoalWidth = DetailTargetWidth;
    }

    private void CloseDetailPanel()
    {
        _detailGoalWidth = 0f;
    }

    // -------------------------------------------------------------------------
    // IConstructionMenuView - Categories
    // -------------------------------------------------------------------------

    /// <summary>
    /// When the presenter rebuilds categories, show/hide the Favorites tree entry
    /// depending on whether any favorites exist.
    /// </summary>
    public string[] Categories
    {
        get => _categories;
        set
        {
            _categories = value;
            // Favorites only exists on the Spawnlists page (and only when there are favorites to show).
            TreeFavorites.Visible = _currentPage == MenuPage.Spawnlists && Array.IndexOf(value, FavoriteCatName) >= 0;

            // If favorites disappeared while it was selected, fall back to the selected spawnlist.
            if (!TreeFavorites.Visible && _currentTreeCategory == FavoriteCatName)
            {
                _currentTreeCategory = ForAllCategoryName;
                if (_spawnlistButtons.TryGetValue(_selectedSpawnlist, out var button))
                {
                    button.Pressed = true;
                    ExpandCategoriesFor(_selectedSpawnlist);
                }
            }
        }
    }

    /// <summary>
    /// Adapter: the presenter populates this hidden OptionButton to track categories.
    /// It is never shown; the tree buttons drive navigation instead.
    /// </summary>
    public OptionButton OptionCategories => _stubOptionCategories;

    // -------------------------------------------------------------------------
    // IConstructionMenuView - View mode (always grouped grid)
    // -------------------------------------------------------------------------

    /// <summary>
    /// Always true - the gmod menu only uses the grid layout, so the presenter always
    /// routes through the grid population path rather than the list view.
    /// </summary>
    public bool GridViewButtonPressed
    {
        get => true;
        set { }
    }

    /// <summary>Always grouped - items are sub-categorized under per-category headers.</summary>
    public bool UseGroupedView => true;

    /// <summary>The menu closes as soon as a build/placement begins.</summary>
    public bool CloseOnConstruct => true;

    // -------------------------------------------------------------------------
    // IConstructionMenuView - Button states
    // -------------------------------------------------------------------------

    public bool EraseButtonPressed
    {
        get => EraseButton.Pressed;
        set => EraseButton.Pressed = value;
    }

    public bool BuildButtonPressed
    {
        get => BuildButton.Pressed;
        set => BuildButton.Pressed = value;
    }

    // -------------------------------------------------------------------------
    // IConstructionMenuView - Controls the presenter writes to
    // -------------------------------------------------------------------------

    /// <summary>
    /// Stub list container. The presenter calls PopulateList([]) on it in grid mode - harmless.
    /// </summary>
    public ListContainer Recipes => _stubRecipes;

    /// <summary>
    /// Stub flat grid. The grouped view uses <see cref="GroupedRecipesContainer"/> instead, but the
    /// interface requires a GridContainer; the presenter only clears this stub when grouped.
    /// </summary>
    public GridContainer RecipesGrid => _stubGrid;

    // RecipesGridScrollContainer, GroupedRecipesContainer and RecipeStepList are generated from the XAML
    // by [GenerateTypedNameReferences] (Access=Public) and satisfy the interface directly.

    // -------------------------------------------------------------------------
    // IConstructionMenuView - Events
    // -------------------------------------------------------------------------

    public event EventHandler<(string search, string catagory)>? PopulateRecipes;
    // Required by IConstructionMenuView; only used by the list-view path, which this menu never enters.
    public event EventHandler<ConstructionMenu.ConstructionMenuListData?>? RecipeSelected { add { } remove { } }
    public event EventHandler? RecipeFavorited;
    public event EventHandler<bool>? BuildButtonToggled;
    public event EventHandler<bool>? EraseButtonToggled;
    public event EventHandler? ClearAllGhosts;

    // -------------------------------------------------------------------------
    // IConstructionMenuView - Recipe display
    // -------------------------------------------------------------------------

    public void ClearRecipeInfo()
    {
        _currentSavedBuild = null;
        BuildButton.Disabled = true;
        TargetName.SetMessage(string.Empty);
        TargetDesc.SetMessage(string.Empty);
        TargetTexture.SetPrototype(null);
        TargetTexture.Modulate = Color.White;
        FavoriteButton.Visible = false;
        RecipeStepList.Clear();

        _currentTargetEntityId = null;
        _currentRecipeId = null;
        RecipeChangeButton.Visible = false;
        RecipeRemoveButton.Visible = false;
        SavedBuildDeleteButton.Visible = false;
        SavedBuildFolderButton.Visible = false;
        SavedBuildRenameButton.Visible = false;
        SavedBuildRenameRow.Visible = false;
        GhostActionsRow.Visible = true;

        CloseDetailPanel();
    }

    public void SetConstructionSkillInfo(int skillLevel, int discountPercent)
    {
        ConstructionSkillInfo.SetMessage(Loc.GetString("construction-menu-skill-info",
            ("skill", skillLevel),
            ("discount", discountPercent)),
            Color.FromHex("#72C7FF"));
        ConstructionSkillInfo.Visible = skillLevel > 0;
    }

    public void SetRecipeInfo(
        string name,
        string description,
        EntityPrototype? targetPrototype,
        Color iconColor,
        bool isItem,
        bool isFavorite,
        ConstructionPrototype prototype)
    {
        _currentSavedBuild = null;
        BuildButton.Disabled = false;
        BuildButton.Text = Loc.GetString(isItem ? "construction-menu-place-ghost" : "construction-menu-craft");
        TargetName.SetMessage(name);
        TargetDesc.SetMessage(description);
        TargetTexture.SetPrototype(targetPrototype?.ID);
        TargetTexture.Modulate = iconColor;
        FavoriteButton.Visible = true;
        FavoriteButton.Text = Loc.GetString(
            isFavorite ? "construction-add-favorite-button" : "construction-remove-from-favorite-button");

        // Recipe-mode detail: admins get Change Recipe / Remove Item for ANY recipe (vanilla included). The
        // saved-build management buttons stay hidden; the ghost erase/clear row is relevant here.
        _currentTargetEntityId = targetPrototype?.ID;
        _currentRecipeId = prototype.ID;
        RecipeChangeButton.Visible = _canEditMenu && _currentTargetEntityId != null;
        RecipeRemoveButton.Visible = _canEditMenu;
        SavedBuildDeleteButton.Visible = false;
        SavedBuildFolderButton.Visible = false;
        SavedBuildRenameButton.Visible = false;
        SavedBuildRenameRow.Visible = false;
        GhostActionsRow.Visible = true;

        OpenDetailPanel();

        // RMC14
        if (prototype.RMCPrototype != null)
            BuildButton.Text = Loc.GetString("rmc-construction-build-here");
    }

    public void ResetPlacement()
    {
        BuildButton.Pressed = false;
        EraseButton.Pressed = false;
    }
}
