- type: entity
  parent: RMCBaseMarineArmorLight
  id: AU14BaseArmor
  name: Example
  description: Standard Issue Armor used by many UA military organizations. Provides modest protection from bullet and melee attacks. It also has a shoulder-mounted directional flashlight for night time combat.
  abstract: true
  components:
  - type: Sprite
    sprite: _RMC14/Objects/Clothing/OuterClothing/Armor/m3/standard/padded/jungle.rsi
  - type: CMArmor
    melee: 35
    bullet: 20
    bio: 20
    explosionArmor: 15
  - type: RMCArmorSpeedTier
    speedTier: medium
  - type: ClothingSpeedModifier
    walkModifier: 0.666
    sprintModifier: 0.666
  - type: ExplosionResistance
    damageCoefficient: 0
    worn: false
  - type: Storage
    maxItemSize: Tiny
    grid:
    - 0,0,15,1
    blacklist:
      tags:
      - Pouch
  - type: LimitedStorage
    limits:
    - popup: rmc-storage-limit-cant-fit
      count: 2
      whitelist:
        components:
        - RMCFlask
        - CMScalpel
        - Figurine
        - CassettePlayer
        tags:
        #       - TODO RMC14 cards
        - Slice
        #       - TODO RMC14 glasses (eyewear)
        - Pen
        - Crayon
        - RMCHandful
        - Flashlight
        - Brutepack
        - CMOintment
        - CMAutoInjector
        - PillPacket
        - Syringe
        - Pill
  - type: ContainerContainer
    containers:
      storagebase: !type:Container
        ents: [ ]
  - type: UserInterface
    interfaces:
      enum.StorageUiKey.Key:
        type: StorageBoundUserInterface
  - type: IgnoreContentsSize
    items:
      components:
      - RMCLighter
      - RMCFlask
      - CMScalpel
      - Figurine
      - Matchbox
      - OuterClothingAccessory
      - CassettePlayer
      - CassetteTape
      tags:
      - CigPack
      - Cigarette
      #      - TODO RMC14 cards
      - Slice
      #      - TODO RMC14 glasses (eyewear)
      - Pen
      - Crayon
      - RMCHandful
      - Flashlight
      - Brutepack
      - CMOintment
      - CMAutoInjector
      - PillPacket
  - type: FixedItemSizeStorage
  - type: Appearance
  - type: OuterClothingAccessoryHolder

- type: entity
  parent: CMHandsBlackMarine
  id: AU14GlovesBase
  name: armored gloves
  description: Non-standard kevlon fiber gloves. They're insulated and heavily armored.
  abstract: true
  components:
  - type: Sprite
    sprite: _RMC14/Objects/Clothing/Hands/Gloves/veteran.rsi
  - type: Clothing
    sprite: _RMC14/Objects/Clothing/Hands/Gloves/veteran.rsi
  - type: CMArmor
    melee: 40
    bullet: 40
    explosionArmor: 20
  - type: Insulated
