- type: reagent
  id: RMCDrinkBase
  parent: CMReagent
  group: Drinks
  abstract: true
  color: "#E78108"
  unknown: true
  metabolisms:
    Digestion:
      metabolismRate: 0.2
      effects:
      - !type:Satiate
        satiationType: Hunger
        factor: 0.125
      - !type:Satiate #Unparity but as long as we have thirst might as well - half as effective as water
        satiationType: Thirst
        factor: 0.4
