- type: job
  parent: CMJobBase
  id: CMUJobRaiderLeader
  roundSide: ThirdParty
  roundForce: CMURaiders
  roundRole: RaiderLeader
  roundComponents:
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: spp_pvt
  - type: Skills
    skills:
      RMCSkillEndurance: 3
      RMCSkillFirearms: 3
      RMCSkillCqc: 2
      RMCSkillLeadership: 2
      RMCSkillJtac: 1
  - type: JobPrefix
    prefix: cmu-raider-prefix-leader
  name: cmu-raider-name-leader
  description: cmu-raider-description
  playTimeTracker: CMUJobRaiderLeader
  ranks:
    RMCRankCivilian: []
  startingGear: CMUGearRaiderLeader
  spawnMenuRoleName: Free Company Raider Leader (3rd party)
  greeting: cmu-raider-greeting
  icon: RMCJobIconMarineRaiderLeader
  joinNotifyCrew: false
  supervisors: cmu-raider-leader
  accessGroups:
  - Colonist
  hidden: false

- type: entity
  parent: CMUBaseMobSpeciesRaiders
  id: CMUJobRaiderLeader
  name: Free Company Raider Leader
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: cmu-raider-name-leader
    description: cmu-raider-description
    reregister: false
    job: CMUJobRaiderLeader
    raffle:
      settings: short
    rules: cmu-raider-rules

- type: startingGear
  id: CMUGearRaiderLeader
  equipment:
    head: RMCArmorHelmetMARSOC
    mask: RMCMaskBalaclavaMARSOC
    ears: RMCHeadsetMARSOC
    jumpsuit: CMUJumpsuitRaiderWebbingBuckshot
    outerClothing: CMUArmorRaiderXM40
    gloves: CMHandsBlackMarine
    shoes: CMBootsBlackFilled
    suitstorage: CMUWeaponRifleXM40Raider
    id: CMUIDCardRaiderLeader
    belt: RMCWeaponShotgunXM38Filled
    back: CMUSatchelRaider
    pocket1: RMCPouchMedicalSocMarineRaiderFill
    pocket2: RMCPouchToolsSocMarineRaiderFill

- type: playTimeTracker
  id: CMUJobRaiderLeader
