using Content.Shared.CMU14.ColonyEconomy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.ColonyEconomy;

[GenerateTypedNameReferences]
public sealed partial class AdminConsoleWindow : DefaultWindow
{
    public AdminConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(AdminConsoleBuiState state)
    {
        ColonyBudgetLabel.Text = Loc.GetString("admin-console-colony-budget", ("amount", $"{state.ColonyBudget:F0}"));
        CurrentTaxLabel.Text = Loc.GetString("admin-console-current-sales-tax", ("percent", $"{state.SalesTaxPercent:F0}"));
        TaxInput.Text = $"{state.SalesTaxPercent:F0}";
        CurrentIncomeTaxLabel.Text = Loc.GetString("admin-console-current-income-tax", ("percent", $"{state.IncomeTaxPercent:F0}"));
        IncomeTaxInput.Text = $"{state.IncomeTaxPercent:F0}";
        UpdateEconomyStatus(state.EconomyStatus);
    }

    private void UpdateEconomyStatus(EconomyStatusState econ)
    {
        EconomyStatusPanel.RemoveAllChildren();
        EconomyStatusPanel.AddChild(new Label
        {
            Text = Loc.GetString("colony-economy-sales-tax", ("percent", $"{econ.SalesTaxPercent:F0}")),
        });
        EconomyStatusPanel.AddChild(new Label
        {
            Text = Loc.GetString("colony-economy-income-tax", ("percent", $"{econ.IncomeTaxPercent:F0}")),
        });
        EconomyStatusPanel.AddChild(new Label
        {
            Text = Loc.GetString("colony-economy-transit-tariff", ("percent", $"{econ.TransitTariffPercent:F0}")),
        });

        if (econ.ActiveEmbargoes.Count > 0)
        {
            EconomyStatusPanel.AddChild(new Label
            {
                Text = Loc.GetString("colony-economy-active-embargoes", ("factions", string.Join(", ", econ.ActiveEmbargoes))),
                StyleClasses = { "Caution" },
            });
        }
        else
        {
            EconomyStatusPanel.AddChild(new Label
            {
                Text = Loc.GetString("colony-economy-no-embargoes"),
                StyleClasses = { "LabelSubText" },
            });
        }

        if (econ.ActiveTradePacts.Count > 0)
        {
            EconomyStatusPanel.AddChild(new Label
            {
                Text = Loc.GetString("colony-economy-active-trade-pacts", ("factions", string.Join(", ", econ.ActiveTradePacts))),
            });
        }
        else
        {
            EconomyStatusPanel.AddChild(new Label
            {
                Text = Loc.GetString("colony-economy-no-trade-pacts"),
                StyleClasses = { "LabelSubText" },
            });
        }
    }
}
