using System.Linq;
using Content.Shared.CMU14.ColonyEconomy;
using Content.Shared.Mobs;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.CMU14.ColonyEconomy;

[GenerateTypedNameReferences]
public sealed partial class AU14ShopkeeperVendorWindow : DefaultWindow
{
    public event Action<int>? OnBuyPressed;
    public event Action<int, string, int>? OnSaveListing;
    public event Action<int>? OnSaveDefaultPrice;
    public event Action<int>? OnRemoveListing;

    private readonly IPrototypeManager _proto;
    private readonly SpriteSystem _sprite;

    public AU14ShopkeeperVendorWindow()
    {
        RobustXamlLoader.Load(this);
        _proto = IoCManager.Resolve<IPrototypeManager>();
        _sprite = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();
    }

    public void UpdateState(AU14ShopkeeperVendorShopState state, bool isShopkeeper)
    {
        InsertedCashLabel.Text = $"Inserted: ${state.InsertedCash:F0}";
        SalesTaxLabel.Text = state.SalesTaxPercent > 0
            ? $"Sales Tax: {state.SalesTaxPercent:F0}% (included in prices)"
            : "No sales tax";
        // -- Shop section (visible to everyone) --
        ItemList.RemoveAllChildren();
        if (state.Listings.Count == 0)
        {
            ItemList.AddChild(new Label { Text = "No items for sale." });
        }
        else
        {
            foreach (var item in state.Listings)
            {
                var row = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    SeparationOverride = 4,
                    HorizontalExpand = true
                };

                // Sprite icon
                if (item.ItemProtoId != null && _proto.TryIndex<EntityPrototype>(item.ItemProtoId, out var proto))
                {
                    var icon = new LayeredTextureRect
                    {
                        MinSize = new System.Numerics.Vector2(32, 32),
                        VerticalAlignment = VAlignment.Center,
                        Textures = _sprite.GetPrototypeTextures(proto)
                            .Select(o => o.Default)
                            .ToList()
                    };
                    row.AddChild(icon);
                }
                else
                {
                    row.AddChild(new Control { MinSize = new System.Numerics.Vector2(32, 32) });
                }

                var countText = item.Count > 1 ? $" x{item.Count}" : "";
                row.AddChild(new Label
                {
                    Text = $"{item.DisplayName}{countText}",
                    HorizontalExpand = true,
                    ClipText = true,
                    SizeFlagsStretchRatio = 3
                });
                row.AddChild(new Label
                {
                    Text = $"${item.EffectivePrice}",
                    MinWidth = 50,
                    HorizontalAlignment = HAlignment.Right
                });
                var btn = new Button { Text = "Buy", MinWidth = 50 };
                var idx = item.Index;
                btn.Disabled = state.InsertedCash < item.EffectivePrice;
                btn.OnPressed += _ => OnBuyPressed?.Invoke(idx);
                row.AddChild(btn);
                ItemList.AddChild(row);
            }
        }
        ReturnChangeBtn.Disabled = state.InsertedCash <= 0;
        // -- Manage section (only for shopkeepers) --
        ManageSection.Visible = isShopkeeper;
        if (!isShopkeeper)
            return;
        
        DefaultPriceLineEdit.Text = $"{state.DefaultPrice:F0}";
        DefaultPriceLineEdit.OnTextChanged += args =>
        {
            var newText = args.Text;
            var lineEdit = args.Control;

            if (!int.TryParse(args.Text, out var curDefaultPrice))
            {
                lineEdit.SetText($"{state.DefaultPrice:F0}");
                return;
            }

            SaveDefaultPriceBtn.Disabled = curDefaultPrice == state.DefaultPrice;
        };

        SaveDefaultPriceBtn.Disabled = true;
        SaveDefaultPriceBtn.OnPressed += args =>
        {
            if(!int.TryParse(DefaultPriceLineEdit.Text.Trim(), out var newDefaultPrice))
            {
                return;
            }
            OnSaveDefaultPrice?.Invoke(newDefaultPrice);
        };

        ManageList.RemoveAllChildren();
        if (state.Listings.Count == 0)
        {
            ManageList.AddChild(new Label
            {
                Text = "No stock. Use an item on this machine to add it.",
                StyleClasses = { "LabelSubText" }
            });
            return;
        }
        foreach (var listing in state.Listings)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4
            };
            var nameEdit = new LineEdit
            {
                Text = listing.DisplayName,
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 3,
                PlaceHolder = "Item name..."
            };
            var priceEdit = new LineEdit
            {
                Text = listing.BasePrice.ToString(),
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 1,
                PlaceHolder = "Price"
            };
            var saveBtn = new Button { Text = "Save" };
            var removeBtn = new Button { Text = "Remove", StyleClasses = { "Caution" } };
            var idxCopy = listing.Index;
            saveBtn.OnPressed += _ =>
            {
                var name = nameEdit.Text.Trim();
                if (string.IsNullOrWhiteSpace(name)) name = listing.DisplayName;
                if (!int.TryParse(priceEdit.Text, out var price) || price < 1) price = listing.BasePrice;
                OnSaveListing?.Invoke(idxCopy, name, price);
            };
            removeBtn.OnPressed += _ => OnRemoveListing?.Invoke(idxCopy);
            row.AddChild(nameEdit);
            row.AddChild(new Label { Text = "$" });
            row.AddChild(priceEdit);
            row.AddChild(saveBtn);
            row.AddChild(removeBtn);
            var countText = listing.Count > 1 ? $" ({listing.Count} in stock)" : "";
            var taxHint = new Label
            {
                Text = $"  sells for ${listing.EffectivePrice} (after tax){countText}",
                StyleClasses = { "LabelSubText" },
                Margin = new Robust.Shared.Maths.Thickness(4, 0, 0, 4)
            };
            var entryBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };
            entryBox.AddChild(row);
            entryBox.AddChild(taxHint);
            ManageList.AddChild(entryBox);
        }
    }
}
