using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.ColonyEconomy;

[GenerateTypedNameReferences]
public sealed partial class ColonyAtmWindow : DefaultWindow
{
    public ColonyAtmWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

