using Content.Shared.CMU14.ColonyEconomy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.ColonyEconomy;

[GenerateTypedNameReferences]
public sealed partial class CorporateConsoleWindow : DefaultWindow
{
    public CorporateConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(CorporateConsoleBuiState state)
    {
        CorporateBudgetLabel.Text = Loc.GetString("corporate-console-budget", ("amount", $"{state.CorporateBudget:F0}"));
        CurrentTariffLabel.Text = Loc.GetString("corporate-console-current-transit-tariff", ("percent", $"{state.TransitTariffPercent:F0}"));
        TariffInput.Text = $"{state.TransitTariffPercent:F0}";

        var incomeTax = state.EconomyStatus.IncomeTaxPercent;
        WithdrawTaxNote.Text = incomeTax > 0
            ? Loc.GetString("corporate-console-withdraw-tax-note", ("percent", $"{incomeTax:F0}"))
            : Loc.GetString("corporate-console-withdraw-no-tax");

        UpdateEconomyStatus(state.EconomyStatus);
    }

    private void UpdateEconomyStatus(EconomyStatusState econ)
    {
        EconomyStatusPanel.RemoveAllChildren();
        EconomyStatusPanel.AddChild(new Label
        {
            Text = Loc.GetString("colony-economy-sales-tax", ("percent", $"{econ.SalesTaxPercent:F0}")),
        });
        EconomyStatusPanel.AddChild(new Label
        {
            Text = Loc.GetString("colony-economy-income-tax", ("percent", $"{econ.IncomeTaxPercent:F0}")),
        });
        EconomyStatusPanel.AddChild(new Label
        {
            Text = Loc.GetString("colony-economy-transit-tariff", ("percent", $"{econ.TransitTariffPercent:F0}")),
        });

        if (econ.ActiveEmbargoes.Count > 0)
        {
            EconomyStatusPanel.AddChild(new Label
            {
                Text = Loc.GetString("colony-economy-active-embargoes", ("factions", string.Join(", ", econ.ActiveEmbargoes))),
                StyleClasses = { "Caution" },
            });
        }
        else
        {
            EconomyStatusPanel.AddChild(new Label
            {
                Text = Loc.GetString("colony-economy-no-embargoes"),
                StyleClasses = { "LabelSubText" },
            });
        }

        if (econ.ActiveTradePacts.Count > 0)
        {
            EconomyStatusPanel.AddChild(new Label
            {
                Text = Loc.GetString("colony-economy-active-trade-pacts", ("factions", string.Join(", ", econ.ActiveTradePacts))),
            });
        }
        else
        {
            EconomyStatusPanel.AddChild(new Label
            {
                Text = Loc.GetString("colony-economy-no-trade-pacts"),
                StyleClasses = { "LabelSubText" },
            });
        }
    }
}
