using Content.Client._RMC14.Commendations;
using Content.Client._RMC14.RMCPlaytimeStats;
using Content.Client.Info;
using Content.Client.Info.PlaytimeStats;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI
{
    /// <summary>
    /// Holds the entire character setup GUI, from character picks to individual character editing.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class CharacterSetupGui : Control
    {
        [Dependency] private IClientPreferencesManager _preferencesManager = default!;
        [Dependency] private IPrototypeManager _protomanager = default!;
        [Dependency] private IConfigurationManager _cfg = default!;
        [Dependency] private IStylesheetManager _stylesheetManager = default!;
        [Dependency] private ISharedPlayerManager _playerManager = default!;

        private readonly Button _createNewCharacterButton;
        private bool _cvarSubscriptionsActive;

        public event Action<int>? SelectCharacter;
        public event Action<int>? DeleteCharacter;

        public CharacterSetupGui(HumanoidProfileEditor profileEditor)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            ApplyCrtPalette();

            _createNewCharacterButton = new Button
            {
                Text = Loc.GetString("character-setup-gui-create-new-character-button"),
                StyleClasses = { StyleNano.StyleClassCrtButton }
            };

            _createNewCharacterButton.OnPressed += args =>
            {
                _preferencesManager.CreateCharacter(HumanoidCharacterProfile.Random().WithJobFromCvar(_cfg));
                ReloadCharacterPickers();
                args.Event.Handle();
            };

            CharEditor.AddChild(profileEditor);
            CrtLobbyTheme.Apply(this);
            RulesButton.OnPressed += _ => new RulesAndInfoWindow().Open();

            StatsButton.OnPressed += _ => new RMCPlaytimeStatsWindow().OpenCentered(); // RMC-PlaytimeStats-Tweak

            CommendationsReceivedButton.OnPressed += _ =>
                IoCManager.Resolve<CommendationsManager>().OpenReceivedWindow();
            CommendationsGivenButton.OnPressed += _ =>
                IoCManager.Resolve<CommendationsManager>().OpenGivenWindow();

            _cfg.OnValueChanged(CCVars.SeeOwnNotes, OnSeeOwnNotesChanged, true);
            _cfg.OnValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
            _cfg.OnValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
            _cfg.OnValueChanged(CCVars.GameMaxCharacterSlots, OnGameMaxCharacterSlotsChanged);
            _cvarSubscriptionsActive = true;
        }

        [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            Shutdown();
        }

        /// <summary>
        /// Releases global configuration subscriptions before this control is orphaned.
        /// </summary>
        internal void Shutdown()
        {
            if (!_cvarSubscriptionsActive)
                return;

            _cfg.UnsubValueChanged(CCVars.SeeOwnNotes, OnSeeOwnNotesChanged);
            _cfg.UnsubValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
            _cfg.UnsubValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
            _cfg.UnsubValueChanged(CCVars.GameMaxCharacterSlots, OnGameMaxCharacterSlotsChanged);
            _cvarSubscriptionsActive = false;
        }

        private void OnSeeOwnNotesChanged(bool visible)
        {
            AdminRemarksButton.Visible = visible;
        }

        private void OnGameMaxCharacterSlotsChanged(int _)
        {
            ReloadCharacterPickers();
        }

        private void OnCrtUiEnabledChanged(bool _)
        {
            ApplyCrtPalette();
            CrtLobbyTheme.Apply(this);
        }

        private void OnCrtUiColorChanged(string _)
        {
            ApplyCrtPalette();
        }

        private void ApplyCrtPalette()
        {
            Stylesheet = _stylesheetManager.SheetNano;
            BackgroundPanel.PanelOverride = CreateBackgroundStyleBox();
            HeaderDividerPanel.PanelOverride = CreateDividerStyleBox();
            BodyDividerPanel.PanelOverride = CreateDividerStyleBox();
        }

        private static CrtStyleBox CreateBackgroundStyleBox()
        {
            return new CrtStyleBox
            {
                BackgroundColor = StyleNano.CrtBackground,
                BorderColor = StyleNano.CrtGreenDim,
                CornerColor = StyleNano.CrtGreen.WithAlpha(0.18f),
                BorderThickness = new Thickness(1),
                CornerLength = 16,
            };
        }

        private static StyleBoxFlat CreateDividerStyleBox()
        {
            return new StyleBoxFlat
            {
                BackgroundColor = StyleNano.CrtGreenDim,
                ContentMarginTopOverride = 2
            };
        }

        /// <summary>
        /// Disposes and reloads all character picker buttons from the preferences data.
        /// </summary>
        public void ReloadCharacterPickers()
        {
            _createNewCharacterButton.Orphan();
            Characters.RemoveAllChildren();

            var numberOfFullSlots = 0;
            var characterButtonsGroup = new ButtonGroup();

            if (!_preferencesManager.ServerDataLoaded)
            {
                return;
            }

            var maxCharactersSlots = _cfg.GetCVar(CCVars.GameMaxCharacterSlots);

            _createNewCharacterButton.ToolTip =
                Loc.GetString("character-setup-gui-create-new-character-button-tooltip",
                    ("maxCharacters", maxCharactersSlots));

            var selectedSlot = _preferencesManager.Preferences?.SelectedCharacterIndex;

            foreach (var (slot, character) in _preferencesManager.Preferences!.Characters)
            {
                numberOfFullSlots++;
                var characterPickerButton = new CharacterPickerButton(_protomanager,
                    _playerManager,
                    characterButtonsGroup,
                    character,
                    slot == selectedSlot);

                if (slot >= maxCharactersSlots)
                {
                    characterPickerButton.SetOnlyStyleClass(ContainerButton.StylePseudoClassDisabled);
                    characterPickerButton.ToolTip =
                        Loc.GetString("character-setup-gui-create-new-character-button-tooltip",
                                      ("maxCharacters", maxCharactersSlots));
                }

                Characters.AddChild(characterPickerButton);

                characterPickerButton.OnPressed += args =>
                {
                    SelectCharacter?.Invoke(slot);
                };

                characterPickerButton.OnDeletePressed += () =>
                {
                    DeleteCharacter?.Invoke(slot);
                };
            }

            _createNewCharacterButton.Disabled = numberOfFullSlots >= maxCharactersSlots;
            Characters.AddChild(_createNewCharacterButton);
        }
    }
}
