using Content.Client.Stylesheets;
using Robust.Client.ResourceManagement;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyCharacterPreviewPanel : Control
{
    [Dependency] private IResourceCache _resourceCache = default!;

    public Button CharacterSetupButton => CharacterSetup;
    public Button LinkAccountButtonControl => LinkAccountButton;
    public Button PrevCharacterButton => PrevCharButton;
    public Button NextCharacterButton => NextCharButton;
    public Button IgnoreAllegianceToggle => IgnoreAllegianceButton;

    /// <summary>
    ///     Must match the size the CrtCharacterSummary style rule uses, or the one-line clamp on the
    ///     name is measured against the wrong font.
    /// </summary>
    private const int CharacterSummaryFontSize = 9;


    public LobbyCharacterPreviewPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        RefreshTheme();

        UpdateIgnoreAllegianceText(IgnoreAllegianceButton.Pressed);
        IgnoreAllegianceButton.OnToggled += args => UpdateIgnoreAllegianceText(args.Pressed);
    }

    public void RefreshTheme()
    {
        // The CRT theme styles every button label at one size via a stylesheet rule. FontOverride
        // is the reliable way to make just this one bigger - another style class would tie with
        // that rule on specificity.
        IgnoreAllegianceButton.Label.FontOverride = StyleNano.CrtUiEnabled
            ? StyleNano.GetCrtFont(_resourceCache, 10)
            : null;

        // Base menu only: toggled on turns the button solid red. The default Pressed state for a
        // plain Button is a thin highlighted border, easy to miss at a glance for something that
        // changes spawn behaviour. The CRT theme already themes every button consistently through
        // CrtButton, so this is left alone there.
        if (!StyleNano.CrtUiEnabled)
            IgnoreAllegianceButton.AddStyleClass(StyleNano.StyleClassButtonToggleRed);
        else
            IgnoreAllegianceButton.RemoveStyleClass(StyleNano.StyleClassButtonToggleRed);
    }

    private void UpdateIgnoreAllegianceText(bool pressed)
    {
        IgnoreAllegianceButton.Text = Loc.GetString(pressed
            ? "lobby-character-preview-ignore-allegiance-on"
            : "lobby-character-preview-ignore-allegiance-off");
    }

    public void SetLoaded(bool value)
    {
        Loaded.Visible = value;
        Unloaded.Visible = !value;
    }

    /// <summary>
    ///     Sets the two-line character summary. Both lines are markup so the name, pronoun and age
    ///     can be coloured; see the lobby-character-summary-* locale keys.
    /// </summary>
    public void SetSummaryText(string nameMarkup, string ageMarkup)
    {
        ClampNameToOneLine();
        SetSummaryLine(SummaryName, nameMarkup);
        SetSummaryLine(SummaryAge, ageMarkup);
    }

    /// <summary>
    ///     The summary column is a fixed share of the panel, so an over-long name wraps instead of
    ///     shoving the sprite sideways. Cap it at a single line and let the rest clip: names are
    ///     bounded in length anyway, and a second line would push the age, job line and toggle down.
    /// </summary>
    private void ClampNameToOneLine()
    {
        // Only meaningful for the CRT font, which is the one the CrtCharacterSummary rule applies.
        // Without CRT the label keeps NanoUI's font and is left to wrap as before.
        if (!StyleNano.CrtUiEnabled)
            return;

        // Read the scale off the control rather than repeating the stylesheet's value - this runs
        // when a profile loads, long after styles have resolved.
        var lineHeight = StyleNano.GetCrtFont(_resourceCache, CharacterSummaryFontSize)
            .GetLineHeight(1f);

        // Height is capped to one line so a long name cannot push the rest of the block down. The
        // width cap that used to sit beside this is gone: it made the name *wrap*, and this cap then
        // hid the wrapped line - so "Zachary Thompson" rendered as "Zachary". The stats column that
        // cap was protecting no longer exists, so there is nothing left to protect.
        SummaryName.MaxHeight = lineHeight * SummaryName.LineHeightScale;

    }

    private static void SetSummaryLine(RichTextLabel label, string markup)
    {
        if (string.IsNullOrWhiteSpace(markup))
        {
            label.SetMessage(FormattedMessage.Empty);
            label.Visible = false;
            return;
        }

        label.SetMessage(FormattedMessage.FromMarkupOrThrow(markup));
        label.Visible = true;
    }

    public void SetJobText(string value)
    {
        JobSummary.Text = value;
        JobSummary.Visible = !string.IsNullOrWhiteSpace(value);
    }

    public void SetSprite(EntityUid uid)
    {
        ProfilePreviewSpriteView.ClearPreview();
        ProfilePreviewSpriteView.PreviewDummy = uid;
        ProfilePreviewSpriteView.SetEntity(uid);
    }
}
