# Military round job profiles for this role family.

- type: roundJobProfile
  id: AU14RoundJobProfileMilitaryBase
  components:
  - type: MarineOrders
  - type: RMCAwardRecommendation
  sideComponents:
    Govfor:
    - type: Marine
      Faction: govfor
    - type: UserIFF
      factions:
      - GOVFOR
    - type: NpcFactionMember
      factions:
      - GOVFOR
    Opfor:
    - type: Marine
      Faction: opfor
    - type: UserIFF
      factions:
      - OPFOR
    - type: NpcFactionMember
      factions:
      - OPFOR
  forceComponents:
    WYPMC:
    - type: UserIFF
      factions:
      - FactionWEYU
    - type: NpcFactionMember
      factions:
      - AUWeYu

- type: roundJobProfile
  parent: AU14RoundJobProfileMilitaryBase
  id: AU14RoundJobProfileSquadRifleman

- type: roundJobProfile
  id: AU14RoundJobProfileWorkingJoe
  sideComponents:
    Govfor:
    - type: UserIFF
      factions:
      - GOVFOR
    - type: IntrinsicRadioTransmitter
      channels:
      - radioAI
      - radioGovforCommand
      - radioGovforJTAC
      - radioGovforAlpha
      - radioGovforCharlie
      - radioGovforBravo
      - radioGovforIntel
      - radioGovforMILP
    - type: ActiveRadio
      channels:
      - radioAI
      - radioGovforCommand
      - radioGovforJTAC
      - radioGovforAlpha
      - radioGovforCharlie
      - radioGovforBravo
      - radioGovforIntel
      - radioGovforMILP
    - type: Tag
      tags:
      - WorkingJoe
      - CanPilot
      - FootstepSound
      - DoorBumpOpener
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/CMU14/Interface/au14govforjobicons.rsi
        state: working_joe
    - type: Language
      preset: AU14LanguagePresetSynth
    - type: LanguageLearning
      preset: AU14LanguageLearningPresetSynth
    Opfor:
    - type: UserIFF
      factions:
      - OPFOR
    - type: IntrinsicRadioTransmitter
      channels:
      - radioAI
      - radioOpforAlpha
      - radioOpforCommand
      - radioOpforCharlie
      - radioOpforBravo
      - radioOpforIntel
      - radioOpforJTAC
    - type: ActiveRadio
      channels:
      - radioAI
      - radioOpforAlpha
      - radioOpforCommand
      - radioOpforCharlie
      - radioOpforBravo
      - radioOpforIntel
      - radioOpforJTAC
    - type: Tag
      tags:
      - WorkingJoe
      - CanPilot
      - FootstepSound
      - DoorBumpOpener
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/CMU14/Interface/au14opforjobicons.rsi
        state: working_joe
    - type: Language
      preset: AU14LanguagePresetSynth
    - type: LanguageLearning
      preset: AU14LanguageLearningPresetSynth
