# base
- type: entity
  parent: RMCArmbandBase
  id: CMU14ChevronLACNBase
  abstract: true
  suffix: LACN Chevron
  description: LACN naval rank insignia. The pin leaves a green stain against your lapel, but it matches the Latin Commando uniform so they've yet to revise it.

# ├──[ Enlisted ]────────────────────────────────────────────────────┤

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNSailor
  name: sailor chevron
  components:
  - type: Sprite
    sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_enlisted
  - type: UniformAccessory
    playerSprite:
      sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_enlisted
  - type: RankChanger
    rank: CMU14RankLACNSailor
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNSailorFirstClass
  name: first class sailor chevron
  components:
  - type: Sprite
    sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_enlisted
  - type: UniformAccessory
    playerSprite:
      sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_enlisted
  - type: RankChanger
    rank: CMU14RankLACNSailorFirstClass
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNThirdClassCorporal
  name: third class corporal chevron
  components:
  - type: Sprite
    sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_enlisted
  - type: UniformAccessory
    playerSprite:
      sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_enlisted
  - type: RankChanger
    rank: CMU14RankLACNThirdClassCorporal
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNSecondClassCorporal
  name: second class corporal chevron
  components:
  - type: Sprite
    sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_nco
  - type: UniformAccessory
    playerSprite:
      sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_nco
  - type: RankChanger
    rank: CMU14RankLACNSecondClassCorporal
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNFirstClassCorporal
  name: first class corporal chevron
  components:
  - type: Sprite
    sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_nco
  - type: UniformAccessory
    playerSprite:
      sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_nco
  - type: RankChanger
    rank: CMU14RankLACNFirstClassCorporal
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNThirdClassSergeant
  name: third class sergeant chevron
  components:
  - type: Sprite
    sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_nco
  - type: UniformAccessory
    playerSprite:
      sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_nco
  - type: RankChanger
    rank: CMU14RankLACNThirdClassSergeant
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNSecondClassSergeant
  name: second class sergeant chevron
  components:
  - type: Sprite
    sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_snco
  - type: UniformAccessory
    playerSprite:
      sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_snco
  - type: RankChanger
    rank: CMU14RankLACNSecondClassSergeant
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNFirstClassSergeant
  name: first class sergeant chevron
  components:
  - type: Sprite
    sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_snco
  - type: UniformAccessory
    playerSprite:
      sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_snco
  - type: RankChanger
    rank: CMU14RankLACNFirstClassSergeant
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNMasterSergeant
  name: master sergeant chevron
  components:
  - type: Sprite
    sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_snco
  - type: UniformAccessory
    playerSprite:
      sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_snco
  - type: RankChanger
    rank: CMU14RankLACNMasterSergeant
    override: true

# ├──[ Officers ]────────────────────────────────────────────────────┤

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNEnsign
  name: ensign chevron
  components:
  - type: Sprite
    sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_officer
  - type: UniformAccessory
    playerSprite:
      sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_officer
  - type: RankChanger
    rank: CMU14RankLACNEnsign
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNShipLineLieutenant
  name: ship of the line lieutenant chevron
  components:
  - type: Sprite
    sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_officer
  - type: UniformAccessory
    playerSprite:
      sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_officer
  - type: RankChanger
    rank: CMU14RankLACNShipLineLieutenant
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNCorvetteCaptain
  name: corvette captain chevron
  components:
  - type: Sprite
    sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_officer
  - type: UniformAccessory
    playerSprite:
      sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_officer
  - type: RankChanger
    rank: CMU14RankLACNCorvetteCaptain
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNFrigateCaptain
  name: frigate captain chevron
  components:
  - type: Sprite
    sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_officer
  - type: UniformAccessory
    playerSprite:
      sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_officer
  - type: RankChanger
    rank: CMU14RankLACNFrigateCaptain
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNCaptain
  name: captain chevron
  components:
  - type: Sprite
    sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_officer
  - type: UniformAccessory
    playerSprite:
      sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_officer
  - type: RankChanger
    rank: CMU14RankLACNCaptain
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNCounterAdmiral
  name: counter admiral chevron
  components:
  - type: Sprite
    sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_officer
  - type: UniformAccessory
    playerSprite:
      sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_officer
  - type: RankChanger
    rank: CMU14RankLACNCounterAdmiral
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNViceAdmiral
  name: vice admiral chevron
  components:
  - type: Sprite
    sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_seniorofficer
  - type: UniformAccessory
    playerSprite:
      sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_officer
  - type: RankChanger
    rank: CMU14RankLACNViceAdmiral
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNAdmiral
  name: admiral chevron
  components:
  - type: Sprite
    sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_flagofficer
  - type: UniformAccessory
    playerSprite:
      sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_flagofficer
  - type: RankChanger
    rank: CMU14RankLACNAdmiral
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNAdmiralGeneral
  name: admiral general chevron
  components:
  - type: Sprite
    sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_flagofficer
  - type: UniformAccessory
    playerSprite:
      sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_flagofficer
  - type: RankChanger
    rank: CMU14RankLACNAdmiralGeneral
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNCaptainGeneral
  name: captain general of the navy chevron
  components:
  - type: Sprite
    sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_flagofficer
  - type: UniformAccessory
    playerSprite:
      sprite: CMU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_flagofficer
  - type: RankChanger
    rank: CMU14RankLACNCaptainGeneral
    override: true