- type: entity
  parent: AdminObserver
  id: RMCAdminObserver
  categories: [ HideSpawnMenu ]
  components:
  - type: PropCaller
  - type: Language # CMU14: aghosts must speak any language over phones and radios
    defaultLanguage: English
  - type: AllLanguages
  - type: Loadout
    prototypes: [ RMCMobAghostGear ]
  - type: IntrinsicUI
    uis: { }

- type: startingGear
  parent: MobAghostGear
  id: RMCMobAghostGear
  equipment:
    back: ClothingBackpackSatchelHolding
    id: RMCAdminPDA
  storage:
    back:
    - CMUAdminAccessConfigurator # CMU14
    - HandheldHealthAnalyzer # CMU14
    - CMHealthAnalyzer
    - DoorRemoteAll
    - AdminHypo
    - MeleeDebug200
    - MeleeDebugGibInsane # CMU14
    - CMUDebugLightningStick # CMU14
#   - ToolDebug # CMU14
    - AU14MaintenanceJackSpecialAdmin # CMU14
    - AU14TabletGovfor #CMU14
    - AU14TabletOpfor # CMU14
    - RMCWelderAdmin
    - CMMultitool
    - CMTRayScanner # CMU14
    - CMUAtmosScanner # CMU14
    - HolofanProjectorDebug # CMU14
