using Content.Shared.CMU14.Round.Antags.Rider;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;

namespace Content.Client.CMU14.Round.Antags.Rider;

[GenerateTypedNameReferences]
public sealed partial class RiderLocatorWindow : DefaultWindow
{
    private ItemList.Item? _selected;

    public event Action<NetEntity>? SetFollowTarget;

    public RiderLocatorWindow()
    {
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("rider-locator-title");
        FollowButton.Text = Loc.GetString("rider-locator-follow");
        FollowButton.Disabled = true;

        RiderList.OnItemSelected += args =>
        {
            _selected = args.ItemList[args.ItemIndex];
            FollowButton.Disabled = false;
        };

        RiderList.OnItemDeselected += args =>
        {
            _selected = null;
            FollowButton.Disabled = true;
        };

        FollowButton.OnPressed += _ =>
        {
            if (_selected?.Metadata is NetEntity rider)
                SetFollowTarget?.Invoke(rider);
        };
    }

    public void UpdateRiders(List<RiderLocatorEntry> riders)
    {
        var selected = _selected?.Metadata is NetEntity netRider ? netRider : default(NetEntity?);

        RiderList.Clear();
        _selected = null;
        FollowButton.Disabled = true;

        foreach (var entry in riders)
        {
            var item = RiderList.AddItem($"{entry.RiderName} - {entry.HostName}");
            item.Metadata = entry.Rider;

            if (entry.Rider == selected)
            {
                item.Selected = true;
                _selected = item;
                FollowButton.Disabled = false;
            }
        }
    }
}
