- type: job
  parent: CMJobXenoBase
  id: CMUJobPathogenBloodburster
  name: cmu-job-name-pathogen-bloodburster
  playTimeTracker: CMUJobPathogenBloodburster
  supervisors: cmu-job-name-pathogen-overmind
 
- type: playTimeTracker
  id: CMUJobPathogenBloodburster
  isXeno: true