- type: job
  parent: CMJobXenoBase
  id: CMU14JobPathogenBrute
  name: cmu-job-name-pathogen-brute
  playTimeTracker: CMU14JobPathogenBrute
  supervisors: cmu-job-name-pathogen-overmind
 
- type: playTimeTracker
  id: CMU14JobPathogenBrute
  isXeno: true