- type: job
  parent: CMJobXenoBase
  id: CMU14JobPathogenHarbinger
  name: cmu-job-name-pathogen-harbinger
  playTimeTracker: CMU14JobPathogenHarbinger
  supervisors: cmu-job-name-pathogen-overmind
 
- type: playTimeTracker
  id: CMU14JobPathogenHarbinger
  isXeno: true