- type: job
  parent: CMJobXenoBase
  id: CMU14JobPathogenMatriarch
  name: cmu-job-name-pathogen-matriarch
  playTimeTracker: CMU14JobPathogenMatriarch
  supervisors: cmu-job-name-pathogen-overmind
 
- type: playTimeTracker
  id: CMU14JobPathogenMatriarch
  isXeno: true