- type: job
  parent: CMJobXenoBase
  id: CMU14JobPathogenOvermind
  name: cmu-job-name-pathogen-overmind
  playTimeTracker: CMU14JobPathogenOvermind
  supervisors: cm-job-supervisors-nobody
 
- type: playTimeTracker
  id: CMU14JobPathogenOvermind
  isXeno: true
