- type: job
  parent: CMJobXenoBase
  id: CMU14JobPathogenRoot
  name: cmu-job-name-pathogen-root
  playTimeTracker: CMU14JobPathogenRoot
  supervisors: cmu-job-name-pathogen-overmind
 
- type: playTimeTracker
  id: CMU14JobPathogenRoot
  isXeno: true