- type: job
<<<<<<< HEAD:Resources/Prototypes/_CMU14/Roles/Colony/Administration/AU14JobCivilianEthicsAndWellnessAdvisor.yml
  parent: RMCJobRibbonBase # RuCM замена медалей на ленточки для колонистов
=======
  parent: RMCJobRibbonBase
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Resources/Prototypes/CMU14/Roles/Colony/Administration/AU14JobCivilianEthicsAndWellnessAdvisor.yml
  id: AU14JobCivilianEthicsAndWellnessAdvisor
  displayWeight: 8
  roundSide: Civilian
  roundForce: COLONY
  roundRole: CivilianEthicsAndWellnessAdvisor
  roundComponents:
  - type: Skills
    skills:
      RMCSkillMedical: 1
      RMCSkillFireman: 2
      RMCSkillFirearms: 2
      RMCSkillVehicles: 1
      RMCSkillDomestics: 1
  - type: JobPrefix
    prefix: au14-job-prefix-ethicsandwellnessadvisor
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/CMU14/Interface/au14colonyjobicons.rsi
      state: nurse

  name: au14-job-name-ethicsandwellnessadvisor
  description: au14-job-description-ethicsandwellnessadvisor
  setPreference: true
  playTimeTracker: AU14JobCivilianEthicsAndWellnessAdvisor
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5 hours
  - !type:AgeRequirement
    requiredAge: 21
  - !type:TraitsRequirement
    inverted: true
    traits:
    - NonResuscitable
    - NoEnglish
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCivilianEthicsAndWellnessAdvisor
  icon: "AU14JobIconColonyNurse"
  hasIcon: false
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  accessGroups:
  - Colonist
  - aumed
  roleWeight: 0.25

- type: startingGear
  id: AU14GearCivilianEthicsAndWellnessAdvisor
  equipment:
    jumpsuit: AU14CivilianWorkwearPink
    shoes: RMCShoesBlack
    id: AU14IDCardColonyEthicsAndWellnessAdvisor
    outerClothing: AU14CivilianJacketGrayPufferJacket
    back: CMSatchel

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianEthicsAndWellnessAdvisor
  name: Spawn Point Civilian Ethics And Wellness Advisor
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianEthicsAndWellnessAdvisor
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianEthicsAndWellnessAdvisor
  isHumanoid: true
