- type: job
<<<<<<< HEAD:Resources/Prototypes/_CMU14/Roles/Colony/Administration/AU14JobCivilianColonyAdministrator.yml
  parent: RMCJobRibbonBase # RuCM замена медалей на ленточки для колонистов
=======
  parent: RMCJobRibbonBase
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Resources/Prototypes/CMU14/Roles/Colony/Administration/AU14JobCivilianColonyAdministrator.yml
  id: AU14JobCivilianColonyAdministrator
  roundSide: Civilian
  roundForce: COLONY
  roundRole: CivilianColonyAdministrator
  roundComponents:
  - type: Skills
    skills:
      RMCSkillCqc: 1
      RMCSkillEndurance: 1
      RMCSkillEngineer: 1
      RMCSkillConstruction: 1
      RMCSkillOverwatch: 1
      RMCSkillResearch: 1
      RMCSkillPolice: 1
      RMCSkillFireman: 1
      RMCSkillVehicles: 1
      RMCSkillIntel: 1
      RMCSkillDomestics: 1
      RMCSkillNavigations: 1
      RMCSkillFirearms: 2
  - type: MarineOrders
  - type: JobPrefix
    prefix: au14-job-prefix-colonyadministrator
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/CMU14/Interface/au14colonyjobicons.rsi
      state: admin

  name: au14-job-name-civiliancolonyadministrator
  description: au14-job-description-civiliancolonyadministrator
  setPreference: true
  playTimeTracker: AU14JobCivilianColonyAdministrator
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5 hours
  - !type:AgeRequirement
    requiredAge: 21
  - !type:TraitsRequirement
    inverted: true
    traits:
    - NonResuscitable
    - NoEnglish
  ranks:
    AU14RankColonySeniorAdministrator:
    - !type:RoleTimeRequirement
      role: AU14JobCivilianColonyAdministrator
      time: 108000 # 30 hours
    AU14RankColonyAdministrator: []
  startingGear: AU14GearCivilianColonyAdministrator
  icon: "AU14JobIconColonyAdmin"
  requireAdminNotify: true
  joinNotifyCrew: false
  canBeAntag: false
<<<<<<< HEAD:Resources/Prototypes/_CMU14/Roles/Colony/Administration/AU14JobCivilianColonyAdministrator.yml
  # whitelisted: true // RuCM удаление вайтлиста для администратора колонии
  # whitelistParent: CMUJobCommandWhitelist // RuCM удаление вайтлиста для администратора колонии
=======
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Resources/Prototypes/CMU14/Roles/Colony/Administration/AU14JobCivilianColonyAdministrator.yml
  supervisors: au14-job-supervisors-colonyadministrator
  accessGroups:
  - auadmin
  - Colonist
  - CMCargoTech
  - auheadsofcolony
  access:
  - AU14AccessColonyAdministrator
  - AU14AccessColonyMarshall
  roleWeight: 0.25
  displayWeight: 22

- type: startingGear
  id: AU14GearCivilianColonyAdministrator
  equipment:
    shoes: RMCShoesLaceupBrown
    id: AU14IDCardColonyAdministrator
    ears: AU14ColonyAdminHeadset
    outerClothing: RMCJacketCorporateBlue
    pocket1: AU14GuidebookLawColonial
    pocket2: AU14StampAdmin
  inhand:
  - RMCRadioHandheldColonyOff

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianColonyAdministrator
  name: Spawn Point Colony Administrator
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianColonyAdministrator
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianColonyAdministrator
  isHumanoid: true

- type: roleLoadout
  id: JobAU14JobCivilianColonyAdministrator
  points: 50 #Make sure to revist the amount of points here after this has been merged for a bit, as this is initally a rather arbitrary amount
  groups:
  - CivSatchelAU14
  - CivFootwearAU14
  - CivJumpsuitAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC
  - EyewearRMC
  - MasksRMC
  - HeadwearCLFAU14
  - ColonyAdministratorBeltCMU
  - ColonyAdministratorSkillsAU14

- type: loadoutGroup
  id: ColonyAdministratorSkillsAU14
  name: au14-loadout-group-colony-administrator-skills
  minLimit: 0
  maxLimit: 21
  loadouts:
  - ColonyAdministratorLeadershipSkillAU14
  - ColonyAdministratorMedicalSkillAU14
  - ColonyAdministratorCqcSkillAU14
  - ColonyAdministratorEnduranceSkillAU14
  - ColonyAdministratorMeleeWeaponsSkillAU14
  - ColonyAdministratorSurgerySkillAU14
  - ColonyAdministratorEngineerSkillAU14
  - ColonyAdministratorConstructionSkillAU14
  - ColonyAdministratorPoliceSkillAU14

- type: loadout
  id: ColonyAdministratorLeadershipSkillAU14
  dummyEntity: RMCSkillLeadership
  cost: 5
  maxSelections: 4
  effects:
  - !type:SkillLoadoutEffect
    skill: RMCSkillLeadership
    amount: 1

- type: loadout
  id: ColonyAdministratorMedicalSkillAU14
  dummyEntity: RMCSkillMedical
  cost: 5
  maxSelections: 4
  effects:
  - !type:SkillLoadoutEffect
    skill: RMCSkillMedical
    amount: 1

- type: loadout
  id: ColonyAdministratorCqcSkillAU14
  dummyEntity: RMCSkillCqc
  cost: 5
  maxSelections: 2
  effects:
  - !type:SkillLoadoutEffect
    skill: RMCSkillCqc
    amount: 1

- type: loadout
  id: ColonyAdministratorEnduranceSkillAU14
  dummyEntity: RMCSkillEndurance
  cost: 5
  maxSelections: 2
  effects:
  - !type:SkillLoadoutEffect
    skill: RMCSkillEndurance
    amount: 1

- type: loadout
  id: ColonyAdministratorMeleeWeaponsSkillAU14
  dummyEntity: RMCSkillMeleeWeapons
  cost: 5
  maxSelections: 1
  effects:
  - !type:SkillLoadoutEffect
    skill: RMCSkillMeleeWeapons
    amount: 1

- type: loadout
  id: ColonyAdministratorSurgerySkillAU14
  dummyEntity: RMCSkillSurgery
  cost: 5
  maxSelections: 2
  effects:
  - !type:SkillLoadoutEffect
    skill: RMCSkillSurgery
    amount: 1

- type: loadout
  id: ColonyAdministratorEngineerSkillAU14
  dummyEntity: RMCSkillEngineer
  cost: 5
  maxSelections: 2
  effects:
  - !type:SkillLoadoutEffect
    skill: RMCSkillEngineer
    amount: 1

- type: loadout
  id: ColonyAdministratorConstructionSkillAU14
  dummyEntity: RMCSkillConstruction
  cost: 5
  maxSelections: 2
  effects:
  - !type:SkillLoadoutEffect
    skill: RMCSkillConstruction
    amount: 1

- type: loadout
  id: ColonyAdministratorPoliceSkillAU14
  dummyEntity: RMCSkillPolice
  cost: 5
  maxSelections: 1
  effects:
  - !type:SkillLoadoutEffect
    skill: RMCSkillPolice
    amount: 1
