### Counselates
## UPP
- type: rank
  id: RUMC14RankCounselateUPPAmbassador
  name: UPP Ambassador
  prefix: Amb.
  paygrade: UPP-EMB11

- type: rank
  id: RUMC14RankCounselateUPPEnvoy1
  name: UPP 1st Class Envoy
  prefix: Env.
  paygrade: UPP-EMB10

- type: rank
  id: RUMC14RankCounselateUPPEnvoy2
  name: UPP 2nd Class Envoy
  prefix: Env.
  paygrade: UPP-EMB9

- type: rank
  id: RUMC14RankCounselateUPPCounselor1
  name: UPP Counselor 1st Class
  prefix: Coun.
  paygrade: UPP-EMB8

- type: rank
  id: RUMC14RankCounselateUPPCounselor2
  name: UPP Counselor 2nd Class
  prefix: Coun.
  paygrade: UPP-EMB7

- type: rank
  id: RUMC14RankCounselateUPPFirstSecretary1
  name: UPP First Secretary 1st Class
  prefix: Sec.
  paygrade: UPP-EMB6

- type: rank
  id: RUMC14RankCounselateUPPFirstSecretary2
  name: UPP First Secretary 2nd Class
  prefix: Sec.
  paygrade: UPP-EMB5

- type: rank
  id: RUMC14RankCounselateUPPSecondSecretary1
  name: UPP Second Secretary 1st Class
  prefix: Sec.
  paygrade: UPP-EMB4

- type: rank
  id: RUMC14RankCounselateUPPSecondSecretary2
  name: UPP Second Secretary 2nd Class
  prefix: Sec.
  paygrade: UPP-EMB3

- type: rank
  id: RUMC14RankCounselateUPPThirdSecretary
  name: UPP Third Secretary
  prefix: Sec.
  paygrade: UPP-EMB2

- type: rank
  id: RUMC14RankCounselateUPPAttache
  name: UPP Attache
  prefix: Att.
  paygrade: UPP-EMB1

## UA
- type: rank
  id: RUMC14RankCounselateUAAmbassador
  name: UA Ambassador
  prefix: Amb.
  paygrade: UA-EMB11

- type: rank
  id: RUMC14RankCounselateUAEnvoy1
  name: UA 1st Class Envoy
  prefix: Env.
  paygrade: UA-EMB10

- type: rank
  id: RUMC14RankCounselateUAEnvoy2
  name: UA 2nd Class Envoy
  prefix: Env.
  paygrade: UA-EMB9

- type: rank
  id: RUMC14RankCounselateUACounselor1
  name: UA Counselor 1st Class
  prefix: Coun.
  paygrade: UA-EMB8

- type: rank
  id: RUMC14RankCounselateUACounselor2
  name: UA Counselor 2nd Class
  prefix: Coun.
  paygrade: UA-EMB7

- type: rank
  id: RUMC14RankCounselateUAFirstSecretary1
  name: UA First Secretary 1st Class
  prefix: Sec.
  paygrade: UA-EMB6

- type: rank
  id: RUMC14RankCounselateUAFirstSecretary2
  name: UA First Secretary 2nd Class
  prefix: Sec.
  paygrade: UA-EMB5

- type: rank
  id: RUMC14RankCounselateUASecondSecretary1
  name: UA Second Secretary 1st Class
  prefix: Sec.
  paygrade: UA-EMB4

- type: rank
  id: RUMC14RankCounselateUASecondSecretary2
  name: UA Second Secretary 2nd Class
  prefix: Sec.
  paygrade: UA-EMB3

- type: rank
  id: RUMC14RankCounselateUAThirdSecretary
  name: UA Third Secretary
  prefix: Sec.
  paygrade: UA-EMB2

- type: rank
  id: RUMC14RankCounselateUAAttache
  name: UA Attache
  prefix: Att.
  paygrade: UA-EMB1

## TWE
- type: rank
  id: RUMC14RankCounselateTWEAmbassador
  name: TWE Ambassador
  prefix: Amb.
  paygrade: TWE-EMB11

- type: rank
  id: RUMC14RankCounselateTWEEnvoy1
  name: TWE 1st Class Envoy
  prefix: Env.
  paygrade: TWE-EMB10

- type: rank
  id: RUMC14RankCounselateTWEEnvoy2
  name: TWE 2nd Class Envoy
  prefix: Env.
  paygrade: TWE-EMB9

- type: rank
  id: RUMC14RankCounselateTWECounselor1
  name: TWE Counselor 1st Class
  prefix: Coun.
  paygrade: TWE-EMB8

- type: rank
  id: RUMC14RankCounselateTWECounselor2
  name: TWE Counselor 2nd Class
  prefix: Coun.
  paygrade: TWE-EMB7

- type: rank
  id: RUMC14RankCounselateTWEFirstSecretary1
  name: TWE First Secretary 1st Class
  prefix: Sec.
  paygrade: TWE-EMB6

- type: rank
  id: RUMC14RankCounselateTWEFirstSecretary2
  name: TWE First Secretary 2nd Class
  prefix: Sec.
  paygrade: TWE-EMB5

- type: rank
  id: RUMC14RankCounselateTWESecondSecretary1
  name: TWE Second Secretary 1st Class
  prefix: Sec.
  paygrade: TWE-EMB4

- type: rank
  id: RUMC14RankCounselateTWESecondSecretary2
  name: TWE Second Secretary 2nd Class
  prefix: Sec.
  paygrade: TWE-EMB3

- type: rank
  id: RUMC14RankCounselateTWEThirdSecretary
  name: TWE Third Secretary
  prefix: Sec.
  paygrade: TWE-EMB2

- type: rank
  id: RUMC14RankCounselateTWEAttache
  name: TWE Attache
  prefix: Att.
  paygrade: TWE-EMB1

## Common
- type: rank
  id: RUMC14RankCounselateCommonAmbassador
  name: Ambassador
  prefix: Amb.

- type: rank
  id: RUMC14RankCounselateCommonEnvoy1
  name: 1st Class Envoy
  prefix: Env.

- type: rank
  id: RUMC14RankCounselateCommonEnvoy2
  name: 2nd Class Envoy
  prefix: Env.

- type: rank
  id: RUMC14RankCounselateCommonCounselor1
  name: Counselor 1st Class
  prefix: Coun.

- type: rank
  id: RUMC14RankCounselateCommonCounselor2
  name: Counselor 2nd Class
  prefix: Coun.

- type: rank
  id: RUMC14RankCounselateCommonFirstSecretary1
  name: First Secretary 1st Class
  prefix: Sec.

- type: rank
  id: RUMC14RankCounselateCommonFirstSecretary2
  name: First Secretary 2nd Class
  prefix: Sec.

- type: rank
  id: RUMC14RankCounselateCommonSecondSecretary1
  name: Second Secretary 1st Class
  prefix: Sec.

- type: rank
  id: RUMC14RankCounselateCommonSecondSecretary2
  name: Second Secretary 2nd Class
  prefix: Sec.

- type: rank
  id: RUMC14RankCounselateCommonThirdSecretary
  name: Third Secretary
  prefix: Sec.

- type: rank
  id: RUMC14RankCounselateCommonAttache
  name: Attache
  prefix: Att.