# Administration
- type: rank
  id: AU14RankColonyAdministrator
  name: Administrator
  prefix: Admin.

- type: rank
  id: AU14RankColonySeniorAdministrator
  name: Senior Administrator
  prefix: Sr. Admin.

- type: rank
  id: AU14RankColonySeniorAdminAssistant
  name: Senior Deputy Administrator
  prefix: Sr. Dep. Admin.

- type: rank
  id: AU14RankColonyAdminAssistant
  name: Deputy Administrator
  prefix: Dep. Admin.

# Diplomatic
- type: rank
  id: AU14RankTWEAmbassador
  name: High Commisioner
  prefix: High Comm.

- type: rank
  id: AU14RankAmbassador
  name: Ambassador
  prefix: Amb.
