- type: department
  parent: CMDepartmentBase
  id: AU14DepartmentThreat
  name:  au-job-name-threat-member
  description: au14-department-threat-description
  color: "#e3ce94"
  faction: hunt
  roles:
  - AU14JobThreatLeader
  - AU14JobThreatMember
  - CMUYautjaHunter
  departmentRadio: null
  headOfDepartment: null
