using Content.Client.CMU14.CharacterDescription.UI;
using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Content.Shared.CMU14.FactionRoster;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.FactionRoster;

[GenerateTypedNameReferences]
public sealed partial class FactionRosterEntryWindow : DefaultWindow
{
    [Dependency] private  IStylesheetManager _stylesheetManager = default!;

    public FactionRosterEntryWindow(FactionRosterEntry entry)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Stylesheet = _stylesheetManager.SheetNano;
        CrtLobbyTheme.ApplyWindow(this, useCrtTypography: true);

        Title = entry.Name;

        CharacterDescriptionRowBuilder.AddHeading(ContentContainer, $"{entry.Name} — {entry.Job}");
        CharacterDescriptionRowBuilder.AddRow(ContentContainer, Loc.GetString("detailed-examine-age"), entry.Age > 0 ? entry.Age.ToString() : null, Loc.GetString("detailed-examine-age-tooltip"));
        CharacterDescriptionRowBuilder.AddRow(ContentContainer, Loc.GetString("detailed-examine-height"), entry.Height, Loc.GetString("detailed-examine-height-tooltip"));
        CharacterDescriptionRowBuilder.AddRow(ContentContainer, Loc.GetString("detailed-examine-weight"), entry.Weight > 0 ? Loc.GetString("detailed-examine-weight-value", ("weight", entry.Weight)) : null, Loc.GetString("detailed-examine-weight-tooltip"));
        CharacterDescriptionRowBuilder.AddRow(ContentContainer, Loc.GetString("detailed-examine-build"), entry.Build, Loc.GetString("detailed-examine-build-tooltip"));
        CharacterDescriptionRowBuilder.AddRow(ContentContainer, Loc.GetString("detailed-examine-skin-tone"), entry.SkinToneName, Loc.GetString("detailed-examine-skin-tone-tooltip"));
        CharacterDescriptionRowBuilder.AddRow(ContentContainer, Loc.GetString("detailed-examine-hair-color"), entry.HairColorName, Loc.GetString("detailed-examine-hair-color-tooltip"));
        CharacterDescriptionRowBuilder.AddRow(ContentContainer, Loc.GetString("detailed-examine-eye-color"), entry.EyeColorName, Loc.GetString("detailed-examine-eye-color-tooltip"));
        CharacterDescriptionRowBuilder.AddRow(ContentContainer, Loc.GetString("detailed-examine-allegiance"), entry.Allegiance, Loc.GetString("detailed-examine-allegiance-tooltip"));
        CharacterDescriptionRowBuilder.AddRow(ContentContainer, Loc.GetString("detailed-examine-origin"), entry.Origin, Loc.GetString("detailed-examine-origin-tooltip"));

        CharacterDescriptionRowBuilder.AddSeparator(ContentContainer);

        CharacterDescriptionRowBuilder.AddParagraph(ContentContainer, Loc.GetString("detailed-examine-full-description"), entry.FullDescription, Loc.GetString("detailed-examine-full-description-tooltip"));
        CharacterDescriptionRowBuilder.AddParagraph(ContentContainer, Loc.GetString("detailed-examine-medical-record"), entry.MedicalRecord, Loc.GetString("detailed-examine-medical-record-tooltip"));
        CharacterDescriptionRowBuilder.AddParagraph(ContentContainer, Loc.GetString("detailed-examine-criminal-record"), entry.CriminalRecord, Loc.GetString("detailed-examine-criminal-record-tooltip"));
        CharacterDescriptionRowBuilder.AddParagraph(ContentContainer, Loc.GetString("detailed-examine-general-record"), entry.GeneralRecord, Loc.GetString("detailed-examine-general-record-tooltip"));

        CrtLobbyTheme.Apply(ContentContainer);
    }
}
