using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Content.Shared.CMU14.FactionRoster;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.FactionRoster;

[GenerateTypedNameReferences]
public sealed partial class FactionRosterConsoleWindow : DefaultWindow
{
    [Dependency] private  IStylesheetManager _stylesheetManager = default!;

    private readonly List<FactionRosterEntryWindow> _openEntryWindows = new();

    public event Action? OnRefresh;

    public FactionRosterConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Stylesheet = _stylesheetManager.SheetNano;
        CrtLobbyTheme.ApplyWindow(this, useCrtTypography: true);

        RefreshButton.OnPressed += _ => OnRefresh?.Invoke();
        OnClose += CloseEntryWindows;
    }

    public void UpdateState(FactionRosterConsoleBuiState state)
    {
        ContentContainer.DisposeAllChildren();
        CountLabel.Text = Loc.GetString("faction-roster-console-count", ("count", state.Entries.Count));

        foreach (var entry in state.Entries)
        {
            var button = new Button
            {
                Text = $"{entry.Name} — {entry.Job}",
                HorizontalExpand = true,
                ToolTip = Loc.GetString("faction-roster-console-entry-tooltip", ("name", entry.Name)),
            };

            button.OnPressed += _ => OpenEntry(entry);

            ContentContainer.AddChild(button);
        }

        CrtLobbyTheme.Apply(ContentContainer);
    }

    private void OpenEntry(FactionRosterEntry entry)
    {
        var window = new FactionRosterEntryWindow(entry);
        _openEntryWindows.Add(window);
        window.OnClose += () => _openEntryWindows.Remove(window);
        window.OpenCentered();
    }

    private void CloseEntryWindows()
    {
        foreach (var window in _openEntryWindows.ToArray())
        {
            window.Close();
        }

        _openEntryWindows.Clear();
    }
}
