using Content.Shared.CMU14.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.Paper;

[GenerateTypedNameReferences]
public sealed partial class UniversalPaperToolWindow : DefaultWindow
{
    public event Action<string>? OnPrint;

    private UniversalPaperToolBuiState? _state;

    public UniversalPaperToolWindow()
    {
        RobustXamlLoader.Load(this);

        HeaderLabel.Text = Loc.GetString("cmu-universal-paper-tool-header");
        ExitButton.OnPressed += _ => Close();
<<<<<<< HEAD:Content.Client/_CMU14/Paper/UniversalPaperToolWindow.xaml.cs
        Title = Loc.GetString("cmu-universal-paper-tool-window-title"); // RuMC edit
=======
        Title = Loc.GetString("cmu-universal-paper-tool-window-title");
>>>>>>> ee5c3f07eab149fc5eabc97c0cc1d76ed75fab34:Content.CMU/Client/Paper/UniversalPaperToolWindow.xaml.cs

        SearchBar.OnTextChanged += _ => RefreshTemplateList();
    }

    public void Populate(UniversalPaperToolBuiState state)
    {
        _state = state;

        PaperStatusLabel.Text = state.HasPaper
            ? Loc.GetString("cmu-universal-paper-tool-paper-loaded")
            : Loc.GetString("cmu-universal-paper-tool-paper-missing");

        RefreshTemplateList();
    }

    private void RefreshTemplateList()
    {
        if (_state == null)
            return;

        TemplateList.RemoveAllChildren();

        var search = SearchBar.Text.Trim();

        foreach (var template in _state.Templates)
        {
            if (!string.IsNullOrWhiteSpace(search) &&
                !template.Name.Contains(search, StringComparison.OrdinalIgnoreCase) &&
                !template.Description.Contains(search, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            var button = new Button
            {
                HorizontalExpand = true,
                Disabled = !_state.HasPaper,
                ToolTip = template.Description,
            };

            var body = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(8, 6),
                HorizontalExpand = true,
            };

            body.AddChild(new Label
            {
                Text = template.Name,
                StyleClasses = { "LabelKeyText" },
                ClipText = true,
            });

            body.AddChild(new Label
            {
                Text = template.Description,
                StyleClasses = { "LabelSubText" },
                ClipText = true,
            });

            button.AddChild(body);
            button.OnPressed += _ => OnPrint?.Invoke(template.Prototype);

            TemplateList.AddChild(button);
        }
    }
}
