- type: randomHumanoidSettings
  parent: RMCEventHumanoid
  id: RMCCorpse
  components:
  - type: Damageable
    damage:
      types:
        Bloodloss: 36
        Asphyxiation: 44
        Slash: 77
        Blunt: 43
  - type: DamageMobState # CMU14
    critDamage:
      types:
        Asphyxiation: 1
    nonDeadDamage:
      types:
        Asphyxiation: -0.33
  - type: Rank
    rank: RMCRankCivilian
#  - type: Loadout # it seems that cm-ss13 doesnt use this loadout
#    prototypes: [ RMCGearCorpse ]

- type: startingGear
  id: RMCGearCorpse
  equipment:
    jumpsuit: CMJumpsuitColonist
    back: CMSatchel
    id: CMIDCardColonist

# TODO RMC14 random equipment and weapon
