using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._RMC14.Chemistry.Reagent;
using Content.Shared.Chemistry.EntitySystems;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Containers.ItemSlots;
using Content.Shared.Kitchen;
using Content.Shared.Kitchen.Components;
using Content.Shared.Kitchen.EntitySystems;
using Content.Shared.Power.EntitySystems;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Kitchen.UI;

[GenerateTypedNameReferences]
public sealed partial class GrinderMenu : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;

    private readonly ItemSlotsSystem _slots;
    private readonly SharedPowerReceiverSystem _power;
    private readonly SharedReagentGrinderSystem _grinder;
    private readonly SharedSolutionContainerSystem _solutionContainer;
    private readonly RMCReagentSystem _reagent;

    private readonly Dictionary<int, EntityUid> _chamberVisualContents = new();
    private readonly StyleBoxFlat _panelBox = new();
    private EntityUid _owner;

    public event Action? OnToggleAuto;
    public event Action? OnGrind;
    public event Action? OnJuice;
    public event Action? OnLink;
    public event Action? OnEjectAll;
    public event Action? OnEjectBeaker;
    public event Action<EntityUid>? OnEjectChamber;
    public event Action<ReagentQuantity>? OnBottle;
    public event Action<ReagentQuantity>? OnDisposeReagent;

    public GrinderMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _slots = _entityManager.System<ItemSlotsSystem>();
        _power = _entityManager.System<SharedPowerReceiverSystem>();
        _grinder = _entityManager.System<SharedReagentGrinderSystem>();
        _solutionContainer = _entityManager.System<SharedSolutionContainerSystem>();
        _reagent = _entityManager.System<RMCReagentSystem>();
        _panelBox.BackgroundColor = Color.FromHex("#373744");

        AutoModeButton.OnPressed += _ => OnToggleAuto?.Invoke();
        GrindButton.OnPressed += _ => OnGrind?.Invoke();
        JuiceButton.OnPressed += _ => OnJuice?.Invoke();
        LinkButton.OnPressed += _ => OnLink?.Invoke();
        ChamberContentBox.EjectButton.OnPressed += _ => OnEjectAll?.Invoke();
        BeakerContentBox.EjectButton.OnPressed += _ => OnEjectBeaker?.Invoke();
        ChamberContentBox.BoxContents.OnItemSelected += OnChamberBoxContentsItemSelected;
        BeakerContentBox.BoxContents.SelectMode = ItemList.ItemListSelectMode.None;
    }

    private void OnChamberBoxContentsItemSelected(ItemList.ItemListSelectedEventArgs args)
    {
        OnEjectChamber?.Invoke(_chamberVisualContents[args.ItemIndex]);
    }

    /// <summary>
    /// Sets the reagent grinder entity associated with this menu.
    /// </summary>
    public void SetEntity(EntityUid owner)
    {
        _owner = owner;
        UpdateUi();
    }

    /// <summary>
    /// Updates the grinder contents and controls from predicted component state.
    /// </summary>
    public void UpdateUi()
    {
        if (!_entityManager.TryGetComponent<ReagentGrinderComponent>(_owner, out var grinderComp))
            return;

        var active = _grinder.IsActive((_owner, grinderComp));
        var beaker = _slots.GetItemOrNull(_owner, ReagentGrinderComponent.BeakerSlotId);
        var powered = _power.IsPowered(_owner);
        var hasInput = grinderComp.InputContainer.ContainedEntities.Any();
        var canGrind = hasInput && grinderComp.InputContainer.ContainedEntities.All(entity => _grinder.CanGrind(entity));
        var canJuice = hasInput && grinderComp.InputContainer.ContainedEntities.All(entity => _grinder.CanJuice(entity));
        var linked = grinderComp.SmartFridge != null;

        BeakerContentBox.EjectButton.Disabled = active || !beaker.HasValue;
        ChamberContentBox.EjectButton.Disabled = active || !hasInput;
        GrindButton.Disabled = active || !canGrind || !powered || !beaker.HasValue;
        JuiceButton.Disabled = active || !canJuice || !powered || !beaker.HasValue;
        LinkButton.Disabled = active || linked || !powered;
        GrindButton.Modulate = grinderComp.Program == GrinderProgram.Grind ? Color.Green : Color.White;
        JuiceButton.Modulate = grinderComp.Program == GrinderProgram.Juice ? Color.Green : Color.White;

        AutoModeButton.Text = grinderComp.AutoMode switch
        {
            GrinderAutoMode.Grind => Loc.GetString("grinder-menu-grind-button"),
            GrinderAutoMode.Juice => Loc.GetString("grinder-menu-juice-button"),
            _ => Loc.GetString("grinder-menu-auto-button-off"),
        };

        RefreshChamberContents(grinderComp);
        RefreshBeakerContents(beaker, linked && !active);
    }

    private void RefreshChamberContents(ReagentGrinderComponent grinder)
    {
        _chamberVisualContents.Clear();
        ChamberContentBox.BoxContents.Clear();

        foreach (var entity in grinder.InputContainer.ContainedEntities)
        {
            if (!_entityManager.EntityExists(entity))
                continue;

            var texture = _entityManager.GetComponent<SpriteComponent>(entity).Icon?.Default;
            var item = ChamberContentBox.BoxContents.AddItem(
                _entityManager.GetComponent<MetaDataComponent>(entity).EntityName,
                texture);
            _chamberVisualContents.Add(ChamberContentBox.BoxContents.IndexOf(item), entity);
        }
    }

    private void RefreshBeakerContents(EntityUid? beaker, bool allowActions)
    {
        BeakerContentBox.BoxContents.Clear();
        ReagentBoxContents.RemoveAllChildren();
        BeakerContentBox.BoxContents.Visible = false;

        if (beaker == null ||
            !_solutionContainer.TryGetFitsInDispenser(beaker.Value, out _, out var reagents))
        {
            return;
        }

        foreach (var (reagentId, quantity) in reagents)
        {
            var reagentName = _reagent.TryIndex(reagentId, out var reagent)
                ? $"{quantity} {reagent.LocalizedName}"
                : "???";

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };
            row.AddChild(new Label { Text = reagentName });

            if (allowActions)
            {
                var reagentQuantity = new ReagentQuantity(reagentId, quantity);
                var bottle = new Button { Text = Loc.GetString("grinder-menu-bottle") };
                bottle.OnPressed += _ => OnBottle?.Invoke(reagentQuantity);
                row.AddChild(bottle);

                var dispose = new Button
                {
                    Text = Loc.GetString("grinder-menu-dispose"),
                    Modulate = Color.Red,
                };
                dispose.OnPressed += _ => OnDisposeReagent?.Invoke(reagentQuantity);
                row.AddChild(dispose);
            }

            var panel = new PanelContainer { PanelOverride = _panelBox };
            panel.AddChild(row);
            ReagentBoxContents.AddChild(panel);
        }
    }
}
