using System.Linq;
using System.Numerics;
using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using Content.Shared.Ghost.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Systems.Ghost.Controls.Roles
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostRolesWindow : DefaultWindow
    {
        [Dependency] private IConfigurationManager _cfg = default!;
        [Dependency] private IEntityManager _entityManager = default!;
        [Dependency] private IStylesheetManager _stylesheetManager = default!;

        public event Action<GhostRoleInfo>? OnRoleRequestButtonClicked;
        public event Action<GhostRoleInfo>? OnRoleFollow;

        private readonly List<EntryState> _entries = new();
        private readonly List<EntityUid> _previewDummies = new();
        private string _searchText = string.Empty;
        private int _availableRoleCount;
        private bool _updatingEntries;
        private Vector2 _entryUpdateScrollValue;

        public GhostRolesWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            ApplyCrtPalette();
            SearchBar.OnTextChanged += OnSearchTextChanged;
            _cfg.OnValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
            _cfg.OnValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
        }

        [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            _cfg.UnsubValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
            _cfg.UnsubValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
            ClearPreviewDummies();
        }

        private void OnCrtUiEnabledChanged(bool _)
        {
            ApplyCrtPalette();
        }

        private void OnCrtUiColorChanged(string _)
        {
            ApplyCrtPalette();
        }

        private void ApplyCrtPalette()
        {
            Stylesheet = _stylesheetManager.SheetNano;
            CrtLobbyTheme.ApplyWindow(this, useCrtTypography: true);
        }

        public void ClearEntries()
        {
            ClearPreviewDummies();
            _availableRoleCount = 0;
            _entries.Clear();
            EntryContainer.RemoveAllChildren();
            if (!_updatingEntries)
                UpdateVisibleEntries();
        }

        public void SaveCollapsibleBoxesStates()
        {
        }

        public void RestoreCollapsibleBoxesStates()
        {
        }

        public void AddEntry(string name, string description, bool hasAccess, FormattedMessage? reason, IEnumerable<GhostRoleInfo> roles, SpriteSystem spriteSystem)
        {
            var ghostRoleInfos = roles.ToList();
            if (ghostRoleInfos.Count == 0)
                return;

            _availableRoleCount += ghostRoleInfos.Count;
            var info = new GhostRoleInfoBox(
                name,
                description,
                ghostRoleInfos[0].Entity,
                ghostRoleInfos[0].EntityPrototype,
                ghostRoleInfos[0].JobPrototype,
                _previewDummies.Add);
            var buttons = new GhostRoleButtonsBox(hasAccess, reason, ghostRoleInfos, spriteSystem);
            buttons.OnRoleSelected += OnRoleRequestButtonClicked;
            buttons.OnRoleFollow += OnRoleFollow;
            info.AddButtons(buttons);
            CrtLobbyTheme.Apply(info);
            CrtLobbyTheme.Apply(buttons);

            EntryContainer.AddChild(info);
            _entries.Add(new EntryState(info, $"{name} {description}"));
            if (!_updatingEntries)
                UpdateVisibleEntries();
        }

        public void BeginEntryUpdate()
        {
            _entryUpdateScrollValue = RoleScroll.GetScrollValue(ignoreVisible: true);
            _updatingEntries = true;
            ClearEntries();
        }

        public void EndEntryUpdate()
        {
            _updatingEntries = false;
            UpdateVisibleEntries();

            RoleScroll.SetScrollValue(_entryUpdateScrollValue);
            RoleScroll.HScrollTarget = _entryUpdateScrollValue.X;
            RoleScroll.VScrollTarget = _entryUpdateScrollValue.Y;
        }

        private void UpdateVisibleEntries()
        {
            CountLabel.Text = Loc.GetString("ghost-roles-window-available-count", ("count", _availableRoleCount));

            var anyVisible = false;
            foreach (var entry in _entries)
            {
                var visible = string.IsNullOrWhiteSpace(_searchText) ||
                              entry.SearchText.Contains(_searchText, StringComparison.OrdinalIgnoreCase);
                entry.Control.Visible = visible;
                anyVisible |= visible;
            }

            ContentPanel.Visible = anyVisible;
            NoRolesMessage.Text = _entries.Count == 0
                ? Loc.GetString("ghost-roles-window-no-roles-available-label")
                : Loc.GetString("ghost-roles-window-no-results-label");
            NoRolesMessage.Visible = !anyVisible;
        }

        private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
        {
            _searchText = args.Text;
            UpdateVisibleEntries();
        }

        private void ClearPreviewDummies()
        {
            foreach (var dummy in _previewDummies)
            {
                _entityManager.DeleteEntity(dummy);
            }

            _previewDummies.Clear();
        }

        private readonly record struct EntryState(Control Control, string SearchText);
    }
}
